-- lumina-canopy-dark -- Lumina (canopy, dark)
-- Generated from spec/lumina.json + spec/nvim_highlights.json.

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = 'dark'
vim.g.colors_name = 'lumina-canopy-dark'

local set = vim.api.nvim_set_hl

set(0, 'Normal', { fg = '#D8E6CE', bg = '#101A12' })
set(0, 'NormalFloat', { fg = '#D8E6CE', bg = '#0C140E' })
set(0, 'FloatBorder', { fg = '#2A3A2C', bg = '#0C140E' })
set(0, 'FloatTitle', { fg = '#D6B25C', bg = '#0C140E', bold = true })
set(0, 'CursorLine', { bg = '#18241A' })
set(0, 'CursorColumn', { bg = '#18241A' })
set(0, 'CursorLineNr', { fg = '#D6B25C', bold = true })
set(0, 'LineNr', { fg = '#384B3A' })
set(0, 'SignColumn', { bg = '#101A12' })
set(0, 'VertSplit', { fg = '#2A3A2C', bg = '#101A12' })
set(0, 'WinSeparator', { fg = '#2A3A2C', bg = '#101A12' })
set(0, 'ColorColumn', { bg = '#18241A' })
set(0, 'Folded', { fg = '#506A52', bg = '#18241A' })
set(0, 'FoldColumn', { fg = '#384B3A', bg = '#101A12' })
set(0, 'EndOfBuffer', { fg = '#101A12' })
set(0, 'NonText', { fg = '#2A3A2C' })
set(0, 'SpecialKey', { fg = '#384B3A' })
set(0, 'Whitespace', { fg = '#2A3A2C' })
set(0, 'MatchParen', { fg = '#7CB377', bg = '#202E22', bold = true })
set(0, 'Cursor', { fg = '#101A12', bg = '#D6B25C' })
set(0, 'iCursor', { link = 'Cursor' })
set(0, 'TermCursor', { link = 'Cursor' })
set(0, 'Visual', { bg = '#2A3A2C' })
set(0, 'VisualNOS', { link = 'Visual' })
set(0, 'Search', { fg = '#101A12', bg = '#D6B25C' })
set(0, 'IncSearch', { fg = '#101A12', bg = '#D6B25C', bold = true })
set(0, 'CurSearch', { fg = '#101A12', bg = '#DD9A5A', bold = true })
set(0, 'Substitute', { link = 'IncSearch' })
set(0, 'StatusLine', { fg = '#97AE8C', bg = '#0C140E' })
set(0, 'StatusLineNC', { fg = '#506A52', bg = '#0C140E' })
set(0, 'TabLine', { fg = '#506A52', bg = '#0C140E' })
set(0, 'TabLineSel', { fg = '#D6B25C', bg = '#101A12', bold = true })
set(0, 'TabLineFill', { bg = '#0C140E' })
set(0, 'WinBar', { fg = '#97AE8C', bg = '#101A12' })
set(0, 'WinBarNC', { fg = '#506A52', bg = '#101A12' })
set(0, 'Pmenu', { fg = '#D8E6CE', bg = '#0C140E' })
set(0, 'PmenuSel', { fg = '#D6B25C', bg = '#202E22', bold = true })
set(0, 'PmenuSbar', { bg = '#202E22' })
set(0, 'PmenuThumb', { bg = '#384B3A' })
set(0, 'ModeMsg', { fg = '#D6B25C', bold = true })
set(0, 'MoreMsg', { fg = '#7CB377' })
set(0, 'MsgArea', { fg = '#D8E6CE' })
set(0, 'WarningMsg', { fg = '#DD9A5A' })
set(0, 'ErrorMsg', { fg = '#D9786A', bold = true })
set(0, 'Question', { fg = '#6FA0C0' })
set(0, 'Title', { fg = '#D6B25C', bold = true })
set(0, 'Directory', { fg = '#D6B25C', bold = true })
set(0, 'DiagnosticError', { fg = '#D9786A' })
set(0, 'DiagnosticWarn', { fg = '#DD9A5A' })
set(0, 'DiagnosticInfo', { fg = '#6FA0C0' })
set(0, 'DiagnosticHint', { fg = '#56A98C' })
set(0, 'DiagnosticOk', { fg = '#7CB377' })
set(0, 'DiagnosticUnderlineError', { sp = '#D9786A', undercurl = true })
set(0, 'DiagnosticUnderlineWarn', { sp = '#DD9A5A', undercurl = true })
set(0, 'DiagnosticUnderlineInfo', { sp = '#6FA0C0', undercurl = true })
set(0, 'DiagnosticUnderlineHint', { sp = '#56A98C', undercurl = true })
set(0, 'DiagnosticUnderlineOk', { sp = '#7CB377', undercurl = true })
set(0, 'DiagnosticVirtualTextError', { fg = '#D9786A', italic = true })
set(0, 'DiagnosticVirtualTextWarn', { fg = '#DD9A5A', italic = true })
set(0, 'DiagnosticVirtualTextInfo', { fg = '#6FA0C0', italic = true })
set(0, 'DiagnosticVirtualTextHint', { fg = '#56A98C', italic = true })
set(0, 'DiagnosticVirtualTextOk', { fg = '#7CB377', italic = true })
set(0, 'Comment', { fg = '#5E7A5E', italic = true })
set(0, 'Constant', { fg = '#9A8ED0', bold = true })
set(0, 'String', { fg = '#7CB377' })
set(0, 'Character', { fg = '#7CB377' })
set(0, 'Number', { fg = '#DD9A5A' })
set(0, 'Boolean', { fg = '#9A8ED0', bold = true })
set(0, 'Float', { fg = '#DD9A5A' })
set(0, 'Identifier', { fg = '#C8D8BE' })
set(0, 'Function', { fg = '#56A98C' })
set(0, 'Statement', { fg = '#D6B25C', bold = true })
set(0, 'Conditional', { link = 'Statement' })
set(0, 'Repeat', { link = 'Statement' })
set(0, 'Label', { link = 'Statement' })
set(0, 'Operator', { fg = '#6E8C70' })
set(0, 'Keyword', { link = 'Statement' })
set(0, 'Exception', { fg = '#D9786A', bold = true })
set(0, 'PreProc', { fg = '#D6B25C' })
set(0, 'Include', { link = 'PreProc' })
set(0, 'Define', { link = 'PreProc' })
set(0, 'Macro', { link = 'PreProc' })
set(0, 'PreCondit', { link = 'PreProc' })
set(0, 'Type', { fg = '#DD9A5A', italic = true })
set(0, 'StorageClass', { fg = '#DD9A5A' })
set(0, 'Structure', { fg = '#DD9A5A' })
set(0, 'Typedef', { link = 'Type' })
set(0, 'Special', { fg = '#9A8ED0' })
set(0, 'SpecialChar', { fg = '#DD9A5A' })
set(0, 'Tag', { fg = '#D6B25C' })
set(0, 'Delimiter', { fg = '#97AE8C' })
set(0, 'SpecialComment', { fg = '#6E8C6E', italic = true })
set(0, 'Debug', { fg = '#DD9A5A' })
set(0, 'Underlined', { fg = '#6FA0C0', underline = true })
set(0, 'Error', { fg = '#D9786A', bold = true })
set(0, 'Todo', { fg = '#DD9A5A', bg = '#101A12', bold = true })
set(0, '@comment', { link = 'Comment' })
set(0, '@string', { link = 'String' })
set(0, '@string.escape', { fg = '#DD9A5A' })
set(0, '@string.regex', { fg = '#DD9A5A' })
set(0, '@number', { link = 'Number' })
set(0, '@boolean', { link = 'Boolean' })
set(0, '@float', { link = 'Float' })
set(0, '@keyword', { link = 'Keyword' })
set(0, '@keyword.return', { fg = '#D6B25C', bold = true, italic = true })
set(0, '@keyword.function', { link = 'Keyword' })
set(0, '@keyword.operator', { link = 'Operator' })
set(0, '@conditional', { link = 'Conditional' })
set(0, '@repeat', { link = 'Repeat' })
set(0, '@operator', { link = 'Operator' })
set(0, '@function', { link = 'Function' })
set(0, '@function.call', { fg = '#56A98C' })
set(0, '@function.builtin', { fg = '#7CB377' })
set(0, '@function.macro', { fg = '#D6B25C' })
set(0, '@method', { link = 'Function' })
set(0, '@method.call', { fg = '#56A98C' })
set(0, '@constructor', { fg = '#DD9A5A' })
set(0, '@parameter', { fg = '#D8E6CE', italic = true })
set(0, '@variable', { link = 'Identifier' })
set(0, '@variable.builtin', { fg = '#9A8ED0', italic = true })
set(0, '@type', { link = 'Type' })
set(0, '@type.builtin', { fg = '#DD9A5A', italic = true })
set(0, '@type.qualifier', { fg = '#DD9A5A' })
set(0, '@constant', { link = 'Constant' })
set(0, '@constant.builtin', { fg = '#9A8ED0', bold = true })
set(0, '@constant.macro', { link = 'Macro' })
set(0, '@namespace', { fg = '#DD9A5A' })
set(0, '@module', { fg = '#DD9A5A' })
set(0, '@attribute', { fg = '#D6B25C' })
set(0, '@property', { fg = '#7CB377' })
set(0, '@field', { fg = '#7CB377' })
set(0, '@tag', { fg = '#D6B25C' })
set(0, '@tag.attribute', { fg = '#D6B25C' })
set(0, '@tag.delimiter', { link = 'Delimiter' })
set(0, '@punctuation', { link = 'Delimiter' })
set(0, '@punctuation.bracket', { link = 'Delimiter' })
set(0, '@punctuation.delimiter', { link = 'Delimiter' })
set(0, '@punctuation.special', { fg = '#9A8ED0' })
set(0, '@text', { fg = '#D8E6CE' })
set(0, '@text.strong', { bold = true })
set(0, '@text.emphasis', { italic = true })
set(0, '@text.underline', { underline = true })
set(0, '@text.title', { fg = '#D6B25C', bold = true })
set(0, '@text.literal', { fg = '#DD9A5A' })
set(0, '@text.uri', { fg = '#6FA0C0', underline = true })
set(0, '@text.todo', { link = 'Todo' })
set(0, '@text.note', { fg = '#6FA0C0', bold = true })
set(0, '@text.warning', { fg = '#DD9A5A', bold = true })
set(0, '@text.danger', { fg = '#D9786A', bold = true })
set(0, '@text.diff.add', { fg = '#7CB377' })
set(0, '@text.diff.delete', { fg = '#D9786A' })
set(0, '@lsp.type.class', { link = '@type' })
set(0, '@lsp.type.function', { link = '@function' })
set(0, '@lsp.type.method', { link = '@method' })
set(0, '@lsp.type.variable', { link = '@variable' })
set(0, '@lsp.type.parameter', { link = '@parameter' })
set(0, '@lsp.type.property', { link = '@property' })
set(0, '@lsp.type.enum', { link = '@type' })
set(0, '@lsp.type.enumMember', { link = '@constant' })
set(0, '@lsp.type.interface', { link = '@type' })
set(0, '@lsp.type.struct', { link = '@type' })
set(0, '@lsp.type.namespace', { link = '@namespace' })
set(0, '@lsp.type.macro', { link = 'Macro' })
set(0, '@lsp.type.type', { link = '@type' })
set(0, '@lsp.type.typeParameter', { link = '@type' })
set(0, 'DiffAdd', { fg = '#7CB377', bg = '#101A12' })
set(0, 'DiffChange', { fg = '#D6B25C', bg = '#101A12' })
set(0, 'DiffDelete', { fg = '#D9786A', bg = '#101A12' })
set(0, 'DiffText', { fg = '#DD9A5A', bg = '#101A12', bold = true })
set(0, 'diffAdded', { fg = '#7CB377' })
set(0, 'diffRemoved', { fg = '#D9786A' })
set(0, 'diffChanged', { fg = '#D6B25C' })
set(0, 'GitSignsAdd', { fg = '#7CB377' })
set(0, 'GitSignsChange', { fg = '#D6B25C' })
set(0, 'GitSignsDelete', { fg = '#D9786A' })
set(0, 'TelescopeBorder', { fg = '#2A3A2C', bg = '#0C140E' })
set(0, 'TelescopeNormal', { link = 'NormalFloat' })
set(0, 'TelescopePromptBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeResultsBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopePreviewBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeSelection', { fg = '#D6B25C', bg = '#202E22' })
set(0, 'TelescopeMatching', { fg = '#D6B25C', bold = true })
set(0, 'TelescopePromptPrefix', { fg = '#D6B25C' })
set(0, 'NvimTreeNormal', { link = 'Normal' })
set(0, 'NvimTreeFolderName', { fg = '#D6B25C' })
set(0, 'NvimTreeFolderIcon', { fg = '#D6B25C' })
set(0, 'NvimTreeOpenedFolderName', { fg = '#D6B25C', bold = true })
set(0, 'NvimTreeEmptyFolderName', { fg = '#506A52' })
set(0, 'NvimTreeRootFolder', { fg = '#9A8ED0', bold = true })
set(0, 'NvimTreeGitDirty', { fg = '#D6B25C' })
set(0, 'NvimTreeGitNew', { fg = '#7CB377' })
set(0, 'NvimTreeGitDeleted', { fg = '#D9786A' })
set(0, 'NvimTreeIndentMarker', { fg = '#2A3A2C' })
set(0, 'markdownH1', { fg = '#D6B25C', bold = true })
set(0, 'markdownH2', { fg = '#6FA0C0', bold = true })
set(0, 'markdownH3', { fg = '#7CB377', bold = true })
set(0, 'markdownCode', { fg = '#DD9A5A' })
set(0, 'markdownLink', { link = 'Underlined' })
