-- lumina-tide-dark -- Lumina (tide, dark)
-- Generated from spec/lumina.json + spec/nvim_highlights.json.

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = 'dark'
vim.g.colors_name = 'lumina-tide-dark'

local set = vim.api.nvim_set_hl

set(0, 'Normal', { fg = '#CFE4E2', bg = '#0F1E20' })
set(0, 'NormalFloat', { fg = '#CFE4E2', bg = '#0B1719' })
set(0, 'FloatBorder', { fg = '#284042', bg = '#0B1719' })
set(0, 'FloatTitle', { fg = '#58D2A4', bg = '#0B1719', bold = true })
set(0, 'CursorLine', { bg = '#16282A' })
set(0, 'CursorColumn', { bg = '#16282A' })
set(0, 'CursorLineNr', { fg = '#58D2A4', bold = true })
set(0, 'LineNr', { fg = '#355154' })
set(0, 'SignColumn', { bg = '#0F1E20' })
set(0, 'VertSplit', { fg = '#284042', bg = '#0F1E20' })
set(0, 'WinSeparator', { fg = '#284042', bg = '#0F1E20' })
set(0, 'ColorColumn', { bg = '#16282A' })
set(0, 'Folded', { fg = '#4E6E70', bg = '#16282A' })
set(0, 'FoldColumn', { fg = '#355154', bg = '#0F1E20' })
set(0, 'EndOfBuffer', { fg = '#0F1E20' })
set(0, 'NonText', { fg = '#284042' })
set(0, 'SpecialKey', { fg = '#355154' })
set(0, 'Whitespace', { fg = '#284042' })
set(0, 'MatchParen', { fg = '#58D2A4', bg = '#1E3234', bold = true })
set(0, 'Cursor', { fg = '#0F1E20', bg = '#58D2A4' })
set(0, 'iCursor', { link = 'Cursor' })
set(0, 'TermCursor', { link = 'Cursor' })
set(0, 'Visual', { bg = '#284042' })
set(0, 'VisualNOS', { link = 'Visual' })
set(0, 'Search', { fg = '#0F1E20', bg = '#DCCB86' })
set(0, 'IncSearch', { fg = '#0F1E20', bg = '#58D2A4', bold = true })
set(0, 'CurSearch', { fg = '#0F1E20', bg = '#EAA478', bold = true })
set(0, 'Substitute', { link = 'IncSearch' })
set(0, 'StatusLine', { fg = '#8FB0AE', bg = '#0B1719' })
set(0, 'StatusLineNC', { fg = '#4E6E70', bg = '#0B1719' })
set(0, 'TabLine', { fg = '#4E6E70', bg = '#0B1719' })
set(0, 'TabLineSel', { fg = '#58D2A4', bg = '#0F1E20', bold = true })
set(0, 'TabLineFill', { bg = '#0B1719' })
set(0, 'WinBar', { fg = '#8FB0AE', bg = '#0F1E20' })
set(0, 'WinBarNC', { fg = '#4E6E70', bg = '#0F1E20' })
set(0, 'Pmenu', { fg = '#CFE4E2', bg = '#0B1719' })
set(0, 'PmenuSel', { fg = '#58D2A4', bg = '#1E3234', bold = true })
set(0, 'PmenuSbar', { bg = '#1E3234' })
set(0, 'PmenuThumb', { bg = '#355154' })
set(0, 'ModeMsg', { fg = '#58D2A4', bold = true })
set(0, 'MoreMsg', { fg = '#58D2A4' })
set(0, 'MsgArea', { fg = '#CFE4E2' })
set(0, 'WarningMsg', { fg = '#EAA478' })
set(0, 'ErrorMsg', { fg = '#EE7888', bold = true })
set(0, 'Question', { fg = '#66B6E2' })
set(0, 'Title', { fg = '#58D2A4', bold = true })
set(0, 'Directory', { fg = '#58D2A4', bold = true })
set(0, 'DiagnosticError', { fg = '#EE7888' })
set(0, 'DiagnosticWarn', { fg = '#EAA478' })
set(0, 'DiagnosticInfo', { fg = '#66B6E2' })
set(0, 'DiagnosticHint', { fg = '#4FCEC6' })
set(0, 'DiagnosticOk', { fg = '#58D2A4' })
set(0, 'DiagnosticUnderlineError', { sp = '#EE7888', undercurl = true })
set(0, 'DiagnosticUnderlineWarn', { sp = '#EAA478', undercurl = true })
set(0, 'DiagnosticUnderlineInfo', { sp = '#66B6E2', undercurl = true })
set(0, 'DiagnosticUnderlineHint', { sp = '#4FCEC6', undercurl = true })
set(0, 'DiagnosticUnderlineOk', { sp = '#58D2A4', undercurl = true })
set(0, 'DiagnosticVirtualTextError', { fg = '#EE7888', italic = true })
set(0, 'DiagnosticVirtualTextWarn', { fg = '#EAA478', italic = true })
set(0, 'DiagnosticVirtualTextInfo', { fg = '#66B6E2', italic = true })
set(0, 'DiagnosticVirtualTextHint', { fg = '#4FCEC6', italic = true })
set(0, 'DiagnosticVirtualTextOk', { fg = '#58D2A4', italic = true })
set(0, 'Comment', { fg = '#7A9896', italic = true })
set(0, 'Constant', { fg = '#A894E4', bold = true })
set(0, 'String', { fg = '#DCCB86' })
set(0, 'Character', { fg = '#DCCB86' })
set(0, 'Number', { fg = '#EAA478' })
set(0, 'Boolean', { fg = '#A894E4', bold = true })
set(0, 'Float', { fg = '#EAA478' })
set(0, 'Identifier', { fg = '#C7DEDC' })
set(0, 'Function', { fg = '#58D2A4' })
set(0, 'Statement', { fg = '#A894E4', bold = true })
set(0, 'Conditional', { link = 'Statement' })
set(0, 'Repeat', { link = 'Statement' })
set(0, 'Label', { link = 'Statement' })
set(0, 'Operator', { fg = '#4FCEC6' })
set(0, 'Keyword', { link = 'Statement' })
set(0, 'Exception', { fg = '#EE7888', bold = true })
set(0, 'PreProc', { fg = '#A894E4' })
set(0, 'Include', { link = 'PreProc' })
set(0, 'Define', { link = 'PreProc' })
set(0, 'Macro', { link = 'PreProc' })
set(0, 'PreCondit', { link = 'PreProc' })
set(0, 'Type', { fg = '#6CD2DE', italic = true })
set(0, 'StorageClass', { fg = '#6CD2DE' })
set(0, 'Structure', { fg = '#6CD2DE' })
set(0, 'Typedef', { link = 'Type' })
set(0, 'Special', { fg = '#A894E4' })
set(0, 'SpecialChar', { fg = '#DC86C2' })
set(0, 'Tag', { fg = '#A894E4' })
set(0, 'Delimiter', { fg = '#8FB0AE' })
set(0, 'SpecialComment', { fg = '#88A4A2', italic = true })
set(0, 'Debug', { fg = '#EAA478' })
set(0, 'Underlined', { fg = '#66B6E2', underline = true })
set(0, 'Error', { fg = '#EE7888', bold = true })
set(0, 'Todo', { fg = '#EAA478', bg = '#0F1E20', bold = true })
set(0, '@comment', { link = 'Comment' })
set(0, '@string', { link = 'String' })
set(0, '@string.escape', { fg = '#DC86C2' })
set(0, '@string.regex', { fg = '#EAA478' })
set(0, '@number', { link = 'Number' })
set(0, '@boolean', { link = 'Boolean' })
set(0, '@float', { link = 'Float' })
set(0, '@keyword', { link = 'Keyword' })
set(0, '@keyword.return', { fg = '#A894E4', bold = true, italic = true })
set(0, '@keyword.function', { link = 'Keyword' })
set(0, '@keyword.operator', { link = 'Operator' })
set(0, '@conditional', { link = 'Conditional' })
set(0, '@repeat', { link = 'Repeat' })
set(0, '@operator', { link = 'Operator' })
set(0, '@function', { link = 'Function' })
set(0, '@function.call', { fg = '#58D2A4' })
set(0, '@function.builtin', { fg = '#DC86C2' })
set(0, '@function.macro', { fg = '#A894E4' })
set(0, '@method', { link = 'Function' })
set(0, '@method.call', { fg = '#58D2A4' })
set(0, '@constructor', { fg = '#6CD2DE' })
set(0, '@parameter', { fg = '#CFE4E2', italic = true })
set(0, '@variable', { link = 'Identifier' })
set(0, '@variable.builtin', { fg = '#A894E4', italic = true })
set(0, '@type', { link = 'Type' })
set(0, '@type.builtin', { fg = '#6CD2DE', italic = true })
set(0, '@type.qualifier', { fg = '#6CD2DE' })
set(0, '@constant', { link = 'Constant' })
set(0, '@constant.builtin', { fg = '#A894E4', bold = true })
set(0, '@constant.macro', { link = 'Macro' })
set(0, '@namespace', { fg = '#6CD2DE' })
set(0, '@module', { fg = '#6CD2DE' })
set(0, '@attribute', { fg = '#DCCB86' })
set(0, '@property', { fg = '#6CD2DE' })
set(0, '@field', { fg = '#6CD2DE' })
set(0, '@tag', { fg = '#A894E4' })
set(0, '@tag.attribute', { fg = '#DCCB86' })
set(0, '@tag.delimiter', { link = 'Delimiter' })
set(0, '@punctuation', { link = 'Delimiter' })
set(0, '@punctuation.bracket', { link = 'Delimiter' })
set(0, '@punctuation.delimiter', { link = 'Delimiter' })
set(0, '@punctuation.special', { fg = '#A894E4' })
set(0, '@text', { fg = '#CFE4E2' })
set(0, '@text.strong', { bold = true })
set(0, '@text.emphasis', { italic = true })
set(0, '@text.underline', { underline = true })
set(0, '@text.title', { fg = '#58D2A4', bold = true })
set(0, '@text.literal', { fg = '#EAA478' })
set(0, '@text.uri', { fg = '#66B6E2', underline = true })
set(0, '@text.todo', { link = 'Todo' })
set(0, '@text.note', { fg = '#66B6E2', bold = true })
set(0, '@text.warning', { fg = '#EAA478', bold = true })
set(0, '@text.danger', { fg = '#EE7888', bold = true })
set(0, '@text.diff.add', { fg = '#58D2A4' })
set(0, '@text.diff.delete', { fg = '#EE7888' })
set(0, '@lsp.type.class', { link = '@type' })
set(0, '@lsp.type.function', { link = '@function' })
set(0, '@lsp.type.method', { link = '@method' })
set(0, '@lsp.type.variable', { link = '@variable' })
set(0, '@lsp.type.parameter', { link = '@parameter' })
set(0, '@lsp.type.property', { link = '@property' })
set(0, '@lsp.type.enum', { link = '@type' })
set(0, '@lsp.type.enumMember', { link = '@constant' })
set(0, '@lsp.type.interface', { link = '@type' })
set(0, '@lsp.type.struct', { link = '@type' })
set(0, '@lsp.type.namespace', { link = '@namespace' })
set(0, '@lsp.type.macro', { link = 'Macro' })
set(0, '@lsp.type.type', { link = '@type' })
set(0, '@lsp.type.typeParameter', { link = '@type' })
set(0, 'DiffAdd', { fg = '#58D2A4', bg = '#0F1E20' })
set(0, 'DiffChange', { fg = '#DCCB86', bg = '#0F1E20' })
set(0, 'DiffDelete', { fg = '#EE7888', bg = '#0F1E20' })
set(0, 'DiffText', { fg = '#EAA478', bg = '#0F1E20', bold = true })
set(0, 'diffAdded', { fg = '#58D2A4' })
set(0, 'diffRemoved', { fg = '#EE7888' })
set(0, 'diffChanged', { fg = '#DCCB86' })
set(0, 'GitSignsAdd', { fg = '#58D2A4' })
set(0, 'GitSignsChange', { fg = '#DCCB86' })
set(0, 'GitSignsDelete', { fg = '#EE7888' })
set(0, 'TelescopeBorder', { fg = '#284042', bg = '#0B1719' })
set(0, 'TelescopeNormal', { link = 'NormalFloat' })
set(0, 'TelescopePromptBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeResultsBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopePreviewBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeSelection', { fg = '#58D2A4', bg = '#1E3234' })
set(0, 'TelescopeMatching', { fg = '#58D2A4', bold = true })
set(0, 'TelescopePromptPrefix', { fg = '#58D2A4' })
set(0, 'NvimTreeNormal', { link = 'Normal' })
set(0, 'NvimTreeFolderName', { fg = '#58D2A4' })
set(0, 'NvimTreeFolderIcon', { fg = '#58D2A4' })
set(0, 'NvimTreeOpenedFolderName', { fg = '#58D2A4', bold = true })
set(0, 'NvimTreeEmptyFolderName', { fg = '#4E6E70' })
set(0, 'NvimTreeRootFolder', { fg = '#A894E4', bold = true })
set(0, 'NvimTreeGitDirty', { fg = '#DCCB86' })
set(0, 'NvimTreeGitNew', { fg = '#58D2A4' })
set(0, 'NvimTreeGitDeleted', { fg = '#EE7888' })
set(0, 'NvimTreeIndentMarker', { fg = '#284042' })
set(0, 'markdownH1', { fg = '#58D2A4', bold = true })
set(0, 'markdownH2', { fg = '#66B6E2', bold = true })
set(0, 'markdownH3', { fg = '#58D2A4', bold = true })
set(0, 'markdownCode', { fg = '#EAA478' })
set(0, 'markdownLink', { link = 'Underlined' })
