-- lumina-amethyst-dark -- Lumina (amethyst, dark)
-- Generated from spec/lumina.json + spec/nvim_highlights.json.

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = 'dark'
vim.g.colors_name = 'lumina-amethyst-dark'

local set = vim.api.nvim_set_hl

set(0, 'Normal', { fg = '#DBD4E4', bg = '#1D1229' })
set(0, 'NormalFloat', { fg = '#DBD4E4', bg = '#170D23' })
set(0, 'FloatBorder', { fg = '#372947', bg = '#170D23' })
set(0, 'FloatTitle', { fg = '#E4CE63', bg = '#170D23', bold = true })
set(0, 'CursorLine', { bg = '#231531' })
set(0, 'CursorColumn', { bg = '#231531' })
set(0, 'CursorLineNr', { fg = '#E4CE63', bold = true })
set(0, 'LineNr', { fg = '#4F4060' })
set(0, 'SignColumn', { bg = '#1D1229' })
set(0, 'VertSplit', { fg = '#372947', bg = '#1D1229' })
set(0, 'WinSeparator', { fg = '#372947', bg = '#1D1229' })
set(0, 'ColorColumn', { bg = '#231531' })
set(0, 'Folded', { fg = '#706183', bg = '#231531' })
set(0, 'FoldColumn', { fg = '#4F4060', bg = '#1D1229' })
set(0, 'EndOfBuffer', { fg = '#1D1229' })
set(0, 'NonText', { fg = '#372947' })
set(0, 'SpecialKey', { fg = '#4F4060' })
set(0, 'Whitespace', { fg = '#372947' })
set(0, 'MatchParen', { fg = '#56D298', bg = '#2D1F3C', bold = true })
set(0, 'Cursor', { fg = '#1D1229', bg = '#E4CE63' })
set(0, 'iCursor', { link = 'Cursor' })
set(0, 'TermCursor', { link = 'Cursor' })
set(0, 'Visual', { bg = '#463B3C' })
set(0, 'VisualNOS', { link = 'Visual' })
set(0, 'Search', { fg = '#1D1229', bg = '#E4CE63' })
set(0, 'IncSearch', { fg = '#1D1229', bg = '#E4CE63', bold = true })
set(0, 'CurSearch', { fg = '#1D1229', bg = '#F0995B', bold = true })
set(0, 'Substitute', { link = 'IncSearch' })
set(0, 'StatusLine', { fg = '#B4A7C5', bg = '#170D23' })
set(0, 'StatusLineNC', { fg = '#706183', bg = '#170D23' })
set(0, 'TabLine', { fg = '#706183', bg = '#170D23' })
set(0, 'TabLineSel', { fg = '#E4CE63', bg = '#1D1229', bold = true })
set(0, 'TabLineFill', { bg = '#170D23' })
set(0, 'WinBar', { fg = '#B4A7C5', bg = '#1D1229' })
set(0, 'WinBarNC', { fg = '#706183', bg = '#1D1229' })
set(0, 'Pmenu', { fg = '#DBD4E4', bg = '#170D23' })
set(0, 'PmenuSel', { fg = '#E4CE63', bg = '#2D1F3C', bold = true })
set(0, 'PmenuSbar', { bg = '#2D1F3C' })
set(0, 'PmenuThumb', { bg = '#4F4060' })
set(0, 'ModeMsg', { fg = '#E4CE63', bold = true })
set(0, 'MoreMsg', { fg = '#56D298' })
set(0, 'MsgArea', { fg = '#DBD4E4' })
set(0, 'WarningMsg', { fg = '#F0995B' })
set(0, 'ErrorMsg', { fg = '#F17074', bold = true })
set(0, 'Question', { fg = '#7FA5FA' })
set(0, 'Title', { fg = '#E4CE63', bold = true })
set(0, 'Directory', { fg = '#E4CE63', bold = true })
set(0, 'DiagnosticError', { fg = '#F17074' })
set(0, 'DiagnosticWarn', { fg = '#F0995B' })
set(0, 'DiagnosticInfo', { fg = '#7FA5FA' })
set(0, 'DiagnosticHint', { fg = '#51CBBD' })
set(0, 'DiagnosticOk', { fg = '#56D298' })
set(0, 'DiagnosticUnderlineError', { sp = '#F17074', undercurl = true })
set(0, 'DiagnosticUnderlineWarn', { sp = '#F0995B', undercurl = true })
set(0, 'DiagnosticUnderlineInfo', { sp = '#7FA5FA', undercurl = true })
set(0, 'DiagnosticUnderlineHint', { sp = '#51CBBD', undercurl = true })
set(0, 'DiagnosticUnderlineOk', { sp = '#56D298', undercurl = true })
set(0, 'DiagnosticVirtualTextError', { fg = '#F17074', italic = true })
set(0, 'DiagnosticVirtualTextWarn', { fg = '#F0995B', italic = true })
set(0, 'DiagnosticVirtualTextInfo', { fg = '#7FA5FA', italic = true })
set(0, 'DiagnosticVirtualTextHint', { fg = '#51CBBD', italic = true })
set(0, 'DiagnosticVirtualTextOk', { fg = '#56D298', italic = true })
set(0, 'Comment', { fg = '#877D9D', italic = true })
set(0, 'Constant', { fg = '#B28FEF', bold = true })
set(0, 'String', { fg = '#56D298' })
set(0, 'Character', { fg = '#56D298' })
set(0, 'Number', { fg = '#F0995B' })
set(0, 'Boolean', { fg = '#B28FEF', bold = true })
set(0, 'Float', { fg = '#F0995B' })
set(0, 'Identifier', { fg = '#DBD4E4' })
set(0, 'Function', { fg = '#E4CE63' })
set(0, 'Statement', { fg = '#F47DB9', bold = true })
set(0, 'Conditional', { link = 'Statement' })
set(0, 'Repeat', { link = 'Statement' })
set(0, 'Label', { link = 'Statement' })
set(0, 'Operator', { fg = '#9181A4' })
set(0, 'Keyword', { link = 'Statement' })
set(0, 'Exception', { fg = '#F17074', bold = true })
set(0, 'PreProc', { fg = '#F47DB9' })
set(0, 'Include', { link = 'PreProc' })
set(0, 'Define', { link = 'PreProc' })
set(0, 'Macro', { link = 'PreProc' })
set(0, 'PreCondit', { link = 'PreProc' })
set(0, 'Type', { fg = '#4DC3DD', italic = true })
set(0, 'StorageClass', { fg = '#4DC3DD' })
set(0, 'Structure', { fg = '#4DC3DD' })
set(0, 'Typedef', { link = 'Type' })
set(0, 'Special', { fg = '#B28FEF' })
set(0, 'SpecialChar', { fg = '#E4CE63' })
set(0, 'Tag', { fg = '#F47DB9' })
set(0, 'Delimiter', { fg = '#B4A7C5' })
set(0, 'SpecialComment', { fg = '#9A8EB3', italic = true })
set(0, 'Debug', { fg = '#F0995B' })
set(0, 'Underlined', { fg = '#7FA5FA', underline = true })
set(0, 'Error', { fg = '#F17074', bold = true })
set(0, 'Todo', { fg = '#F0995B', bg = '#1D1229', bold = true })
set(0, '@comment', { link = 'Comment' })
set(0, '@string', { link = 'String' })
set(0, '@string.escape', { fg = '#E4CE63' })
set(0, '@string.regex', { fg = '#F0995B' })
set(0, '@number', { link = 'Number' })
set(0, '@boolean', { link = 'Boolean' })
set(0, '@float', { link = 'Float' })
set(0, '@keyword', { link = 'Keyword' })
set(0, '@keyword.return', { fg = '#F47DB9', bold = true, italic = true })
set(0, '@keyword.function', { link = 'Keyword' })
set(0, '@keyword.operator', { link = 'Operator' })
set(0, '@conditional', { link = 'Conditional' })
set(0, '@repeat', { link = 'Repeat' })
set(0, '@operator', { link = 'Operator' })
set(0, '@function', { link = 'Function' })
set(0, '@function.call', { fg = '#4DC3DD' })
set(0, '@function.builtin', { fg = '#7FA5FA' })
set(0, '@function.macro', { fg = '#F47DB9' })
set(0, '@method', { link = 'Function' })
set(0, '@method.call', { fg = '#4DC3DD' })
set(0, '@constructor', { fg = '#4DC3DD' })
set(0, '@parameter', { fg = '#DBD4E4', italic = true })
set(0, '@variable', { link = 'Identifier' })
set(0, '@variable.builtin', { fg = '#B28FEF', italic = true })
set(0, '@type', { link = 'Type' })
set(0, '@type.builtin', { fg = '#4DC3DD', italic = true })
set(0, '@type.qualifier', { fg = '#4DC3DD' })
set(0, '@constant', { link = 'Constant' })
set(0, '@constant.builtin', { fg = '#B28FEF', bold = true })
set(0, '@constant.macro', { link = 'Macro' })
set(0, '@namespace', { fg = '#4DC3DD' })
set(0, '@module', { fg = '#4DC3DD' })
set(0, '@attribute', { fg = '#E4CE63' })
set(0, '@property', { fg = '#51CBBD' })
set(0, '@field', { fg = '#51CBBD' })
set(0, '@tag', { fg = '#F47DB9' })
set(0, '@tag.attribute', { fg = '#E4CE63' })
set(0, '@tag.delimiter', { link = 'Delimiter' })
set(0, '@punctuation', { link = 'Delimiter' })
set(0, '@punctuation.bracket', { link = 'Delimiter' })
set(0, '@punctuation.delimiter', { link = 'Delimiter' })
set(0, '@punctuation.special', { fg = '#B28FEF' })
set(0, '@text', { fg = '#DBD4E4' })
set(0, '@text.strong', { bold = true })
set(0, '@text.emphasis', { italic = true })
set(0, '@text.underline', { underline = true })
set(0, '@text.title', { fg = '#E4CE63', bold = true })
set(0, '@text.literal', { fg = '#F0995B' })
set(0, '@text.uri', { fg = '#7FA5FA', underline = true })
set(0, '@text.todo', { link = 'Todo' })
set(0, '@text.note', { fg = '#7FA5FA', bold = true })
set(0, '@text.warning', { fg = '#F0995B', bold = true })
set(0, '@text.danger', { fg = '#F17074', bold = true })
set(0, '@text.diff.add', { fg = '#56D298' })
set(0, '@text.diff.delete', { fg = '#F17074' })
set(0, '@lsp.type.class', { link = '@type' })
set(0, '@lsp.type.function', { link = '@function' })
set(0, '@lsp.type.method', { link = '@method' })
set(0, '@lsp.type.variable', { link = '@variable' })
set(0, '@lsp.type.parameter', { link = '@parameter' })
set(0, '@lsp.type.property', { link = '@property' })
set(0, '@lsp.type.enum', { link = '@type' })
set(0, '@lsp.type.enumMember', { link = '@constant' })
set(0, '@lsp.type.interface', { link = '@type' })
set(0, '@lsp.type.struct', { link = '@type' })
set(0, '@lsp.type.namespace', { link = '@namespace' })
set(0, '@lsp.type.macro', { link = 'Macro' })
set(0, '@lsp.type.type', { link = '@type' })
set(0, '@lsp.type.typeParameter', { link = '@type' })
set(0, 'DiffAdd', { fg = '#56D298', bg = '#1D1229' })
set(0, 'DiffChange', { fg = '#E4CE63', bg = '#1D1229' })
set(0, 'DiffDelete', { fg = '#F17074', bg = '#1D1229' })
set(0, 'DiffText', { fg = '#F0995B', bg = '#1D1229', bold = true })
set(0, 'diffAdded', { fg = '#56D298' })
set(0, 'diffRemoved', { fg = '#F17074' })
set(0, 'diffChanged', { fg = '#E4CE63' })
set(0, 'GitSignsAdd', { fg = '#56D298' })
set(0, 'GitSignsChange', { fg = '#E4CE63' })
set(0, 'GitSignsDelete', { fg = '#F17074' })
set(0, 'TelescopeBorder', { fg = '#372947', bg = '#170D23' })
set(0, 'TelescopeNormal', { link = 'NormalFloat' })
set(0, 'TelescopePromptBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeResultsBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopePreviewBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeSelection', { fg = '#E4CE63', bg = '#2D1F3C' })
set(0, 'TelescopeMatching', { fg = '#E4CE63', bold = true })
set(0, 'TelescopePromptPrefix', { fg = '#E4CE63' })
set(0, 'NvimTreeNormal', { link = 'Normal' })
set(0, 'NvimTreeFolderName', { fg = '#E4CE63' })
set(0, 'NvimTreeFolderIcon', { fg = '#E4CE63' })
set(0, 'NvimTreeOpenedFolderName', { fg = '#E4CE63', bold = true })
set(0, 'NvimTreeEmptyFolderName', { fg = '#706183' })
set(0, 'NvimTreeRootFolder', { fg = '#B28FEF', bold = true })
set(0, 'NvimTreeGitDirty', { fg = '#E4CE63' })
set(0, 'NvimTreeGitNew', { fg = '#56D298' })
set(0, 'NvimTreeGitDeleted', { fg = '#F17074' })
set(0, 'NvimTreeIndentMarker', { fg = '#372947' })
set(0, 'markdownH1', { fg = '#E4CE63', bold = true })
set(0, 'markdownH2', { fg = '#7FA5FA', bold = true })
set(0, 'markdownH3', { fg = '#56D298', bold = true })
set(0, 'markdownCode', { fg = '#F0995B' })
set(0, 'markdownLink', { link = 'Underlined' })
set(0, '@lsp.type.decorator', { link = '@function' })
set(0, '@lsp.mod.deprecated', {  })
set(0, '@lsp.mod.readonly', { italic = true })
set(0, '@lsp.mod.defaultLibrary', { link = '@function.builtin' })
set(0, 'CmpItemAbbr', { fg = '#DBD4E4' })
set(0, 'CmpItemAbbrDeprecated', { fg = '#706183' })
set(0, 'CmpItemAbbrMatch', { fg = '#E4CE63', bold = true })
set(0, 'CmpItemAbbrMatchFuzzy', { fg = '#E4CE63', bold = true })
set(0, 'CmpItemKind', { fg = '#B28FEF' })
set(0, 'CmpItemKindClass', { fg = '#E4CE63' })
set(0, 'CmpItemKindFunction', { fg = '#7FA5FA' })
set(0, 'CmpItemKindMethod', { fg = '#7FA5FA' })
set(0, 'CmpItemKindKeyword', { fg = '#B28FEF' })
set(0, 'CmpItemKindVariable', { fg = '#DBD4E4' })
set(0, 'CmpItemKindConstant', { fg = '#F0995B' })
set(0, 'CmpItemKindInterface', { fg = '#E4CE63' })
set(0, 'CmpItemKindModule', { fg = '#B28FEF' })
set(0, 'CmpItemKindProperty', { fg = '#51CBBD' })
set(0, 'CmpItemKindUnit', { fg = '#F0995B' })
set(0, 'CmpItemKindValue', { fg = '#F0995B' })
set(0, 'CmpItemKindEnum', { fg = '#E4CE63' })
set(0, 'CmpItemKindEnumMember', { fg = '#F0995B' })
set(0, 'CmpItemKindText', { fg = '#B4A7C5' })
set(0, 'CmpItemKindSnippet', { fg = '#4DC3DD' })
set(0, 'CmpItemKindFile', { fg = '#DBD4E4' })
set(0, 'CmpItemKindFolder', { fg = '#E4CE63' })
set(0, 'CmpItemKindEvent', { fg = '#F47DB9' })
set(0, 'CmpItemKindOperator', { fg = '#B4A7C5' })
set(0, 'CmpItemKindTypeParameter', { fg = '#E4CE63' })
set(0, 'CmpItemMenu', { fg = '#706183', italic = true })
set(0, 'NeoTreeNormal', { link = 'Normal' })
set(0, 'NeoTreeNormalNC', { link = 'Normal' })
set(0, 'NeoTreeDirectoryName', { fg = '#E4CE63' })
set(0, 'NeoTreeDirectoryIcon', { fg = '#E4CE63' })
set(0, 'NeoTreeRootName', { fg = '#B28FEF', bold = true })
set(0, 'NeoTreeFileName', { fg = '#DBD4E4' })
set(0, 'NeoTreeFileIcon', { fg = '#9181A4' })
set(0, 'NeoTreeIndentMarker', { fg = '#372947' })
set(0, 'NeoTreeExpander', { fg = '#706183' })
set(0, 'NeoTreeDimText', { fg = '#706183' })
set(0, 'NeoTreeGitAdded', { fg = '#56D298' })
set(0, 'NeoTreeGitConflict', { fg = '#F17074', bold = true })
set(0, 'NeoTreeGitDeleted', { fg = '#F17074' })
set(0, 'NeoTreeGitIgnored', { fg = '#706183' })
set(0, 'NeoTreeGitModified', { fg = '#E4CE63' })
set(0, 'NeoTreeGitRenamed', { fg = '#B28FEF' })
set(0, 'NeoTreeGitUntracked', { fg = '#F0995B', italic = true })
set(0, 'NeoTreeFloatBorder', { fg = '#372947', bg = '#170D23' })
set(0, 'NeoTreeTitleBar', { fg = '#E4CE63', bg = '#170D23', bold = true })
set(0, 'NoicePopup', { bg = '#170D23' })
set(0, 'NoiceCmdlinePopup', { bg = '#170D23' })
set(0, 'NoiceCmdline', { fg = '#DBD4E4' })
set(0, 'NoiceCmdlineIcon', { fg = '#E4CE63' })
set(0, 'NoiceCmdlineIconSearch', { fg = '#F0995B' })
set(0, 'NoiceCmdlinePopupBorder', { fg = '#372947' })
set(0, 'NoiceCmdlinePopupBorderSearch', { fg = '#F0995B' })
set(0, 'NoiceConfirm', { bg = '#170D23' })
set(0, 'NoiceConfirmBorder', { fg = '#E4CE63' })
set(0, 'NoiceMini', { link = 'Normal' })
set(0, 'NoiceLspProgressTitle', { fg = '#E4CE63', bold = true })
set(0, 'NoiceLspProgressClient', { fg = '#B28FEF' })
set(0, 'NoiceLspProgressSpinner', { fg = '#E4CE63' })
set(0, 'WhichKey', { fg = '#E4CE63', bold = true })
set(0, 'WhichKeyGroup', { fg = '#E4CE63', italic = true })
set(0, 'WhichKeyDesc', { fg = '#DBD4E4' })
set(0, 'WhichKeySeparator', { fg = '#706183' })
set(0, 'WhichKeyFloat', { bg = '#170D23' })
set(0, 'WhichKeyBorder', { fg = '#372947', bg = '#170D23' })
set(0, 'WhichKeyValue', { fg = '#B28FEF' })
set(0, 'TroubleNormal', { link = 'Normal' })
set(0, 'TroubleText', { fg = '#DBD4E4' })
set(0, 'TroubleCount', { fg = '#F0995B', bold = true })
set(0, 'TroubleIndent', { fg = '#372947' })
set(0, 'TroubleFile', { fg = '#E4CE63', bold = true })
set(0, 'TroubleLocation', { fg = '#706183' })
set(0, 'TroubleFoldIcon', { fg = '#706183' })
set(0, 'TodoBgFix', { fg = '#1D1229', bg = '#F17074', bold = true })
set(0, 'TodoBgHack', { fg = '#1D1229', bg = '#F0995B', bold = true })
set(0, 'TodoBgNote', { fg = '#1D1229', bg = '#7FA5FA', bold = true })
set(0, 'TodoBgTodo', { fg = '#1D1229', bg = '#E4CE63', bold = true })
set(0, 'TodoBgWarn', { fg = '#1D1229', bg = '#F0995B', bold = true })
set(0, 'TodoBgPerf', { fg = '#1D1229', bg = '#F47DB9', bold = true })
set(0, 'TodoFgFix', { fg = '#F17074', bold = true })
set(0, 'TodoFgHack', { fg = '#F0995B', bold = true })
set(0, 'TodoFgNote', { fg = '#7FA5FA', bold = true })
set(0, 'TodoFgTodo', { fg = '#E4CE63', bold = true })
set(0, 'TodoFgWarn', { fg = '#F0995B', bold = true })
set(0, 'TodoFgPerf', { fg = '#F47DB9', bold = true })
set(0, 'TodoSignFix', { fg = '#F17074' })
set(0, 'TodoSignHack', { fg = '#F0995B' })
set(0, 'TodoSignNote', { fg = '#7FA5FA' })
set(0, 'TodoSignTodo', { fg = '#E4CE63' })
set(0, 'TodoSignWarn', { fg = '#F0995B' })
set(0, 'TodoSignPerf', { fg = '#F47DB9' })
set(0, 'LualineFilenameNormal', { fg = '#E4CE63', bold = true })
set(0, 'LualineModifiedNormal', { fg = '#F0995B', bold = true })
set(0, 'LualineFiletypeNormal', { fg = '#DBD4E4' })
set(0, 'LualineLocationNormal', { fg = '#B4A7C5' })
set(0, 'BufferLineFill', { bg = '#170D23' })
set(0, 'BufferLineBackground', { fg = '#706183', bg = '#170D23' })
set(0, 'BufferLineBufferVisible', { fg = '#B4A7C5', bg = '#170D23' })
set(0, 'BufferLineBufferSelected', { fg = '#E4CE63', bg = '#1D1229', bold = true })
set(0, 'BufferLineSeparator', { fg = '#170D23', bg = '#170D23' })
set(0, 'BufferLineSeparatorVisible', { fg = '#170D23', bg = '#170D23' })
set(0, 'BufferLineSeparatorSelected', { fg = '#170D23', bg = '#1D1229' })
set(0, 'BufferLineCloseButton', { fg = '#706183', bg = '#170D23' })
set(0, 'BufferLineCloseButtonVisible', { fg = '#B4A7C5', bg = '#170D23' })
set(0, 'BufferLineCloseButtonSelected', { fg = '#F17074', bg = '#1D1229' })
set(0, 'BufferLineIndicatorSelected', { fg = '#E4CE63', bg = '#1D1229' })
set(0, 'BufferLineModified', { fg = '#F0995B', bg = '#170D23' })
set(0, 'BufferLineModifiedVisible', { fg = '#F0995B', bg = '#170D23' })
set(0, 'BufferLineModifiedSelected', { fg = '#F0995B', bg = '#1D1229' })
set(0, 'BufferLineTabSelected', { fg = '#E4CE63', bg = '#1D1229', bold = true })
set(0, 'BufferLineTab', { fg = '#706183', bg = '#170D23' })
set(0, 'BufferLineTabClose', { fg = '#F17074', bg = '#170D23' })
set(0, 'IblIndent', { fg = '#372947' })
set(0, 'IblScope', { fg = '#706183' })
set(0, 'IblWhitespace', { fg = '#372947' })
set(0, 'IndentBlanklineChar', { fg = '#372947' })
set(0, 'IndentBlanklineContextChar', { fg = '#706183' })
set(0, 'LazyButton', { fg = '#DBD4E4', bg = '#170D23' })
set(0, 'LazyButtonActive', { fg = '#E4CE63', bg = '#2D1F3C', bold = true })
set(0, 'LazyH1', { fg = '#E4CE63', bold = true })
set(0, 'LazyH2', { fg = '#B28FEF', bold = true })
set(0, 'LazyProgressDone', { fg = '#56D298' })
set(0, 'LazyProgressTodo', { fg = '#706183' })
set(0, 'LazyReasonCmd', { fg = '#F0995B' })
set(0, 'LazyReasonEvent', { fg = '#F47DB9' })
set(0, 'LazyReasonFt', { fg = '#4DC3DD' })
set(0, 'LazyReasonKeys', { fg = '#B28FEF' })
set(0, 'LazyReasonPlugin', { fg = '#E4CE63' })
set(0, 'LazyReasonRuntime', { fg = '#E4CE63' })
set(0, 'LazyReasonSource', { fg = '#56D298' })
set(0, 'LazyReasonStart', { fg = '#56D298' })
set(0, 'LazyCommit', { fg = '#B28FEF' })
set(0, 'LazyValue', { fg = '#F0995B' })
set(0, 'LazyDir', { fg = '#E4CE63' })
set(0, 'LazyUrl', { fg = '#7FA5FA', underline = true })
set(0, 'MasonHeader', { fg = '#1D1229', bg = '#E4CE63', bold = true })
set(0, 'MasonHeaderSecondary', { fg = '#1D1229', bg = '#B28FEF', bold = true })
set(0, 'MasonHighlight', { fg = '#E4CE63' })
set(0, 'MasonHighlightBlock', { fg = '#1D1229', bg = '#E4CE63' })
set(0, 'MasonHighlightBlockBold', { fg = '#1D1229', bg = '#E4CE63', bold = true })
set(0, 'MasonHighlightSecondary', { fg = '#B28FEF' })
set(0, 'MasonError', { fg = '#F17074' })
set(0, 'MasonMuted', { fg = '#706183' })
set(0, 'MasonMutedBlock', { fg = '#DBD4E4', bg = '#372947' })
set(0, 'DapBreakpoint', { fg = '#F17074' })
set(0, 'DapBreakpointCondition', { fg = '#E4CE63' })
set(0, 'DapBreakpointRejected', { fg = '#706183' })
set(0, 'DapLogPoint', { fg = '#7FA5FA' })
set(0, 'DapStopped', { fg = '#56D298', bold = true })
set(0, 'DapUIVariable', { fg = '#DBD4E4' })
set(0, 'DapUIScope', { fg = '#E4CE63', bold = true })
set(0, 'DapUIType', { fg = '#E4CE63' })
set(0, 'DapUIValue', { fg = '#F0995B' })
set(0, 'DapUIModifiedValue', { fg = '#F0995B', bold = true })
set(0, 'DapUIDecoration', { fg = '#E4CE63' })
set(0, 'DapUIThread', { fg = '#56D298' })
set(0, 'DapUIStoppedThread', { fg = '#E4CE63', bold = true })
set(0, 'DapUIFrameName', { fg = '#DBD4E4' })
set(0, 'DapUISource', { fg = '#B28FEF' })
set(0, 'DapUILineNumber', { fg = '#706183' })
set(0, 'DapUIFloatBorder', { fg = '#372947', bg = '#170D23' })
set(0, 'DapUIWatchesEmpty', { fg = '#F17074' })
set(0, 'DapUIWatchesValue', { fg = '#56D298' })
set(0, 'DapUIWatchesError', { fg = '#F17074' })
set(0, 'DapUIBreakpointsPath', { fg = '#B28FEF' })
set(0, 'DapUIBreakpointsInfo', { fg = '#56D298' })
set(0, 'DapUIBreakpointsCurrentLine', { fg = '#56D298', bold = true })
set(0, 'GitSignsAddNr', { fg = '#56D298' })
set(0, 'GitSignsAddLn', { bg = '#231531' })
set(0, 'GitSignsChangeNr', { fg = '#E4CE63' })
set(0, 'GitSignsChangeLn', { bg = '#231531' })
set(0, 'GitSignsDeleteNr', { fg = '#F17074' })
set(0, 'GitSignsDeleteLn', { bg = '#231531' })
set(0, 'GitSignsCurrentLineBlame', { fg = '#706183', italic = true })
set(0, 'GitSignsAddInline', { bg = '#2D1F3C' })
set(0, 'GitSignsChangeInline', { bg = '#2D1F3C' })
set(0, 'GitSignsDeleteInline', { bg = '#2D1F3C' })
set(0, 'GitSignsUntracked', { fg = '#F0995B' })
set(0, 'GitSignsStagedAdd', { fg = '#56D298', italic = true })
set(0, 'GitSignsStagedChange', { fg = '#E4CE63', italic = true })
set(0, 'GitSignsStagedDelete', { fg = '#F17074', italic = true })
set(0, 'NotifyERRORBorder', { fg = '#F17074' })
set(0, 'NotifyWARNBorder', { fg = '#F0995B' })
set(0, 'NotifyINFOBorder', { fg = '#7FA5FA' })
set(0, 'NotifyDEBUGBorder', { fg = '#706183' })
set(0, 'NotifyTRACEBorder', { fg = '#B28FEF' })
set(0, 'NotifyERRORIcon', { fg = '#F17074' })
set(0, 'NotifyWARNIcon', { fg = '#F0995B' })
set(0, 'NotifyINFOIcon', { fg = '#7FA5FA' })
set(0, 'NotifyDEBUGIcon', { fg = '#706183' })
set(0, 'NotifyTRACEIcon', { fg = '#B28FEF' })
set(0, 'NotifyERRORTitle', { fg = '#F17074', bold = true })
set(0, 'NotifyWARNTitle', { fg = '#F0995B', bold = true })
set(0, 'NotifyINFOTitle', { fg = '#7FA5FA', bold = true })
set(0, 'NotifyDEBUGTitle', { fg = '#706183', bold = true })
set(0, 'NotifyTRACETitle', { fg = '#B28FEF', bold = true })
set(0, 'NotifyERRORBody', { fg = '#DBD4E4' })
set(0, 'NotifyWARNBody', { fg = '#DBD4E4' })
set(0, 'NotifyINFOBody', { fg = '#DBD4E4' })
set(0, 'NotifyDEBUGBody', { fg = '#DBD4E4' })
set(0, 'NotifyTRACEBody', { fg = '#DBD4E4' })
set(0, 'markdownH4', { fg = '#F0995B', bold = true })
set(0, 'markdownH5', { fg = '#F47DB9', bold = true })
set(0, 'markdownH6', { fg = '#B28FEF', bold = true })
set(0, 'markdownBlockquote', { fg = '#B4A7C5', italic = true })
set(0, 'markdownBold', { fg = '#DBD4E4', bold = true })
set(0, 'markdownItalic', { fg = '#DBD4E4', italic = true })
set(0, 'markdownBoldItalic', { fg = '#DBD4E4', bold = true, italic = true })
set(0, 'markdownCodeBlock', { fg = '#F0995B' })
set(0, 'markdownListMarker', { fg = '#E4CE63' })
set(0, 'markdownOrderedListMarker', { fg = '#E4CE63' })
set(0, 'markdownRule', { fg = '#372947' })
set(0, 'markdownUrl', { fg = '#7FA5FA', underline = true })
set(0, 'markdownLinkText', { fg = '#E4CE63', underline = true })
set(0, 'helpHyperTextEntry', { fg = '#E4CE63' })
set(0, 'helpHyperTextJump', { fg = '#7FA5FA', underline = true })
set(0, 'helpCommand', { fg = '#B28FEF' })
set(0, 'helpExample', { fg = '#F0995B' })
set(0, 'helpSpecial', { fg = '#F47DB9' })
set(0, 'helpNote', { fg = '#E4CE63' })
set(0, 'helpHeader', { fg = '#E4CE63', bold = true })
set(0, 'helpSectionDelim', { fg = '#706183' })
set(0, 'DiagnosticSignError', { fg = '#F17074' })
set(0, 'DiagnosticSignWarn', { fg = '#F0995B' })
set(0, 'DiagnosticSignInfo', { fg = '#7FA5FA' })
set(0, 'DiagnosticSignHint', { fg = '#4DC3DD' })
set(0, 'DiagnosticSignOk', { fg = '#56D298' })
set(0, 'DiagnosticDeprecated', { fg = '#706183' })
set(0, 'DiagnosticUnnecessary', { fg = '#706183', italic = true })
set(0, 'DiagnosticVirtualLines', { fg = '#706183', italic = true })
