-- lumina-oxblood-light -- Lumina (oxblood, light)
-- Generated from spec/lumina.json + spec/nvim_highlights.json.

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = 'light'
vim.g.colors_name = 'lumina-oxblood-light'

local set = vim.api.nvim_set_hl

set(0, 'Normal', { fg = '#2A2024', bg = '#FBF3F2' })
set(0, 'NormalFloat', { fg = '#2A2024', bg = '#F2E6E5' })
set(0, 'FloatBorder', { fg = '#DCCACB', bg = '#F2E6E5' })
set(0, 'FloatTitle', { fg = '#93621A', bg = '#F2E6E5', bold = true })
set(0, 'CursorLine', { bg = '#F2E6E5' })
set(0, 'CursorColumn', { bg = '#F2E6E5' })
set(0, 'CursorLineNr', { fg = '#93621A', bold = true })
set(0, 'LineNr', { fg = '#C6AFB1' })
set(0, 'SignColumn', { bg = '#FBF3F2' })
set(0, 'VertSplit', { fg = '#DCCACB', bg = '#FBF3F2' })
set(0, 'WinSeparator', { fg = '#DCCACB', bg = '#FBF3F2' })
set(0, 'ColorColumn', { bg = '#F2E6E5' })
set(0, 'Folded', { fg = '#9B868A', bg = '#F2E6E5' })
set(0, 'FoldColumn', { fg = '#C6AFB1', bg = '#FBF3F2' })
set(0, 'EndOfBuffer', { fg = '#FBF3F2' })
set(0, 'NonText', { fg = '#DCCACB' })
set(0, 'SpecialKey', { fg = '#C6AFB1' })
set(0, 'Whitespace', { fg = '#DCCACB' })
set(0, 'MatchParen', { fg = '#2E7A56', bg = '#EADBDA', bold = true })
set(0, 'Cursor', { fg = '#FBF3F2', bg = '#93621A' })
set(0, 'iCursor', { link = 'Cursor' })
set(0, 'TermCursor', { link = 'Cursor' })
set(0, 'Visual', { bg = '#EDDADF' })
set(0, 'VisualNOS', { link = 'Visual' })
set(0, 'Search', { fg = '#FBF3F2', bg = '#93621A' })
set(0, 'IncSearch', { fg = '#FBF3F2', bg = '#93621A', bold = true })
set(0, 'CurSearch', { fg = '#FBF3F2', bg = '#A8542A', bold = true })
set(0, 'Substitute', { link = 'IncSearch' })
set(0, 'StatusLine', { fg = '#5C5054', bg = '#F2E6E5' })
set(0, 'StatusLineNC', { fg = '#9B868A', bg = '#F2E6E5' })
set(0, 'TabLine', { fg = '#9B868A', bg = '#F2E6E5' })
set(0, 'TabLineSel', { fg = '#93621A', bg = '#FBF3F2', bold = true })
set(0, 'TabLineFill', { bg = '#F2E6E5' })
set(0, 'WinBar', { fg = '#5C5054', bg = '#FBF3F2' })
set(0, 'WinBarNC', { fg = '#9B868A', bg = '#FBF3F2' })
set(0, 'Pmenu', { fg = '#2A2024', bg = '#F2E6E5' })
set(0, 'PmenuSel', { fg = '#93621A', bg = '#EADBDA', bold = true })
set(0, 'PmenuSbar', { bg = '#EADBDA' })
set(0, 'PmenuThumb', { bg = '#C6AFB1' })
set(0, 'ModeMsg', { fg = '#93621A', bold = true })
set(0, 'MoreMsg', { fg = '#2E7A56' })
set(0, 'MsgArea', { fg = '#2A2024' })
set(0, 'WarningMsg', { fg = '#A8542A' })
set(0, 'ErrorMsg', { fg = '#B23036', bold = true })
set(0, 'Question', { fg = '#2A5C9E' })
set(0, 'Title', { fg = '#93621A', bold = true })
set(0, 'Directory', { fg = '#93621A', bold = true })
set(0, 'DiagnosticError', { fg = '#B23036' })
set(0, 'DiagnosticWarn', { fg = '#A8542A' })
set(0, 'DiagnosticInfo', { fg = '#2A5C9E' })
set(0, 'DiagnosticHint', { fg = '#1C7472' })
set(0, 'DiagnosticOk', { fg = '#2E7A56' })
set(0, 'DiagnosticUnderlineError', { sp = '#B23036', undercurl = true })
set(0, 'DiagnosticUnderlineWarn', { sp = '#A8542A', undercurl = true })
set(0, 'DiagnosticUnderlineInfo', { sp = '#2A5C9E', undercurl = true })
set(0, 'DiagnosticUnderlineHint', { sp = '#1C7472', undercurl = true })
set(0, 'DiagnosticUnderlineOk', { sp = '#2E7A56', undercurl = true })
set(0, 'DiagnosticVirtualTextError', { fg = '#B23036', italic = true })
set(0, 'DiagnosticVirtualTextWarn', { fg = '#A8542A', italic = true })
set(0, 'DiagnosticVirtualTextInfo', { fg = '#2A5C9E', italic = true })
set(0, 'DiagnosticVirtualTextHint', { fg = '#1C7472', italic = true })
set(0, 'DiagnosticVirtualTextOk', { fg = '#2E7A56', italic = true })
set(0, 'Comment', { fg = '#897579', italic = true })
set(0, 'Constant', { fg = '#50469E', bold = true })
set(0, 'String', { fg = '#1A6675' })
set(0, 'Character', { fg = '#1A6675' })
set(0, 'Number', { fg = '#A8542A' })
set(0, 'Boolean', { fg = '#50469E', bold = true })
set(0, 'Float', { fg = '#A8542A' })
set(0, 'Identifier', { fg = '#46393C' })
set(0, 'Function', { fg = '#963F6E' })
set(0, 'Statement', { fg = '#93621A', bold = true })
set(0, 'Conditional', { link = 'Statement' })
set(0, 'Repeat', { link = 'Statement' })
set(0, 'Label', { link = 'Statement' })
set(0, 'Operator', { fg = '#1C7472' })
set(0, 'Keyword', { link = 'Statement' })
set(0, 'Exception', { fg = '#B23036', bold = true })
set(0, 'PreProc', { fg = '#93621A' })
set(0, 'Include', { link = 'PreProc' })
set(0, 'Define', { link = 'PreProc' })
set(0, 'Macro', { link = 'PreProc' })
set(0, 'PreCondit', { link = 'PreProc' })
set(0, 'Type', { fg = '#2E7A56', italic = true })
set(0, 'StorageClass', { fg = '#2E7A56' })
set(0, 'Structure', { fg = '#2E7A56' })
set(0, 'Typedef', { link = 'Type' })
set(0, 'Special', { fg = '#50469E' })
set(0, 'SpecialChar', { fg = '#1A6675' })
set(0, 'Tag', { fg = '#93621A' })
set(0, 'Delimiter', { fg = '#5C5054' })
set(0, 'SpecialComment', { fg = '#6F5F62', italic = true })
set(0, 'Debug', { fg = '#A8542A' })
set(0, 'Underlined', { fg = '#2A5C9E', underline = true })
set(0, 'Error', { fg = '#B23036', bold = true })
set(0, 'Todo', { fg = '#A8542A', bg = '#FBF3F2', bold = true })
set(0, '@comment', { link = 'Comment' })
set(0, '@string', { link = 'String' })
set(0, '@string.escape', { fg = '#1A6675' })
set(0, '@string.regex', { fg = '#A8542A' })
set(0, '@number', { link = 'Number' })
set(0, '@boolean', { link = 'Boolean' })
set(0, '@float', { link = 'Float' })
set(0, '@keyword', { link = 'Keyword' })
set(0, '@keyword.return', { fg = '#93621A', bold = true, italic = true })
set(0, '@keyword.function', { link = 'Keyword' })
set(0, '@keyword.operator', { link = 'Operator' })
set(0, '@conditional', { link = 'Conditional' })
set(0, '@repeat', { link = 'Repeat' })
set(0, '@operator', { link = 'Operator' })
set(0, '@function', { link = 'Function' })
set(0, '@function.call', { fg = '#963F6E' })
set(0, '@function.builtin', { fg = '#2A5C9E' })
set(0, '@function.macro', { fg = '#93621A' })
set(0, '@method', { link = 'Function' })
set(0, '@method.call', { fg = '#963F6E' })
set(0, '@constructor', { fg = '#2E7A56' })
set(0, '@parameter', { fg = '#2A2024', italic = true })
set(0, '@variable', { link = 'Identifier' })
set(0, '@variable.builtin', { fg = '#50469E', italic = true })
set(0, '@type', { link = 'Type' })
set(0, '@type.builtin', { fg = '#2E7A56', italic = true })
set(0, '@type.qualifier', { fg = '#2E7A56' })
set(0, '@constant', { link = 'Constant' })
set(0, '@constant.builtin', { fg = '#50469E', bold = true })
set(0, '@constant.macro', { link = 'Macro' })
set(0, '@namespace', { fg = '#2E7A56' })
set(0, '@module', { fg = '#2E7A56' })
set(0, '@attribute', { fg = '#93621A' })
set(0, '@property', { fg = '#2E7A56' })
set(0, '@field', { fg = '#2E7A56' })
set(0, '@tag', { fg = '#93621A' })
set(0, '@tag.attribute', { fg = '#93621A' })
set(0, '@tag.delimiter', { link = 'Delimiter' })
set(0, '@punctuation', { link = 'Delimiter' })
set(0, '@punctuation.bracket', { link = 'Delimiter' })
set(0, '@punctuation.delimiter', { link = 'Delimiter' })
set(0, '@punctuation.special', { fg = '#50469E' })
set(0, '@text', { fg = '#2A2024' })
set(0, '@text.strong', { bold = true })
set(0, '@text.emphasis', { italic = true })
set(0, '@text.underline', { underline = true })
set(0, '@text.title', { fg = '#93621A', bold = true })
set(0, '@text.literal', { fg = '#A8542A' })
set(0, '@text.uri', { fg = '#2A5C9E', underline = true })
set(0, '@text.todo', { link = 'Todo' })
set(0, '@text.note', { fg = '#2A5C9E', bold = true })
set(0, '@text.warning', { fg = '#A8542A', bold = true })
set(0, '@text.danger', { fg = '#B23036', bold = true })
set(0, '@text.diff.add', { fg = '#2E7A56' })
set(0, '@text.diff.delete', { fg = '#B23036' })
set(0, '@lsp.type.class', { link = '@type' })
set(0, '@lsp.type.function', { link = '@function' })
set(0, '@lsp.type.method', { link = '@method' })
set(0, '@lsp.type.variable', { link = '@variable' })
set(0, '@lsp.type.parameter', { link = '@parameter' })
set(0, '@lsp.type.property', { link = '@property' })
set(0, '@lsp.type.enum', { link = '@type' })
set(0, '@lsp.type.enumMember', { link = '@constant' })
set(0, '@lsp.type.interface', { link = '@type' })
set(0, '@lsp.type.struct', { link = '@type' })
set(0, '@lsp.type.namespace', { link = '@namespace' })
set(0, '@lsp.type.macro', { link = 'Macro' })
set(0, '@lsp.type.type', { link = '@type' })
set(0, '@lsp.type.typeParameter', { link = '@type' })
set(0, 'DiffAdd', { fg = '#2E7A56', bg = '#FBF3F2' })
set(0, 'DiffChange', { fg = '#93621A', bg = '#FBF3F2' })
set(0, 'DiffDelete', { fg = '#B23036', bg = '#FBF3F2' })
set(0, 'DiffText', { fg = '#A8542A', bg = '#FBF3F2', bold = true })
set(0, 'diffAdded', { fg = '#2E7A56' })
set(0, 'diffRemoved', { fg = '#B23036' })
set(0, 'diffChanged', { fg = '#93621A' })
set(0, 'GitSignsAdd', { fg = '#2E7A56' })
set(0, 'GitSignsChange', { fg = '#93621A' })
set(0, 'GitSignsDelete', { fg = '#B23036' })
set(0, 'TelescopeBorder', { fg = '#DCCACB', bg = '#F2E6E5' })
set(0, 'TelescopeNormal', { link = 'NormalFloat' })
set(0, 'TelescopePromptBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeResultsBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopePreviewBorder', { link = 'TelescopeBorder' })
set(0, 'TelescopeSelection', { fg = '#93621A', bg = '#EADBDA' })
set(0, 'TelescopeMatching', { fg = '#93621A', bold = true })
set(0, 'TelescopePromptPrefix', { fg = '#93621A' })
set(0, 'NvimTreeNormal', { link = 'Normal' })
set(0, 'NvimTreeFolderName', { fg = '#93621A' })
set(0, 'NvimTreeFolderIcon', { fg = '#93621A' })
set(0, 'NvimTreeOpenedFolderName', { fg = '#93621A', bold = true })
set(0, 'NvimTreeEmptyFolderName', { fg = '#9B868A' })
set(0, 'NvimTreeRootFolder', { fg = '#50469E', bold = true })
set(0, 'NvimTreeGitDirty', { fg = '#93621A' })
set(0, 'NvimTreeGitNew', { fg = '#2E7A56' })
set(0, 'NvimTreeGitDeleted', { fg = '#B23036' })
set(0, 'NvimTreeIndentMarker', { fg = '#DCCACB' })
set(0, 'markdownH1', { fg = '#93621A', bold = true })
set(0, 'markdownH2', { fg = '#2A5C9E', bold = true })
set(0, 'markdownH3', { fg = '#2E7A56', bold = true })
set(0, 'markdownCode', { fg = '#A8542A' })
set(0, 'markdownLink', { link = 'Underlined' })
