;;; lumina-ember-light-theme.el --- Lumina Ember, light -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Ember, light variant.
;; Warm tan paper with deep inks and an orange lead accent.
;;
;;; Code:

(deftheme lumina-ember-light
  "Lumina Ember, light variant.")

(custom-theme-set-faces
 'lumina-ember-light
 '(default ((t (:foreground "#2A2620" :background "#FAF5EE"))))
 '(fringe ((t (:foreground "#9A8E78" :background "#FAF5EE"))))
 '(mode-line ((t (:foreground "#5C5448" :background "#F1EAE0"))))
 '(mode-line-inactive ((t (:foreground "#9A8E78" :background "#F1EAE0"))))
 '(mode-line-buffer-id ((t (:foreground "#A85410" :weight bold))))
 '(header-line ((t (:foreground "#6E6452" :background "#F1EAE0"))))
 '(header-line-inactive ((t (:foreground "#9A8E78" :background "#F1EAE0"))))
 '(header-line-highlight ((t (:foreground "#A85410"))))
 '(cursor ((t (:background "#A85410"))))
 '(region ((t (:background "#ECE4D3" :extend t))))
 '(secondary-selection ((t (:background "#E8DFCF"))))
 '(hl-line ((t (:background "#F1EAE0" :extend t))))
 '(highlight ((t (:background "#E8DFCF"))))
 '(vertical-border ((t (:foreground "#DBCFBA"))))
 '(window-divider ((t (:foreground "#DBCFBA"))))
 '(window-divider-first-pixel ((t (:foreground "#DBCFBA"))))
 '(window-divider-last-pixel ((t (:foreground "#DBCFBA"))))
 '(internal-border ((t (:background "#FAF5EE"))))
 '(line-number ((t (:foreground "#C5B79E" :background "#FAF5EE"))))
 '(line-number-current-line ((t (:foreground "#A85410" :background "#F1EAE0" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#A85410" :weight bold))))
 '(isearch ((t (:foreground "#FAF5EE" :background "#A85410" :weight bold))))
 '(isearch-fail ((t (:foreground "#B53A2E" :background "#FAF5EE"))))
 '(lazy-highlight ((t (:foreground "#FAF5EE" :background "#8A6310"))))
 '(match ((t (:foreground "#FAF5EE" :background "#2E7A45"))))
 '(show-paren-match ((t (:foreground "#2E7A45" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#B53A2E" :weight bold))))
 '(link ((t (:foreground "#245F9E" :underline t))))
 '(link-visited ((t (:foreground "#4E4694" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#B53A2E" :weight bold))))
 '(warning ((t (:foreground "#A85410" :weight bold))))
 '(success ((t (:foreground "#2E7A45" :weight bold))))
 '(escape-glyph ((t (:foreground "#A85410"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#9A8E78"))))
 '(trailing-whitespace ((t (:background "#B53A2E"))))
 '(font-lock-keyword-face ((t (:foreground "#A85410" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#897C68" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#6E6452" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#2E7A45"))))
 '(font-lock-function-name-face ((t (:foreground "#245F9E"))))
 '(font-lock-variable-name-face ((t (:foreground "#463F34"))))
 '(font-lock-type-face ((t (:foreground "#1A7468" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#8A6310" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#8E3F66"))))
 '(font-lock-preprocessor-face ((t (:foreground "#A85410"))))
 '(font-lock-negation-char-face ((t (:foreground "#B53A2E"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#245F9E"))))
 '(font-lock-property-name-face ((t (:foreground "#1A7468"))))
 '(font-lock-property-use-face ((t (:foreground "#1A7468"))))
 '(font-lock-number-face ((t (:foreground "#B53A2E"))))
 '(font-lock-operator-face ((t (:foreground "#1A6678"))))
 '(font-lock-escape-face ((t (:foreground "#8E3F66"))))
 '(tab-bar ((t (:foreground "#5C5448" :background "#F1EAE0"))))
 '(tab-bar-tab ((t (:foreground "#A85410" :background "#FAF5EE" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#9A8E78" :background "#F1EAE0"))))
 '(outline-1 ((t (:foreground "#A85410" :weight bold))))
 '(outline-2 ((t (:foreground "#245F9E"))))
 '(outline-3 ((t (:foreground "#1A7468"))))
 '(outline-4 ((t (:foreground "#8A6310"))))
 '(outline-5 ((t (:foreground "#A85410"))))
 '(outline-6 ((t (:foreground "#245F9E"))))
 '(outline-7 ((t (:foreground "#1A7468"))))
 '(outline-8 ((t (:foreground "#8A6310"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#A85410" :weight bold :height 1.3))))
 '(org-block ((t (:background "#F1EAE0" :extend t))))
 '(org-block-begin-line ((t (:foreground "#897C68" :background "#F1EAE0" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#B53A2E" :weight bold))))
 '(org-done ((t (:foreground "#2E7A45" :weight bold))))
 '(org-table ((t (:foreground "#2A2620"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#4E4694" :underline t))))
 '(org-code ((t (:foreground "#A85410"))))
 '(org-verbatim ((t (:foreground "#2E7A45"))))
 '(org-special-keyword ((t (:foreground "#4E4694"))))
 '(org-drawer ((t (:foreground "#9A8E78"))))
 '(org-meta-line ((t (:foreground "#9A8E78"))))
 '(markdown-header-face ((t (:foreground "#A85410" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#A85410" :weight bold))))
 '(magit-section-highlight ((t (:background "#F1EAE0"))))
 '(magit-branch-local ((t (:foreground "#245F9E"))))
 '(magit-branch-remote ((t (:foreground "#1A7468"))))
 '(magit-diff-added ((t (:foreground "#2E7A45"))))
 '(magit-diff-removed ((t (:foreground "#B53A2E"))))
 '(magit-diff-context ((t (:foreground "#9A8E78"))))
 '(magit-hash ((t (:foreground "#4E4694"))))
 '(diff-added ((t (:foreground "#2E7A45"))))
 '(diff-removed ((t (:foreground "#B53A2E"))))
 '(diff-changed ((t (:foreground "#8A6310"))))
 '(diff-hunk-header ((t (:foreground "#A85410"))))
 '(dired-directory ((t (:foreground "#A85410" :weight bold))))
 '(dired-symlink ((t (:foreground "#1A6678" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#B53A2E" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#5C5448" :slant italic))))
 '(dired-mark ((t (:foreground "#A85410"))))
 '(dired-marked ((t (:foreground "#A85410" :weight bold))))
 '(dired-flagged ((t (:foreground "#B53A2E" :weight bold))))
 '(dired-warning ((t (:foreground "#A85410"))))
 '(dired-ignored ((t (:foreground "#9A8E78"))))
 '(dired-perm-write ((t (:foreground "#8A6310"))))
 '(dired-set-id ((t (:foreground "#8E3F66"))))
 '(dired-special ((t (:foreground "#4E4694"))))
 '(diredfl-dir-heading ((t (:foreground "#5C5448" :background "#F1EAE0" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#A85410" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#2A2620"))))
 '(diredfl-file-suffix ((t (:foreground "#9A8E78"))))
 '(diredfl-symlink ((t (:foreground "#1A6678" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#2E7A45"))))
 '(diredfl-date-time ((t (:foreground "#9A8E78" :slant italic))))
 '(diredfl-number ((t (:foreground "#A85410"))))
 '(diredfl-no-priv ((t (:foreground "#9A8E78"))))
 '(diredfl-read-priv ((t (:foreground "#2E7A45"))))
 '(diredfl-write-priv ((t (:foreground "#8A6310"))))
 '(diredfl-exec-priv ((t (:foreground "#B53A2E"))))
 '(diredfl-dir-priv ((t (:foreground "#A85410" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#1A6678"))))
 '(diredfl-rare-priv ((t (:foreground "#8E3F66"))))
 '(diredfl-other-priv ((t (:foreground "#4E4694"))))
 '(diredfl-flag-mark ((t (:foreground "#A85410" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#F1EAE0"))))
 '(diredfl-deletion ((t (:foreground "#B53A2E" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#B53A2E" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#A85410"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#9A8E78"))))
 '(diredfl-ignored-file-name ((t (:foreground "#9A8E78"))))
 '(diredfl-autofile-name ((t (:foreground "#1A7468"))))
 '(dired-dirname ((t (:foreground "#A85410" :weight bold))))
 '(dirvish-hl-line ((t (:background "#E8DFCF" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#9A8E78"))))
 '(dirvish-yank-overlay ((t (:background "#E8DFCF"))))
 '(dirvish-quick-access-entry ((t (:foreground "#1A6678"))))
 '(dirvish-emerge-group-title ((t (:foreground "#A85410" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#6E6452" :background "#F1EAE0"))))
 '(dirvish-header-line-face ((t (:foreground "#6E6452" :background "#F1EAE0"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#A85410"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#A85410"))))
 '(vertico-current ((t (:background "#DBCFBA" :extend t))))
 '(corfu-current ((t (:foreground "#2A2620" :background "#DBCFBA"))))
 '(corfu-default ((t (:foreground "#2A2620" :background "#F1EAE0"))))
 '(corfu-border ((t (:foreground "#DBCFBA"))))
 '(corfu-bar ((t (:background "#A85410"))))
 '(orderless-match-face-0 ((t (:foreground "#A85410" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#245F9E" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#1A7468" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#2E7A45" :weight bold))))
 '(doom-modeline-bar ((t (:background "#A85410"))))
 '(doom-modeline-buffer-path ((t (:foreground "#A85410" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#B53A2E" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#2E7A45"))))
 '(doom-modeline-info ((t (:foreground "#2E7A45"))))
 '(doom-modeline-warning ((t (:foreground "#A85410"))))
 '(doom-modeline-error ((t (:foreground "#B53A2E"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#A85410"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#245F9E"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#1A7468"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8A6310"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#8E3F66"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#2E7A45"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#B53A2E" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-ember-light)

;;; lumina-ember-light-theme.el ends here
