;;; lumina-ember-dark-theme.el --- Lumina Ember, dark -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Ember, dark variant.
;; Warm forge-brown ground with an orange incandescent lead accent.
;;
;;; Code:

(deftheme lumina-ember-dark
  "Lumina Ember, dark variant.")

(custom-theme-set-faces
 'lumina-ember-dark
 '(default ((t (:foreground "#E4DACB" :background "#1B1714"))))
 '(fringe ((t (:foreground "#6A5E50" :background "#1B1714"))))
 '(mode-line ((t (:foreground "#A99C8A" :background "#151210"))))
 '(mode-line-inactive ((t (:foreground "#6A5E50" :background "#151210"))))
 '(mode-line-buffer-id ((t (:foreground "#F0974E" :weight bold))))
 '(header-line ((t (:foreground "#8E8072" :background "#151210"))))
 '(header-line-inactive ((t (:foreground "#6A5E50" :background "#151210"))))
 '(header-line-highlight ((t (:foreground "#F0974E"))))
 '(cursor ((t (:background "#F0974E"))))
 '(region ((t (:background "#39322B" :extend t))))
 '(secondary-selection ((t (:background "#2D2722"))))
 '(hl-line ((t (:background "#241F1B" :extend t))))
 '(highlight ((t (:background "#2D2722"))))
 '(vertical-border ((t (:foreground "#39322B"))))
 '(window-divider ((t (:foreground "#39322B"))))
 '(window-divider-first-pixel ((t (:foreground "#39322B"))))
 '(window-divider-last-pixel ((t (:foreground "#39322B"))))
 '(internal-border ((t (:background "#1B1714"))))
 '(line-number ((t (:foreground "#483F36" :background "#1B1714"))))
 '(line-number-current-line ((t (:foreground "#F0974E" :background "#241F1B" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#F0974E" :weight bold))))
 '(isearch ((t (:foreground "#1B1714" :background "#F0974E" :weight bold))))
 '(isearch-fail ((t (:foreground "#E0705A" :background "#1B1714"))))
 '(lazy-highlight ((t (:foreground "#1B1714" :background "#DDB45E"))))
 '(match ((t (:foreground "#1B1714" :background "#82BE7A"))))
 '(show-paren-match ((t (:foreground "#82BE7A" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#E0705A" :weight bold))))
 '(link ((t (:foreground "#66A6CC" :underline t))))
 '(link-visited ((t (:foreground "#A593D2" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#E0705A" :weight bold))))
 '(warning ((t (:foreground "#F0974E" :weight bold))))
 '(success ((t (:foreground "#82BE7A" :weight bold))))
 '(escape-glyph ((t (:foreground "#F0974E"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#6A5E50"))))
 '(trailing-whitespace ((t (:background "#E0705A"))))
 '(font-lock-keyword-face ((t (:foreground "#F0974E" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#8A7C6B" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#978876" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#82BE7A"))))
 '(font-lock-function-name-face ((t (:foreground "#66A6CC"))))
 '(font-lock-variable-name-face ((t (:foreground "#D8CDBC"))))
 '(font-lock-type-face ((t (:foreground "#56B49E" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#DDB45E" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#D086A4"))))
 '(font-lock-preprocessor-face ((t (:foreground "#F0974E"))))
 '(font-lock-negation-char-face ((t (:foreground "#E0705A"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#66A6CC"))))
 '(font-lock-property-name-face ((t (:foreground "#56B49E"))))
 '(font-lock-property-use-face ((t (:foreground "#56B49E"))))
 '(font-lock-number-face ((t (:foreground "#E0705A"))))
 '(font-lock-operator-face ((t (:foreground "#66B6C0"))))
 '(font-lock-escape-face ((t (:foreground "#D086A4"))))
 '(tab-bar ((t (:foreground "#A99C8A" :background "#151210"))))
 '(tab-bar-tab ((t (:foreground "#F0974E" :background "#1B1714" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#6A5E50" :background "#151210"))))
 '(outline-1 ((t (:foreground "#F0974E" :weight bold))))
 '(outline-2 ((t (:foreground "#66A6CC"))))
 '(outline-3 ((t (:foreground "#56B49E"))))
 '(outline-4 ((t (:foreground "#DDB45E"))))
 '(outline-5 ((t (:foreground "#F0974E"))))
 '(outline-6 ((t (:foreground "#66A6CC"))))
 '(outline-7 ((t (:foreground "#56B49E"))))
 '(outline-8 ((t (:foreground "#DDB45E"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#F0974E" :weight bold :height 1.3))))
 '(org-block ((t (:background "#151210" :extend t))))
 '(org-block-begin-line ((t (:foreground "#8A7C6B" :background "#151210" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#E0705A" :weight bold))))
 '(org-done ((t (:foreground "#82BE7A" :weight bold))))
 '(org-table ((t (:foreground "#E4DACB"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#A593D2" :underline t))))
 '(org-code ((t (:foreground "#F0974E"))))
 '(org-verbatim ((t (:foreground "#82BE7A"))))
 '(org-special-keyword ((t (:foreground "#A593D2"))))
 '(org-drawer ((t (:foreground "#6A5E50"))))
 '(org-meta-line ((t (:foreground "#6A5E50"))))
 '(markdown-header-face ((t (:foreground "#F0974E" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#F0974E" :weight bold))))
 '(magit-section-highlight ((t (:background "#241F1B"))))
 '(magit-branch-local ((t (:foreground "#66A6CC"))))
 '(magit-branch-remote ((t (:foreground "#56B49E"))))
 '(magit-diff-added ((t (:foreground "#82BE7A"))))
 '(magit-diff-removed ((t (:foreground "#E0705A"))))
 '(magit-diff-context ((t (:foreground "#6A5E50"))))
 '(magit-hash ((t (:foreground "#A593D2"))))
 '(diff-added ((t (:foreground "#82BE7A"))))
 '(diff-removed ((t (:foreground "#E0705A"))))
 '(diff-changed ((t (:foreground "#DDB45E"))))
 '(diff-hunk-header ((t (:foreground "#F0974E"))))
 '(dired-directory ((t (:foreground "#F0974E" :weight bold))))
 '(dired-symlink ((t (:foreground "#66B6C0" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#E0705A" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#A99C8A" :slant italic))))
 '(dired-mark ((t (:foreground "#F0974E"))))
 '(dired-marked ((t (:foreground "#F0974E" :weight bold))))
 '(dired-flagged ((t (:foreground "#E0705A" :weight bold))))
 '(dired-warning ((t (:foreground "#F0974E"))))
 '(dired-ignored ((t (:foreground "#6A5E50"))))
 '(dired-perm-write ((t (:foreground "#DDB45E"))))
 '(dired-set-id ((t (:foreground "#D086A4"))))
 '(dired-special ((t (:foreground "#A593D2"))))
 '(diredfl-dir-heading ((t (:foreground "#A99C8A" :background "#151210" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#F0974E" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#E4DACB"))))
 '(diredfl-file-suffix ((t (:foreground "#6A5E50"))))
 '(diredfl-symlink ((t (:foreground "#66B6C0" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#82BE7A"))))
 '(diredfl-date-time ((t (:foreground "#6A5E50" :slant italic))))
 '(diredfl-number ((t (:foreground "#F0974E"))))
 '(diredfl-no-priv ((t (:foreground "#6A5E50"))))
 '(diredfl-read-priv ((t (:foreground "#82BE7A"))))
 '(diredfl-write-priv ((t (:foreground "#DDB45E"))))
 '(diredfl-exec-priv ((t (:foreground "#E0705A"))))
 '(diredfl-dir-priv ((t (:foreground "#F0974E" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#66B6C0"))))
 '(diredfl-rare-priv ((t (:foreground "#D086A4"))))
 '(diredfl-other-priv ((t (:foreground "#A593D2"))))
 '(diredfl-flag-mark ((t (:foreground "#F0974E" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#241F1B"))))
 '(diredfl-deletion ((t (:foreground "#E0705A" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#E0705A" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#F0974E"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#6A5E50"))))
 '(diredfl-ignored-file-name ((t (:foreground "#6A5E50"))))
 '(diredfl-autofile-name ((t (:foreground "#56B49E"))))
 '(dired-dirname ((t (:foreground "#F0974E" :weight bold))))
 '(dirvish-hl-line ((t (:background "#2D2722" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#6A5E50"))))
 '(dirvish-yank-overlay ((t (:background "#2D2722"))))
 '(dirvish-quick-access-entry ((t (:foreground "#66B6C0"))))
 '(dirvish-emerge-group-title ((t (:foreground "#F0974E" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#8E8072" :background "#151210"))))
 '(dirvish-header-line-face ((t (:foreground "#8E8072" :background "#151210"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#F0974E"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#F0974E"))))
 '(vertico-current ((t (:background "#39322B" :extend t))))
 '(corfu-current ((t (:foreground "#E4DACB" :background "#39322B"))))
 '(corfu-default ((t (:foreground "#E4DACB" :background "#151210"))))
 '(corfu-border ((t (:foreground "#39322B"))))
 '(corfu-bar ((t (:background "#F0974E"))))
 '(orderless-match-face-0 ((t (:foreground "#F0974E" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#66A6CC" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#56B49E" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#82BE7A" :weight bold))))
 '(doom-modeline-bar ((t (:background "#F0974E"))))
 '(doom-modeline-buffer-path ((t (:foreground "#F0974E" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E0705A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#82BE7A"))))
 '(doom-modeline-info ((t (:foreground "#82BE7A"))))
 '(doom-modeline-warning ((t (:foreground "#F0974E"))))
 '(doom-modeline-error ((t (:foreground "#E0705A"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#F0974E"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#66A6CC"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#56B49E"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#DDB45E"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#D086A4"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#82BE7A"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#E0705A" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-ember-dark)

;;; lumina-ember-dark-theme.el ends here
