;;; lumina-canopy-light-theme.el --- Lumina Canopy, light -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Canopy, light variant.
;; Pale leaf paper with deep botanical inks.
;;
;;; Code:

(deftheme lumina-canopy-light
  "Lumina Canopy, light variant.")

(custom-theme-set-faces
 'lumina-canopy-light
 '(default ((t (:foreground "#1F2A1C" :background "#EEF5EA"))))
 '(fringe ((t (:foreground "#7E977A" :background "#EEF5EA"))))
 '(mode-line ((t (:foreground "#54664E" :background "#E3EEDF"))))
 '(mode-line-inactive ((t (:foreground "#7E977A" :background "#E3EEDF"))))
 '(mode-line-buffer-id ((t (:foreground "#7E6210" :weight bold))))
 '(header-line ((t (:foreground "#5A7256" :background "#E3EEDF"))))
 '(header-line-inactive ((t (:foreground "#7E977A" :background "#E3EEDF"))))
 '(header-line-highlight ((t (:foreground "#7E6210"))))
 '(cursor ((t (:background "#7E6210"))))
 '(region ((t (:background "#DDEAD6" :extend t))))
 '(secondary-selection ((t (:background "#D6E4D2"))))
 '(hl-line ((t (:background "#E3EEDF" :extend t))))
 '(highlight ((t (:background "#D6E4D2"))))
 '(vertical-border ((t (:foreground "#C4D6C0"))))
 '(window-divider ((t (:foreground "#C4D6C0"))))
 '(window-divider-first-pixel ((t (:foreground "#C4D6C0"))))
 '(window-divider-last-pixel ((t (:foreground "#C4D6C0"))))
 '(internal-border ((t (:background "#EEF5EA"))))
 '(line-number ((t (:foreground "#A6C0A2" :background "#EEF5EA"))))
 '(line-number-current-line ((t (:foreground "#7E6210" :background "#E3EEDF" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#7E6210" :weight bold))))
 '(isearch ((t (:foreground "#EEF5EA" :background "#7E6210" :weight bold))))
 '(isearch-fail ((t (:foreground "#A8482E" :background "#EEF5EA"))))
 '(lazy-highlight ((t (:foreground "#EEF5EA" :background "#7E6210"))))
 '(match ((t (:foreground "#EEF5EA" :background "#2E7A3E"))))
 '(show-paren-match ((t (:foreground "#2E7A3E" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#A8482E" :weight bold))))
 '(link ((t (:foreground "#1F5E92" :underline t))))
 '(link-visited ((t (:foreground "#4E469A" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#A8482E" :weight bold))))
 '(warning ((t (:foreground "#9A5A1A" :weight bold))))
 '(success ((t (:foreground "#2E7A3E" :weight bold))))
 '(escape-glyph ((t (:foreground "#9A5A1A"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#7E977A"))))
 '(trailing-whitespace ((t (:background "#A8482E"))))
 '(font-lock-keyword-face ((t (:foreground "#7E6210" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#6E866A" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#5A7256" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#2E7A3E"))))
 '(font-lock-function-name-face ((t (:foreground "#166E58"))))
 '(font-lock-variable-name-face ((t (:foreground "#36402E"))))
 '(font-lock-type-face ((t (:foreground "#9A5A1A" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#4E469A" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#2E7A3E"))))
 '(font-lock-preprocessor-face ((t (:foreground "#7E6210"))))
 '(font-lock-negation-char-face ((t (:foreground "#A8482E"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#166E58"))))
 '(font-lock-property-name-face ((t (:foreground "#2E7A3E"))))
 '(font-lock-property-use-face ((t (:foreground "#2E7A3E"))))
 '(font-lock-number-face ((t (:foreground "#9A5A1A"))))
 '(font-lock-operator-face ((t (:foreground "#5A7256"))))
 '(font-lock-escape-face ((t (:foreground "#9A5A1A"))))
 '(tab-bar ((t (:foreground "#54664E" :background "#E3EEDF"))))
 '(tab-bar-tab ((t (:foreground "#7E6210" :background "#EEF5EA" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#7E977A" :background "#E3EEDF"))))
 '(outline-1 ((t (:foreground "#7E6210" :weight bold))))
 '(outline-2 ((t (:foreground "#166E58"))))
 '(outline-3 ((t (:foreground "#2E7A3E"))))
 '(outline-4 ((t (:foreground "#9A5A1A"))))
 '(outline-5 ((t (:foreground "#7E6210"))))
 '(outline-6 ((t (:foreground "#166E58"))))
 '(outline-7 ((t (:foreground "#2E7A3E"))))
 '(outline-8 ((t (:foreground "#9A5A1A"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#7E6210" :weight bold :height 1.3))))
 '(org-block ((t (:background "#E3EEDF" :extend t))))
 '(org-block-begin-line ((t (:foreground "#6E866A" :background "#E3EEDF" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#9A5A1A" :weight bold))))
 '(org-done ((t (:foreground "#2E7A3E" :weight bold))))
 '(org-table ((t (:foreground "#1F2A1C"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#4E469A" :underline t))))
 '(org-code ((t (:foreground "#9A5A1A"))))
 '(org-verbatim ((t (:foreground "#2E7A3E"))))
 '(org-special-keyword ((t (:foreground "#4E469A"))))
 '(org-drawer ((t (:foreground "#7E977A"))))
 '(org-meta-line ((t (:foreground "#7E977A"))))
 '(markdown-header-face ((t (:foreground "#7E6210" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#7E6210" :weight bold))))
 '(magit-section-highlight ((t (:background "#E3EEDF"))))
 '(magit-branch-local ((t (:foreground "#166E58"))))
 '(magit-branch-remote ((t (:foreground "#2E7A3E"))))
 '(magit-diff-added ((t (:foreground "#2E7A3E"))))
 '(magit-diff-removed ((t (:foreground "#A8482E"))))
 '(magit-diff-context ((t (:foreground "#7E977A"))))
 '(magit-hash ((t (:foreground "#4E469A"))))
 '(diff-added ((t (:foreground "#2E7A3E"))))
 '(diff-removed ((t (:foreground "#A8482E"))))
 '(diff-changed ((t (:foreground "#7E6210"))))
 '(diff-hunk-header ((t (:foreground "#7E6210"))))
 '(dired-directory ((t (:foreground "#7E6210" :weight bold))))
 '(dired-symlink ((t (:foreground "#166678" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#A8482E" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#54664E" :slant italic))))
 '(dired-mark ((t (:foreground "#9A5A1A"))))
 '(dired-marked ((t (:foreground "#9A5A1A" :weight bold))))
 '(dired-flagged ((t (:foreground "#A8482E" :weight bold))))
 '(dired-warning ((t (:foreground "#9A5A1A"))))
 '(dired-ignored ((t (:foreground "#7E977A"))))
 '(dired-perm-write ((t (:foreground "#7E6210"))))
 '(dired-set-id ((t (:foreground "#8E3F66"))))
 '(dired-special ((t (:foreground "#4E469A"))))
 '(diredfl-dir-heading ((t (:foreground "#54664E" :background "#E3EEDF" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#7E6210" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#1F2A1C"))))
 '(diredfl-file-suffix ((t (:foreground "#7E977A"))))
 '(diredfl-symlink ((t (:foreground "#166678" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#2E7A3E"))))
 '(diredfl-date-time ((t (:foreground "#7E977A" :slant italic))))
 '(diredfl-number ((t (:foreground "#9A5A1A"))))
 '(diredfl-no-priv ((t (:foreground "#7E977A"))))
 '(diredfl-read-priv ((t (:foreground "#2E7A3E"))))
 '(diredfl-write-priv ((t (:foreground "#7E6210"))))
 '(diredfl-exec-priv ((t (:foreground "#A8482E"))))
 '(diredfl-dir-priv ((t (:foreground "#7E6210" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#166678"))))
 '(diredfl-rare-priv ((t (:foreground "#8E3F66"))))
 '(diredfl-other-priv ((t (:foreground "#4E469A"))))
 '(diredfl-flag-mark ((t (:foreground "#9A5A1A" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#E3EEDF"))))
 '(diredfl-deletion ((t (:foreground "#A8482E" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#A8482E" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#9A5A1A"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#7E977A"))))
 '(diredfl-ignored-file-name ((t (:foreground "#7E977A"))))
 '(diredfl-autofile-name ((t (:foreground "#166E58"))))
 '(dired-dirname ((t (:foreground "#7E6210" :weight bold))))
 '(dirvish-hl-line ((t (:background "#D6E4D2" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#7E977A"))))
 '(dirvish-yank-overlay ((t (:background "#D6E4D2"))))
 '(dirvish-quick-access-entry ((t (:foreground "#166678"))))
 '(dirvish-emerge-group-title ((t (:foreground "#7E6210" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#5A7256" :background "#E3EEDF"))))
 '(dirvish-header-line-face ((t (:foreground "#5A7256" :background "#E3EEDF"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#9A5A1A"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#7E6210"))))
 '(vertico-current ((t (:background "#C4D6C0" :extend t))))
 '(corfu-current ((t (:foreground "#1F2A1C" :background "#C4D6C0"))))
 '(corfu-default ((t (:foreground "#1F2A1C" :background "#E3EEDF"))))
 '(corfu-border ((t (:foreground "#C4D6C0"))))
 '(corfu-bar ((t (:background "#7E6210"))))
 '(orderless-match-face-0 ((t (:foreground "#7E6210" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#166E58" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#2E7A3E" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#2E7A3E" :weight bold))))
 '(doom-modeline-bar ((t (:background "#7E6210"))))
 '(doom-modeline-buffer-path ((t (:foreground "#7E6210" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#9A5A1A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#2E7A3E"))))
 '(doom-modeline-info ((t (:foreground "#2E7A3E"))))
 '(doom-modeline-warning ((t (:foreground "#9A5A1A"))))
 '(doom-modeline-error ((t (:foreground "#A8482E"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#7E6210"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#166E58"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#2E7A3E"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#9A5A1A"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#4E469A"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#1F5E92"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#A8482E" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-canopy-light)

;;; lumina-canopy-light-theme.el ends here
