;;; lumina-dawn-light-theme.el --- Lumina Dawn, light -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Dawn, light variant.
;; Warm-modern paper with deep readable inks; the reference flavor of the family.
;;
;;; Code:

(deftheme lumina-dawn-light
  "Lumina Dawn, light variant.")

(custom-theme-set-faces
 'lumina-dawn-light
 '(default ((t (:foreground "#2B2A28" :background "#FAF7F2"))))
 '(fringe ((t (:foreground "#9A9080" :background "#FAF7F2"))))
 '(mode-line ((t (:foreground "#5C574F" :background "#F1ECE3"))))
 '(mode-line-inactive ((t (:foreground "#9A9080" :background "#F1ECE3"))))
 '(mode-line-buffer-id ((t (:foreground "#4B4FBF" :weight bold))))
 '(header-line ((t (:foreground "#6E665A" :background "#F1ECE3"))))
 '(header-line-inactive ((t (:foreground "#9A9080" :background "#F1ECE3"))))
 '(header-line-highlight ((t (:foreground "#4B4FBF"))))
 '(cursor ((t (:background "#4B4FBF"))))
 '(region ((t (:background "#E3DEEF" :extend t))))
 '(secondary-selection ((t (:background "#E8E2D6"))))
 '(hl-line ((t (:background "#F1ECE3" :extend t))))
 '(highlight ((t (:background "#E8E2D6"))))
 '(vertical-border ((t (:foreground "#DBD3C4"))))
 '(window-divider ((t (:foreground "#DBD3C4"))))
 '(window-divider-first-pixel ((t (:foreground "#DBD3C4"))))
 '(window-divider-last-pixel ((t (:foreground "#DBD3C4"))))
 '(internal-border ((t (:background "#FAF7F2"))))
 '(line-number ((t (:foreground "#C5BBA8" :background "#FAF7F2"))))
 '(line-number-current-line ((t (:foreground "#4B4FBF" :background "#F1ECE3" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#4B4FBF" :weight bold))))
 '(isearch ((t (:foreground "#FAF7F2" :background "#4B4FBF" :weight bold))))
 '(isearch-fail ((t (:foreground "#BE2F33" :background "#FAF7F2"))))
 '(lazy-highlight ((t (:foreground "#FAF7F2" :background "#9A6B16"))))
 '(match ((t (:foreground "#FAF7F2" :background "#2E7D4F"))))
 '(show-paren-match ((t (:foreground "#2E7D4F" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#BE2F33" :weight bold))))
 '(link ((t (:foreground "#1F6FB5" :underline t))))
 '(link-visited ((t (:foreground "#4B4FBF" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#BE2F33" :weight bold))))
 '(warning ((t (:foreground "#B0532A" :weight bold))))
 '(success ((t (:foreground "#2E7D4F" :weight bold))))
 '(escape-glyph ((t (:foreground "#B0532A"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#9A9080"))))
 '(trailing-whitespace ((t (:background "#BE2F33"))))
 '(font-lock-keyword-face ((t (:foreground "#4B4FBF" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#79705F" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#6E665A" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#2E7D4F"))))
 '(font-lock-function-name-face ((t (:foreground "#1F6FB5"))))
 '(font-lock-variable-name-face ((t (:foreground "#46413A"))))
 '(font-lock-type-face ((t (:foreground "#9A6B16" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#8A3F73" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#8A3F73"))))
 '(font-lock-preprocessor-face ((t (:foreground "#4B4FBF"))))
 '(font-lock-negation-char-face ((t (:foreground "#BE2F33"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#1F6FB5"))))
 '(font-lock-property-name-face ((t (:foreground "#1B6E86"))))
 '(font-lock-property-use-face ((t (:foreground "#1B6E86"))))
 '(font-lock-number-face ((t (:foreground "#B0532A"))))
 '(font-lock-operator-face ((t (:foreground "#6E665A"))))
 '(font-lock-escape-face ((t (:foreground "#8A3F73"))))
 '(tab-bar ((t (:foreground "#5C574F" :background "#F1ECE3"))))
 '(tab-bar-tab ((t (:foreground "#4B4FBF" :background "#FAF7F2" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#9A9080" :background "#F1ECE3"))))
 '(outline-1 ((t (:foreground "#4B4FBF" :weight bold))))
 '(outline-2 ((t (:foreground "#1F6FB5"))))
 '(outline-3 ((t (:foreground "#2E7D4F"))))
 '(outline-4 ((t (:foreground "#8A3F73"))))
 '(outline-5 ((t (:foreground "#4B4FBF"))))
 '(outline-6 ((t (:foreground "#1F6FB5"))))
 '(outline-7 ((t (:foreground "#2E7D4F"))))
 '(outline-8 ((t (:foreground "#8A3F73"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#4B4FBF" :weight bold :height 1.3))))
 '(org-block ((t (:background "#F1ECE3" :extend t))))
 '(org-block-begin-line ((t (:foreground "#79705F" :background "#F1ECE3" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#B0532A" :weight bold))))
 '(org-done ((t (:foreground "#2E7D4F" :weight bold))))
 '(org-table ((t (:foreground "#2B2A28"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#4B4FBF" :underline t))))
 '(org-code ((t (:foreground "#B0532A"))))
 '(org-verbatim ((t (:foreground "#2E7D4F"))))
 '(org-special-keyword ((t (:foreground "#4B4FBF"))))
 '(org-drawer ((t (:foreground "#9A9080"))))
 '(org-meta-line ((t (:foreground "#9A9080"))))
 '(markdown-header-face ((t (:foreground "#4B4FBF" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#4B4FBF" :weight bold))))
 '(magit-section-highlight ((t (:background "#F1ECE3"))))
 '(magit-branch-local ((t (:foreground "#1F6FB5"))))
 '(magit-branch-remote ((t (:foreground "#2E7D4F"))))
 '(magit-diff-added ((t (:foreground "#2E7D4F"))))
 '(magit-diff-removed ((t (:foreground "#BE2F33"))))
 '(magit-diff-context ((t (:foreground "#9A9080"))))
 '(magit-hash ((t (:foreground "#4B4FBF"))))
 '(diff-added ((t (:foreground "#2E7D4F"))))
 '(diff-removed ((t (:foreground "#BE2F33"))))
 '(diff-changed ((t (:foreground "#9A6B16"))))
 '(diff-hunk-header ((t (:foreground "#4B4FBF"))))
 '(dired-directory ((t (:foreground "#4B4FBF" :weight bold))))
 '(dired-symlink ((t (:foreground "#1B6E86" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#BE2F33" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#5C574F" :slant italic))))
 '(dired-mark ((t (:foreground "#B0532A"))))
 '(dired-marked ((t (:foreground "#B0532A" :weight bold))))
 '(dired-flagged ((t (:foreground "#BE2F33" :weight bold))))
 '(dired-warning ((t (:foreground "#B0532A"))))
 '(dired-ignored ((t (:foreground "#9A9080"))))
 '(dired-perm-write ((t (:foreground "#9A6B16"))))
 '(dired-set-id ((t (:foreground "#8A3F73"))))
 '(dired-special ((t (:foreground "#4B4FBF"))))
 '(diredfl-dir-heading ((t (:foreground "#5C574F" :background "#F1ECE3" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#4B4FBF" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#2B2A28"))))
 '(diredfl-file-suffix ((t (:foreground "#9A9080"))))
 '(diredfl-symlink ((t (:foreground "#1B6E86" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#2E7D4F"))))
 '(diredfl-date-time ((t (:foreground "#9A9080" :slant italic))))
 '(diredfl-number ((t (:foreground "#B0532A"))))
 '(diredfl-no-priv ((t (:foreground "#9A9080"))))
 '(diredfl-read-priv ((t (:foreground "#2E7D4F"))))
 '(diredfl-write-priv ((t (:foreground "#9A6B16"))))
 '(diredfl-exec-priv ((t (:foreground "#BE2F33"))))
 '(diredfl-dir-priv ((t (:foreground "#4B4FBF" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#1B6E86"))))
 '(diredfl-rare-priv ((t (:foreground "#8A3F73"))))
 '(diredfl-other-priv ((t (:foreground "#4B4FBF"))))
 '(diredfl-flag-mark ((t (:foreground "#B0532A" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#F1ECE3"))))
 '(diredfl-deletion ((t (:foreground "#BE2F33" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#BE2F33" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#B0532A"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#9A9080"))))
 '(diredfl-ignored-file-name ((t (:foreground "#9A9080"))))
 '(diredfl-autofile-name ((t (:foreground "#1C7A78"))))
 '(dired-dirname ((t (:foreground "#4B4FBF" :weight bold))))
 '(dirvish-hl-line ((t (:background "#E8E2D6" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#9A9080"))))
 '(dirvish-yank-overlay ((t (:background "#E8E2D6"))))
 '(dirvish-quick-access-entry ((t (:foreground "#1B6E86"))))
 '(dirvish-emerge-group-title ((t (:foreground "#4B4FBF" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#6E665A" :background "#F1ECE3"))))
 '(dirvish-header-line-face ((t (:foreground "#6E665A" :background "#F1ECE3"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#B0532A"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#4B4FBF"))))
 '(vertico-current ((t (:background "#E8E2D6" :extend t))))
 '(corfu-current ((t (:foreground "#2B2A28" :background "#E8E2D6"))))
 '(corfu-default ((t (:foreground "#2B2A28" :background "#F1ECE3"))))
 '(corfu-border ((t (:foreground "#DBD3C4"))))
 '(corfu-bar ((t (:background "#4B4FBF"))))
 '(orderless-match-face-0 ((t (:foreground "#4B4FBF" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#1F6FB5" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#2E7D4F" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#2E7D4F" :weight bold))))
 '(doom-modeline-bar ((t (:background "#4B4FBF"))))
 '(doom-modeline-buffer-path ((t (:foreground "#4B4FBF" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#B0532A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#2E7D4F"))))
 '(doom-modeline-info ((t (:foreground "#2E7D4F"))))
 '(doom-modeline-warning ((t (:foreground "#B0532A"))))
 '(doom-modeline-error ((t (:foreground "#BE2F33"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#4B4FBF"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#1F6FB5"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#2E7D4F"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8A3F73"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#1C7A78"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#B0532A"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#BE2F33" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-dawn-light)

;;; lumina-dawn-light-theme.el ends here
