;;; lumina-oxblood-dark-theme.el --- Lumina Oxblood, dark -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Oxblood, dark variant.
;; A theatre after the curtain falls: oxblood-velvet drape in shadow, a single overhead spot on the gilt frame. Velvet rose, brass and wine at equal weight, sage relief, cream-parchment strings.
;;
;;; Code:

(deftheme lumina-oxblood-dark
  "Lumina Oxblood, dark variant.")

(custom-theme-set-faces
 'lumina-oxblood-dark
 '(default ((t (:foreground "#DDCFB8" :background "#23151A"))))
 '(fringe ((t (:foreground "#574047" :background "#23151A"))))
 '(mode-line ((t (:foreground "#BAA793" :background "#1C0F14" :box (:line-width 6 :color "#1C0F14")))))
 '(mode-line-inactive ((t (:foreground "#7C6164" :background "#23151A" :box (:line-width 6 :color "#23151A")))))
 '(mode-line-buffer-id ((t (:foreground "#DDCFB8" :weight semi-bold))))
 '(header-line ((t (:foreground "#9D817F" :background "#1C0F14" :box (:line-width 4 :color "#1C0F14")))))
 '(header-line-inactive ((t (:foreground "#7C6164" :background "#1C0F14" :box (:line-width 4 :color "#1C0F14")))))
 '(header-line-highlight ((t (:foreground "#DAB060"))))
 '(cursor ((t (:background "#DAB060"))))
 '(region ((t (:background "#492B34" :extend t))))
 '(secondary-selection ((t (:background "#322127" :extend t))))
 '(hl-line ((t (:background "#28191F" :extend t))))
 '(highlight ((t (:background "#322127"))))
 '(vertical-border ((t (:foreground "#322127"))))
 '(window-divider ((t (:foreground "#322127"))))
 '(window-divider-first-pixel ((t (:foreground "#322127"))))
 '(window-divider-last-pixel ((t (:foreground "#322127"))))
 '(internal-border ((t (:background "#23151A"))))
 '(line-number ((t (:foreground "#574047" :background "#23151A"))))
 '(line-number-current-line ((t (:foreground "#DAB060" :background "#28191F"))))
 '(minibuffer-prompt ((t (:foreground "#DAB060"))))
 '(isearch ((t (:foreground "#23151A" :background "#DAB060"))))
 '(isearch-fail ((t (:foreground "#D0787F" :background "#381E1E"))))
 '(lazy-highlight ((t (:foreground "#DDCFB8" :background "#3D2A31"))))
 '(match ((t (:foreground "#DAB060" :background "#2B1B21"))))
 '(show-paren-match ((t (:foreground "#DAB060" :background "#3D2A31"))))
 '(show-paren-mismatch ((t (:foreground "#D0787F" :background "#381E1E"))))
 '(link ((t (:foreground "#86A1C4" :underline (:color "#6882A4" :style line)))))
 '(link-visited ((t (:foreground "#AF8FB0" :underline (:color "#7C6164" :style line)))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#D0787F"))))
 '(warning ((t (:foreground "#CF976B"))))
 '(success ((t (:foreground "#86AFA0"))))
 '(escape-glyph ((t (:foreground "#DAB060"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#7C6164"))))
 '(trailing-whitespace ((t (:background "#381E1E"))))
 '(font-lock-keyword-face ((t (:foreground "#C4879E"))))
 '(font-lock-comment-face ((t (:foreground "#91797A" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#A78B86" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#BBAC92"))))
 '(font-lock-function-name-face ((t (:foreground "#DAB060"))))
 '(font-lock-variable-name-face ((t (:foreground "#DDCFB8"))))
 '(font-lock-type-face ((t (:foreground "#86AFA0"))))
 '(font-lock-constant-face ((t (:foreground "#D0787F"))))
 '(font-lock-builtin-face ((t (:foreground "#AF8FB0"))))
 '(font-lock-preprocessor-face ((t (:foreground "#C4879E"))))
 '(font-lock-negation-char-face ((t (:foreground "#D0787F"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#CF976B"))))
 '(font-lock-property-name-face ((t (:foreground "#82ABA5"))))
 '(font-lock-property-use-face ((t (:foreground "#82ABA5"))))
 '(font-lock-number-face ((t (:foreground "#D0787F"))))
 '(font-lock-operator-face ((t (:foreground "#9D817F"))))
 '(font-lock-escape-face ((t (:foreground "#D0787F"))))
 '(tab-bar ((t (:foreground "#BAA793" :background "#1C0F14"))))
 '(tab-bar-tab ((t (:foreground "#DDCFB8" :background "#23151A" :box (:line-width 4 :color "#23151A") :overline "#DAB060"))))
 '(tab-bar-tab-inactive ((t (:foreground "#7C6164" :background "#1C0F14" :box (:line-width 4 :color "#1C0F14")))))
 '(outline-1 ((t (:foreground "#DAB060" :weight semi-bold :height 1.25))))
 '(outline-2 ((t (:foreground "#CF976B" :weight semi-bold :height 1.12))))
 '(outline-3 ((t (:foreground "#C4879E" :weight semi-bold :height 1.05))))
 '(outline-4 ((t (:foreground "#86AFA0" :weight semi-bold))))
 '(outline-5 ((t (:foreground "#DAB060"))))
 '(outline-6 ((t (:foreground "#CF976B"))))
 '(outline-7 ((t (:foreground "#C4879E"))))
 '(outline-8 ((t (:foreground "#86AFA0"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#DAB060" :weight semi-bold :height 1.5))))
 '(org-block ((t (:background "#2B1B21" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7C6164" :background "#2B1B21" :extend t :height 0.85))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#D0787F" :weight semi-bold))))
 '(org-done ((t (:foreground "#86AFA0" :weight semi-bold))))
 '(org-table ((t (:foreground "#BAA793"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#AF8FB0"))))
 '(org-code ((t (:foreground "#CF976B"))))
 '(org-verbatim ((t (:foreground "#86AFA0"))))
 '(org-special-keyword ((t (:foreground "#7C6164"))))
 '(org-drawer ((t (:foreground "#7C6164"))))
 '(org-meta-line ((t (:foreground "#7C6164"))))
 '(org-document-info ((t (:foreground "#BAA793" :height 1.05))))
 '(org-document-info-keyword ((t (:foreground "#7C6164"))))
 '(org-property-value ((t (:foreground "#BAA793"))))
 '(org-priority ((t (:foreground "#D0787F"))))
 '(org-tag ((t (:foreground "#7C6164" :slant italic))))
 '(org-quote ((t (:foreground "#BAA793" :background "#2B1B21" :slant italic :extend t))))
 '(org-verse ((t (:inherit org-quote))))
 '(org-warning ((t (:foreground "#CF976B"))))
 '(org-checkbox ((t (:foreground "#DAB060"))))
 '(org-checkbox-statistics-todo ((t (:foreground "#D0787F"))))
 '(org-checkbox-statistics-done ((t (:foreground "#86AFA0"))))
 '(org-headline-done ((t (:foreground "#7C6164"))))
 '(org-footnote ((t (:foreground "#88ADAE"))))
 '(org-ellipsis ((t (:foreground "#7C6164"))))
 '(org-formula ((t (:foreground "#C4879E"))))
 '(org-agenda-date ((t (:foreground "#DDCFB8" :weight semi-bold))))
 '(org-agenda-date-today ((t (:foreground "#DAB060" :background "#28191F" :weight semi-bold :extend t))))
 '(org-agenda-date-weekend ((t (:foreground "#9D817F" :weight semi-bold))))
 '(org-agenda-structure ((t (:foreground "#DAB060" :weight semi-bold :height 1.15))))
 '(org-agenda-current-time ((t (:foreground "#DAB060"))))
 '(org-scheduled ((t (:foreground "#DDCFB8"))))
 '(org-scheduled-today ((t (:foreground "#DAB060"))))
 '(org-scheduled-previously ((t (:foreground "#CF976B"))))
 '(org-deadline-announce ((t (:foreground "#D0787F"))))
 '(org-upcoming-deadline ((t (:foreground "#CF976B"))))
 '(markdown-header-face ((t (:foreground "#DAB060" :weight semi-bold))))
 '(markdown-header-face-1 ((t (:inherit outline-1))))
 '(markdown-header-face-2 ((t (:inherit outline-2))))
 '(markdown-header-face-3 ((t (:inherit outline-3))))
 '(markdown-header-face-4 ((t (:inherit outline-4))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#DAB060" :weight semi-bold))))
 '(magit-section-heading-selection ((t (:foreground "#DAB060" :background "#28191F"))))
 '(magit-section-highlight ((t (:background "#28191F" :extend t))))
 '(magit-branch-local ((t (:foreground "#CF976B"))))
 '(magit-branch-remote ((t (:foreground "#86AFA0"))))
 '(magit-branch-current ((t (:foreground "#DAB060" :box (:line-width -1 :color "#574047")))))
 '(magit-branch-upstream ((t (:foreground "#86AFA0" :slant italic))))
 '(magit-tag ((t (:foreground "#DAB060"))))
 '(magit-hash ((t (:foreground "#7C6164"))))
 '(magit-log-author ((t (:foreground "#9D817F"))))
 '(magit-log-date ((t (:foreground "#7C6164"))))
 '(magit-log-graph ((t (:foreground "#7C6164"))))
 '(magit-diff-added ((t (:foreground "#86AFA0" :background "#192B21" :extend t))))
 '(magit-diff-added-highlight ((t (:foreground "#86AFA0" :background "#192B21" :extend t))))
 '(magit-diff-removed ((t (:foreground "#D0787F" :background "#381E1E" :extend t))))
 '(magit-diff-removed-highlight ((t (:foreground "#D0787F" :background "#381E1E" :extend t))))
 '(magit-diff-context ((t (:foreground "#7C6164" :extend t))))
 '(magit-diff-context-highlight ((t (:foreground "#BAA793" :background "#28191F" :extend t))))
 '(magit-diff-file-heading ((t (:foreground "#DDCFB8" :weight semi-bold :extend t))))
 '(magit-diff-file-heading-highlight ((t (:foreground "#DDCFB8" :background "#28191F" :weight semi-bold :extend t))))
 '(magit-diff-hunk-heading ((t (:foreground "#9D817F" :background "#322127" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#DDCFB8" :background "#3D2A31" :extend t))))
 '(magit-diff-lines-heading ((t (:foreground "#23151A" :background "#DAB060" :extend t))))
 '(magit-diffstat-added ((t (:foreground "#86AFA0"))))
 '(magit-diffstat-removed ((t (:foreground "#D0787F"))))
 '(magit-process-ok ((t (:foreground "#86AFA0"))))
 '(magit-process-ng ((t (:foreground "#D0787F"))))
 '(magit-blame-heading ((t (:foreground "#BAA793" :background "#2B1B21" :extend t))))
 '(magit-blame-summary ((t (:foreground "#BAA793" :slant italic))))
 '(magit-blame-date ((t (:foreground "#7C6164"))))
 '(magit-blame-name ((t (:foreground "#CF976B"))))
 '(magit-blame-hash ((t (:foreground "#7C6164"))))
 '(magit-bisect-good ((t (:foreground "#86AFA0"))))
 '(magit-bisect-bad ((t (:foreground "#D0787F"))))
 '(magit-bisect-skip ((t (:foreground "#DAB060"))))
 '(magit-cherry-equivalent ((t (:foreground "#C4879E"))))
 '(magit-cherry-unmatched ((t (:foreground "#88ADAE"))))
 '(magit-reflog-amend ((t (:foreground "#C4879E"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#86AFA0"))))
 '(magit-reflog-checkout ((t (:foreground "#86A1C4"))))
 '(magit-reflog-commit ((t (:foreground "#86AFA0"))))
 '(magit-reflog-merge ((t (:foreground "#86AFA0"))))
 '(magit-reflog-other ((t (:foreground "#88ADAE"))))
 '(magit-reflog-rebase ((t (:foreground "#C4879E"))))
 '(magit-reflog-remote ((t (:foreground "#88ADAE"))))
 '(magit-reflog-reset ((t (:foreground "#D0787F"))))
 '(magit-signature-good ((t (:foreground "#86AFA0"))))
 '(magit-signature-bad ((t (:foreground "#D0787F"))))
 '(magit-signature-untrusted ((t (:foreground "#DAB060"))))
 '(magit-signature-expired ((t (:foreground "#CF976B"))))
 '(magit-signature-revoked ((t (:foreground "#C4879E"))))
 '(magit-signature-error ((t (:foreground "#D0787F"))))
 '(diff-added ((t (:foreground "#86AFA0" :background "#192B21" :extend t))))
 '(diff-removed ((t (:foreground "#D0787F" :background "#381E1E" :extend t))))
 '(diff-changed ((t (:foreground "#DAB060" :background "#302412" :extend t))))
 '(diff-hunk-header ((t (:foreground "#9D817F" :background "#2B1B21"))))
 '(dired-directory ((t (:foreground "#DAB060"))))
 '(dired-symlink ((t (:foreground "#88ADAE" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#D0787F" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#BAA793" :slant italic))))
 '(dired-mark ((t (:foreground "#CF976B"))))
 '(dired-marked ((t (:foreground "#CF976B" :weight bold))))
 '(dired-flagged ((t (:foreground "#D0787F" :weight bold))))
 '(dired-warning ((t (:foreground "#CF976B"))))
 '(dired-ignored ((t (:foreground "#7C6164"))))
 '(dired-perm-write ((t (:foreground "#DAB060"))))
 '(dired-set-id ((t (:foreground "#C4879E"))))
 '(dired-special ((t (:foreground "#AF8FB0"))))
 '(diredfl-dir-heading ((t (:foreground "#BAA793" :background "#1C0F14" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#DAB060"))))
 '(diredfl-file-name ((t (:foreground "#DDCFB8"))))
 '(diredfl-file-suffix ((t (:foreground "#7C6164"))))
 '(diredfl-symlink ((t (:foreground "#88ADAE" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#86AFA0"))))
 '(diredfl-date-time ((t (:foreground "#7C6164" :slant italic))))
 '(diredfl-number ((t (:foreground "#CF976B"))))
 '(diredfl-no-priv ((t (:foreground "#7C6164"))))
 '(diredfl-read-priv ((t (:foreground "#86AFA0"))))
 '(diredfl-write-priv ((t (:foreground "#DAB060"))))
 '(diredfl-exec-priv ((t (:foreground "#D0787F"))))
 '(diredfl-dir-priv ((t (:foreground "#DAB060"))))
 '(diredfl-link-priv ((t (:foreground "#88ADAE"))))
 '(diredfl-rare-priv ((t (:foreground "#C4879E"))))
 '(diredfl-other-priv ((t (:foreground "#AF8FB0"))))
 '(diredfl-flag-mark ((t (:foreground "#CF976B" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#28191F"))))
 '(diredfl-deletion ((t (:foreground "#D0787F" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#D0787F" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#CF976B"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#7C6164"))))
 '(diredfl-ignored-file-name ((t (:foreground "#7C6164"))))
 '(diredfl-autofile-name ((t (:foreground "#82ABA5"))))
 '(dired-dirname ((t (:foreground "#DAB060"))))
 '(dirvish-hl-line ((t (:background "#322127" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#7C6164"))))
 '(dirvish-yank-overlay ((t (:background "#322127"))))
 '(dirvish-quick-access-entry ((t (:foreground "#88ADAE"))))
 '(dirvish-emerge-group-title ((t (:foreground "#DAB060" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#9D817F" :background "#1C0F14"))))
 '(dirvish-header-line-face ((t (:foreground "#9D817F" :background "#1C0F14"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#CF976B"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#DAB060"))))
 '(vertico-current ((t (:background "#322127" :extend t))))
 '(vertico-group-title ((t (:foreground "#9D817F" :slant italic))))
 '(vertico-group-separator ((t (:foreground "#3D2A31"))))
 '(vertico-multiline ((t (:foreground "#7C6164"))))
 '(vertico-quick1 ((t (:foreground "#23151A" :background "#DAB060"))))
 '(vertico-quick2 ((t (:foreground "#23151A" :background "#CF976B"))))
 '(consult-preview-cursor ((t (:background "#DAB060"))))
 '(consult-preview-line ((t (:background "#28191F" :extend t))))
 '(consult-preview-error ((t (:foreground "#D0787F" :background "#28191F"))))
 '(consult-preview-insertion ((t (:background "#322127"))))
 '(consult-preview-yank ((t (:background "#322127"))))
 '(consult-async-failed ((t (:foreground "#D0787F"))))
 '(consult-async-running ((t (:foreground "#DAB060"))))
 '(consult-async-finished ((t (:foreground "#86AFA0"))))
 '(consult-async-split ((t (:foreground "#DAB060" :weight bold))))
 '(consult-narrow-indicator ((t (:foreground "#DAB060"))))
 '(consult-bookmark ((t (:foreground "#AF8FB0"))))
 '(consult-buffer ((t (:foreground "#DDCFB8"))))
 '(consult-file ((t (:foreground "#BAA793"))))
 '(consult-grep-context ((t (:foreground "#7C6164"))))
 '(consult-line-number-prefix ((t (:foreground "#7C6164"))))
 '(consult-line-number-wrapped ((t (:foreground "#CF976B"))))
 '(consult-key ((t (:foreground "#DAB060"))))
 '(consult-imenu-prefix ((t (:foreground "#7C6164"))))
 '(consult-separator ((t (:foreground "#574047"))))
 '(consult-help ((t (:foreground "#9D817F"))))
 '(marginalia-key ((t (:foreground "#DAB060"))))
 '(marginalia-mode ((t (:foreground "#AF8FB0"))))
 '(marginalia-modified ((t (:foreground "#CF976B"))))
 '(marginalia-file-name ((t (:foreground "#BAA793"))))
 '(marginalia-file-priv-no ((t (:foreground "#7C6164"))))
 '(marginalia-file-priv-dir ((t (:foreground "#DAB060"))))
 '(marginalia-file-priv-read ((t (:foreground "#86AFA0"))))
 '(marginalia-file-priv-write ((t (:foreground "#DAB060"))))
 '(marginalia-file-priv-exec ((t (:foreground "#D0787F"))))
 '(marginalia-date ((t (:foreground "#7C6164" :slant italic))))
 '(marginalia-documentation ((t (:foreground "#A78B86" :slant italic))))
 '(marginalia-size ((t (:foreground "#CF976B"))))
 '(marginalia-number ((t (:foreground "#CF976B"))))
 '(marginalia-string ((t (:foreground "#BBAC92"))))
 '(marginalia-symbol ((t (:foreground "#AF8FB0"))))
 '(marginalia-list ((t (:foreground "#9D817F"))))
 '(marginalia-type ((t (:foreground "#86AFA0"))))
 '(marginalia-value ((t (:foreground "#DDCFB8"))))
 '(marginalia-version ((t (:foreground "#88ADAE"))))
 '(marginalia-true ((t (:foreground "#86AFA0"))))
 '(marginalia-null ((t (:foreground "#7C6164"))))
 '(corfu-current ((t (:foreground "#DDCFB8" :background "#3D2A31"))))
 '(corfu-default ((t (:foreground "#DDCFB8" :background "#2B1B21"))))
 '(corfu-border ((t (:background "#3D2A31"))))
 '(corfu-bar ((t (:background "#7C6164"))))
 '(corfu-popupinfo ((t (:foreground "#BAA793" :background "#2B1B21"))))
 '(corfu-deprecated ((t (:foreground "#7C6164"))))
 '(orderless-match-face-0 ((t (:foreground "#DAB060" :weight semi-bold))))
 '(orderless-match-face-1 ((t (:foreground "#C4879E" :weight semi-bold))))
 '(orderless-match-face-2 ((t (:foreground "#86AFA0" :weight semi-bold))))
 '(orderless-match-face-3 ((t (:foreground "#86A1C4" :weight semi-bold))))
 '(company-tooltip ((t (:foreground "#DDCFB8" :background "#2B1B21"))))
 '(company-tooltip-common ((t (:foreground "#DAB060"))))
 '(company-tooltip-common-selection ((t (:foreground "#DAB060"))))
 '(company-tooltip-selection ((t (:background "#3D2A31"))))
 '(company-tooltip-annotation ((t (:foreground "#AF8FB0" :slant italic))))
 '(company-tooltip-annotation-selection ((t (:foreground "#AF8FB0" :slant italic))))
 '(company-scrollbar-bg ((t (:background "#322127"))))
 '(company-scrollbar-fg ((t (:background "#DAB060"))))
 '(company-preview ((t (:foreground "#DDCFB8" :background "#28191F"))))
 '(company-preview-common ((t (:foreground "#DAB060"))))
 '(eldoc-highlight-function-argument ((t (:foreground "#DAB060" :underline (:color "#DAB060" :style line)))))
 '(flycheck-error ((t (:underline (:color "#D0787F" :style wave)))))
 '(flycheck-warning ((t (:underline (:color "#CF976B" :style wave)))))
 '(flycheck-info ((t (:underline (:color "#86A1C4" :style wave)))))
 '(flycheck-fringe-error ((t (:foreground "#D0787F"))))
 '(flycheck-fringe-warning ((t (:foreground "#CF976B"))))
 '(flycheck-fringe-info ((t (:foreground "#86A1C4"))))
 '(flycheck-error-list-error ((t (:foreground "#D0787F" :weight bold))))
 '(flycheck-error-list-warning ((t (:foreground "#CF976B"))))
 '(flycheck-error-list-info ((t (:foreground "#86A1C4"))))
 '(flycheck-error-list-line-number ((t (:foreground "#7C6164"))))
 '(flycheck-error-list-filename ((t (:foreground "#BAA793"))))
 '(flycheck-error-list-highlight ((t (:background "#28191F"))))
 '(flymake-error ((t (:underline (:color "#D0787F" :style wave)))))
 '(flymake-warning ((t (:underline (:color "#CF976B" :style wave)))))
 '(flymake-note ((t (:underline (:color "#86A1C4" :style wave)))))
 '(compilation-mode-line-fail ((t (:foreground "#D0787F"))))
 '(compilation-mode-line-exit ((t (:foreground "#86AFA0"))))
 '(compilation-mode-line-run ((t (:foreground "#DAB060"))))
 '(compilation-error ((t (:foreground "#D0787F"))))
 '(compilation-warning ((t (:foreground "#CF976B"))))
 '(compilation-info ((t (:foreground "#86A1C4"))))
 '(compilation-line-number ((t (:foreground "#7C6164"))))
 '(compilation-column-number ((t (:foreground "#7C6164"))))
 '(eshell-prompt ((t (:foreground "#DAB060" :weight semi-bold))))
 '(eshell-ls-directory ((t (:foreground "#DAB060"))))
 '(eshell-ls-executable ((t (:foreground "#86AFA0"))))
 '(eshell-ls-symlink ((t (:foreground "#88ADAE" :slant italic))))
 '(eshell-ls-special ((t (:foreground "#AF8FB0"))))
 '(eshell-ls-archive ((t (:foreground "#CF976B"))))
 '(eshell-ls-backup ((t (:foreground "#7C6164"))))
 '(eshell-ls-product ((t (:foreground "#DAB060"))))
 '(eshell-ls-readonly ((t (:foreground "#D0787F"))))
 '(eshell-ls-missing ((t (:foreground "#D0787F" :slant italic))))
 '(eshell-ls-unreadable ((t (:foreground "#7C6164"))))
 '(eshell-ls-clutter ((t (:foreground "#7C6164"))))
 '(tab-line ((t (:foreground "#BAA793" :background "#1C0F14"))))
 '(tab-line-tab ((t (:foreground "#DDCFB8" :background "#23151A" :box (:line-width 4 :color "#23151A")))))
 '(tab-line-tab-current ((t (:foreground "#DDCFB8" :background "#23151A" :box (:line-width 4 :color "#23151A") :overline "#DAB060"))))
 '(tab-line-tab-inactive ((t (:foreground "#7C6164" :background "#1C0F14" :box (:line-width 4 :color "#1C0F14")))))
 '(tab-line-tab-modified ((t (:foreground "#CF976B" :slant italic))))
 '(tab-line-highlight ((t (:foreground "#DAB060" :background "#23151A"))))
 '(tab-line-close-highlight ((t (:foreground "#D0787F"))))
 '(helpful-heading ((t (:foreground "#DAB060" :weight semi-bold :height 1.15))))
 '(which-key-key-face ((t (:foreground "#DAB060"))))
 '(which-key-separator-face ((t (:foreground "#7C6164"))))
 '(which-key-note-face ((t (:foreground "#7C6164" :slant italic))))
 '(which-key-command-description-face ((t (:foreground "#DDCFB8"))))
 '(which-key-local-map-description-face ((t (:foreground "#AF8FB0"))))
 '(which-key-group-description-face ((t (:foreground "#CF976B"))))
 '(which-key-special-key-face ((t (:foreground "#CF976B"))))
 '(treemacs-root-face ((t (:foreground "#DAB060" :weight semi-bold :height 1.1))))
 '(treemacs-directory-face ((t (:foreground "#BAA793"))))
 '(treemacs-file-face ((t (:foreground "#DDCFB8"))))
 '(treemacs-git-modified-face ((t (:foreground "#CF976B"))))
 '(treemacs-git-added-face ((t (:foreground "#86AFA0"))))
 '(treemacs-git-untracked-face ((t (:foreground "#CF976B" :slant italic))))
 '(treemacs-git-conflict-face ((t (:foreground "#D0787F" :weight bold))))
 '(treemacs-git-renamed-face ((t (:foreground "#AF8FB0"))))
 '(treemacs-git-ignored-face ((t (:foreground "#7C6164"))))
 '(treemacs-tags-face ((t (:foreground "#DAB060"))))
 '(treemacs-on-success-pulse-face ((t (:background "#DAB060"))))
 '(imenu-list-entry-face-0 ((t (:foreground "#DAB060" :weight bold))))
 '(imenu-list-entry-face-1 ((t (:foreground "#DDCFB8"))))
 '(imenu-list-entry-face-2 ((t (:foreground "#BAA793"))))
 '(imenu-list-entry-face-3 ((t (:foreground "#9D817F"))))
 '(ansi-color-black ((t (:foreground "#150B0F"))))
 '(ansi-color-red ((t (:foreground "#D0787F"))))
 '(ansi-color-green ((t (:foreground "#86AFA0"))))
 '(ansi-color-yellow ((t (:foreground "#DAB060"))))
 '(ansi-color-blue ((t (:foreground "#86A1C4"))))
 '(ansi-color-magenta ((t (:foreground "#C4879E"))))
 '(ansi-color-cyan ((t (:foreground "#88ADAE"))))
 '(ansi-color-white ((t (:foreground "#DDCFB8"))))
 '(ansi-color-bright-black ((t (:foreground "#7C6164"))))
 '(ansi-color-bright-red ((t (:foreground "#D0787F"))))
 '(ansi-color-bright-green ((t (:foreground "#86AFA0"))))
 '(ansi-color-bright-yellow ((t (:foreground "#DAB060"))))
 '(ansi-color-bright-blue ((t (:foreground "#86A1C4"))))
 '(ansi-color-bright-magenta ((t (:foreground "#C4879E"))))
 '(ansi-color-bright-cyan ((t (:foreground "#88ADAE"))))
 '(ansi-color-bright-white ((t (:foreground "#DDCFB8"))))
 '(doom-modeline-bar ((t (:background "#DAB060"))))
 '(doom-modeline-buffer-path ((t (:foreground "#9D817F"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#CF976B" :weight semi-bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#BAA793"))))
 '(doom-modeline-info ((t (:foreground "#86AFA0"))))
 '(doom-modeline-warning ((t (:foreground "#CF976B"))))
 '(doom-modeline-error ((t (:foreground "#D0787F"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#DAB060"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#C4879E"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#CF976B"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#86AFA0"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#86A1C4"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#AF8FB0"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#D0787F" :background "#381E1E"))))
 '(font-latex-sectioning-0-face ((t (:foreground "#DAB060" :weight semi-bold :height 1.3))))
 '(font-latex-sectioning-1-face ((t (:foreground "#CF976B" :weight semi-bold :height 1.2))))
 '(font-latex-sectioning-2-face ((t (:foreground "#CF976B" :weight semi-bold :height 1.12))))
 '(font-latex-sectioning-3-face ((t (:foreground "#82ABA5" :weight semi-bold))))
 '(font-latex-sectioning-4-face ((t (:foreground "#86A1C4" :weight semi-bold))))
 '(font-latex-sectioning-5-face ((t (:foreground "#86A1C4"))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-string-face ((t (:foreground "#BBAC92"))))
 '(font-latex-warning-face ((t (:foreground "#D0787F"))))
 '(font-latex-verbatim-face ((t (:foreground "#CF976B"))))
 '(font-latex-math-face ((t (:foreground "#AF8FB0"))))
 '(font-latex-sedate-face ((t (:foreground "#BAA793"))))
 '(font-latex-script-char-face ((t (:foreground "#D0787F"))))
 '(font-latex-doctex-preprocessor-face ((t (:foreground "#C4879E"))))
 '(font-latex-doctex-documentation-face ((t (:foreground "#A78B86"))))
 '(TeX-error-description-error ((t (:foreground "#D0787F"))))
 '(TeX-error-description-warning ((t (:foreground "#CF976B"))))
 '(TeX-error-description-tip ((t (:foreground "#86A1C4"))))
 '(mode-line-active ((t (:inherit mode-line))))
 '(mode-line-emphasis ((t (:foreground "#DAB060"))))
 '(mode-line-highlight ((t (:foreground "#DAB060"))))
 '(line-number-major-tick ((t (:foreground "#7C6164" :background "#23151A"))))
 '(line-number-minor-tick ((t (:foreground "#574047" :background "#23151A"))))
 '(fill-column-indicator ((t (:foreground "#322127"))))
 '(tooltip ((t (:foreground "#DDCFB8" :background "#2B1B21"))))
 '(help-key-binding ((t (:foreground "#DAB060" :background "#2B1B21" :box (:line-width -1 :color "#3D2A31")))))
 '(font-lock-bracket-face ((t (:foreground "#9D817F"))))
 '(font-lock-delimiter-face ((t (:foreground "#9D817F"))))
 '(font-lock-punctuation-face ((t (:foreground "#9D817F"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#9D817F"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#DAB060"))))
 '(org-hide ((t (:foreground "#23151A"))))
 '(org-agenda-done ((t (:foreground "#7C6164"))))
 '(org-time-grid ((t (:foreground "#7C6164"))))
 '(markdown-inline-code-face ((t (:foreground "#CF976B"))))
 '(markdown-markup-face ((t (:foreground "#7C6164"))))
 '(markdown-blockquote-face ((t (:inherit org-quote))))
 '(magit-diff-base ((t (:foreground "#DAB060" :background "#302412" :extend t))))
 '(magit-diff-base-highlight ((t (:foreground "#DAB060" :background "#302412" :extend t))))
 '(magit-diff-revision-summary ((t (:foreground "#DAB060" :weight semi-bold))))
 '(diff-refine-added ((t (:background "#1B412E"))))
 '(diff-refine-removed ((t (:background "#572729"))))
 '(diff-refine-changed ((t (:background "#3D2A31"))))
 '(diff-indicator-added ((t (:foreground "#86AFA0" :background "#192B21"))))
 '(diff-indicator-removed ((t (:foreground "#D0787F" :background "#381E1E"))))
 '(diff-indicator-changed ((t (:foreground "#DAB060" :background "#302412"))))
 '(diff-context ((t (:foreground "#BAA793"))))
 '(diff-header ((t (:foreground "#9D817F" :background "#28191F"))))
 '(diff-file-header ((t (:foreground "#DDCFB8" :background "#322127" :weight semi-bold))))
 '(diff-function ((t (:foreground "#DAB060" :background "#2B1B21"))))
 '(smerge-upper ((t (:background "#381E1E" :extend t))))
 '(smerge-lower ((t (:background "#192B21" :extend t))))
 '(smerge-base ((t (:background "#302412" :extend t))))
 '(smerge-markers ((t (:foreground "#9D817F" :background "#322127" :extend t))))
 '(smerge-refined-added ((t (:background "#1B412E"))))
 '(smerge-refined-removed ((t (:background "#572729"))))
 '(ediff-current-diff-A ((t (:background "#381E1E" :extend t))))
 '(ediff-current-diff-B ((t (:background "#192B21" :extend t))))
 '(ediff-current-diff-C ((t (:background "#302412" :extend t))))
 '(ediff-fine-diff-A ((t (:background "#572729"))))
 '(ediff-fine-diff-B ((t (:background "#1B412E"))))
 '(ediff-fine-diff-C ((t (:background "#3D2A31"))))
 '(ediff-even-diff-A ((t (:background "#28191F"))))
 '(ediff-even-diff-B ((t (:background "#28191F"))))
 '(ediff-odd-diff-A ((t (:background "#322127"))))
 '(ediff-odd-diff-B ((t (:background "#322127"))))
 '(diff-hl-insert ((t (:foreground "#86AFA0" :background "#86AFA0"))))
 '(diff-hl-change ((t (:foreground "#DAB060" :background "#DAB060"))))
 '(diff-hl-delete ((t (:foreground "#D0787F" :background "#D0787F"))))
 '(git-gutter:added ((t (:foreground "#86AFA0"))))
 '(git-gutter:modified ((t (:foreground "#DAB060"))))
 '(git-gutter:deleted ((t (:foreground "#D0787F"))))
 '(git-gutter-fr:added ((t (:foreground "#86AFA0"))))
 '(git-gutter-fr:modified ((t (:foreground "#DAB060"))))
 '(git-gutter-fr:deleted ((t (:foreground "#D0787F"))))
 '(completions-common-part ((t (:foreground "#DAB060"))))
 '(completions-first-difference ((t (:foreground "#DDCFB8" :weight semi-bold))))
 '(completions-annotations ((t (:foreground "#7C6164" :slant italic))))
 '(eglot-highlight-symbol-face ((t (:background "#322127"))))
 '(eglot-inlay-hint-face ((t (:foreground "#7C6164" :height 0.9))))
 '(eglot-mode-line ((t (:foreground "#9D817F"))))
 '(lsp-face-highlight-textual ((t (:background "#322127"))))
 '(lsp-face-highlight-read ((t (:background "#322127"))))
 '(lsp-face-highlight-write ((t (:background "#3D2A31"))))
 '(lsp-inlay-hint-face ((t (:foreground "#7C6164" :height 0.9))))
 '(hl-todo ((t (:foreground "#CF976B" :weight semi-bold))))
 '(pulse-highlight-start-face ((t (:background "#492B34"))))
 '(pulse-highlight-face ((t (:background "#492B34" :extend t))))
 '(nav-flash-face ((t (:background "#492B34" :extend t))))
 '(solaire-default-face ((t (:foreground "#DDCFB8" :background "#1C0F14"))))
 '(solaire-fringe-face ((t (:foreground "#574047" :background "#1C0F14"))))
 '(solaire-line-number-face ((t (:foreground "#574047" :background "#1C0F14"))))
 '(solaire-hl-line-face ((t (:background "#23151A" :extend t))))
 '(solaire-org-hide-face ((t (:foreground "#1C0F14"))))
 '(solaire-minibuffer-face ((t (:foreground "#DDCFB8" :background "#1C0F14"))))
 '(solaire-header-line-face ((t (:foreground "#9D817F" :background "#1C0F14"))))
 '(doom-modeline-bar-inactive ((t (:background "#23151A"))))
 '(doom-modeline-buffer-file ((t (:foreground "#DDCFB8" :weight semi-bold))))
 '(doom-modeline-project-dir ((t (:foreground "#DAB060"))))
 '(doom-modeline-highlight ((t (:foreground "#DAB060"))))
 '(doom-modeline-panel ((t (:foreground "#23151A" :background "#DAB060"))))
 '(doom-modeline-urgent ((t (:foreground "#D0787F"))))
 '(doom-modeline-evil-normal-state ((t (:foreground "#DAB060"))))
 '(doom-modeline-evil-insert-state ((t (:foreground "#82ABA5"))))
 '(doom-modeline-evil-visual-state ((t (:foreground "#AF8FB0"))))
 '(doom-modeline-evil-replace-state ((t (:foreground "#D0787F"))))
 '(doom-modeline-evil-emacs-state ((t (:foreground "#C4879E"))))
 '(doom-modeline-evil-motion-state ((t (:foreground "#86A1C4"))))
 '(doom-modeline-evil-operator-state ((t (:foreground "#86A1C4"))))
 '(doom-dashboard-banner ((t (:foreground "#7C6164"))))
 '(doom-dashboard-menu-title ((t (:foreground "#DAB060"))))
 '(doom-dashboard-menu-desc ((t (:foreground "#9D817F"))))
 '(doom-dashboard-loaded ((t (:foreground "#7C6164" :slant italic))))
 '(doom-dashboard-footer-icon ((t (:foreground "#574047")))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-oxblood-dark)

;;; lumina-oxblood-dark-theme.el ends here
