;;; lumina-dawn-dark-theme.el --- Lumina Dawn, dark -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Dawn, dark variant.
;; Warm sepia ground; aged-ivory text and deep hand-mixed inks of red, ochre, blue and violet under lamplight.
;;
;;; Code:

(deftheme lumina-dawn-dark
  "Lumina Dawn, dark variant.")

(custom-theme-set-faces
 'lumina-dawn-dark
 '(default ((t (:foreground "#E8E1D2" :background "#15120F"))))
 '(fringe ((t (:foreground "#6E6051" :background "#15120F"))))
 '(mode-line ((t (:foreground "#B9AC97" :background "#1A1612"))))
 '(mode-line-inactive ((t (:foreground "#6E6051" :background "#1A1612"))))
 '(mode-line-buffer-id ((t (:foreground "#9292E8" :weight bold))))
 '(header-line ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(header-line-inactive ((t (:foreground "#6E6051" :background "#1E1813"))))
 '(header-line-highlight ((t (:foreground "#9292E8"))))
 '(cursor ((t (:background "#9292E8"))))
 '(region ((t (:background "#2D2A42" :extend t))))
 '(secondary-selection ((t (:background "#241E18"))))
 '(hl-line ((t (:background "#1A1612" :extend t))))
 '(highlight ((t (:background "#241E18"))))
 '(vertical-border ((t (:foreground "#322A20"))))
 '(window-divider ((t (:foreground "#322A20"))))
 '(window-divider-first-pixel ((t (:foreground "#322A20"))))
 '(window-divider-last-pixel ((t (:foreground "#322A20"))))
 '(internal-border ((t (:background "#15120F"))))
 '(line-number ((t (:foreground "#4A3F30" :background "#15120F"))))
 '(line-number-current-line ((t (:foreground "#9292E8" :background "#1A1612" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#9292E8" :weight bold))))
 '(isearch ((t (:foreground "#15120F" :background "#9292E8" :weight bold))))
 '(isearch-fail ((t (:foreground "#E06B62" :background "#15120F"))))
 '(lazy-highlight ((t (:foreground "#15120F" :background "#C9A14E"))))
 '(match ((t (:foreground "#15120F" :background "#7FB58A"))))
 '(show-paren-match ((t (:foreground "#7FB58A" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#E06B62" :weight bold))))
 '(link ((t (:foreground "#6EA6D8" :underline t))))
 '(link-visited ((t (:foreground "#9292E8" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#E06B62" :weight bold))))
 '(warning ((t (:foreground "#D8965A" :weight bold))))
 '(success ((t (:foreground "#7FB58A" :weight bold))))
 '(escape-glyph ((t (:foreground "#D8965A"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#6E6051"))))
 '(trailing-whitespace ((t (:background "#E06B62"))))
 '(font-lock-keyword-face ((t (:foreground "#9292E8" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7A6E5C" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#8C7E68" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#B5A488"))))
 '(font-lock-function-name-face ((t (:foreground "#6EA6D8" :weight semi-bold))))
 '(font-lock-variable-name-face ((t (:foreground "#E8E1D2"))))
 '(font-lock-type-face ((t (:foreground "#7FB58A" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#CC8FB6" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#CC8FB6"))))
 '(font-lock-preprocessor-face ((t (:foreground "#9292E8"))))
 '(font-lock-negation-char-face ((t (:foreground "#E06B62"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#6EA6D8"))))
 '(font-lock-property-name-face ((t (:foreground "#7FB58A"))))
 '(font-lock-property-use-face ((t (:foreground "#7FB58A"))))
 '(font-lock-number-face ((t (:foreground "#D8965A"))))
 '(font-lock-operator-face ((t (:foreground "#8C7C68"))))
 '(font-lock-escape-face ((t (:foreground "#CC8FB6"))))
 '(tab-bar ((t (:foreground "#B9AC97" :background "#1E1813"))))
 '(tab-bar-tab ((t (:foreground "#9292E8" :background "#15120F" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#6E6051" :background "#1E1813"))))
 '(outline-1 ((t (:foreground "#9292E8" :weight bold))))
 '(outline-2 ((t (:foreground "#6EA6D8"))))
 '(outline-3 ((t (:foreground "#CC8FB6"))))
 '(outline-4 ((t (:foreground "#7FB58A"))))
 '(outline-5 ((t (:foreground "#9292E8"))))
 '(outline-6 ((t (:foreground "#6EA6D8"))))
 '(outline-7 ((t (:foreground "#CC8FB6"))))
 '(outline-8 ((t (:foreground "#7FB58A"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#9292E8" :weight bold :height 1.3))))
 '(org-block ((t (:background "#1E1813" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7A6E5C" :background "#1E1813" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#E06B62" :weight bold))))
 '(org-done ((t (:foreground "#7FB58A" :weight bold))))
 '(org-table ((t (:foreground "#E8E1D2"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#9292E8" :underline t))))
 '(org-code ((t (:foreground "#D8965A"))))
 '(org-verbatim ((t (:foreground "#7FB58A"))))
 '(org-special-keyword ((t (:foreground "#9292E8"))))
 '(org-drawer ((t (:foreground "#6E6051"))))
 '(org-meta-line ((t (:foreground "#6E6051"))))
 '(org-document-info ((t (:foreground "#B9AC97"))))
 '(org-document-info-keyword ((t (:foreground "#6E6051"))))
 '(org-property-value ((t (:foreground "#E8E1D2"))))
 '(org-priority ((t (:foreground "#E06B62" :weight bold))))
 '(org-tag ((t (:foreground "#7FB58A" :slant italic))))
 '(org-quote ((t (:foreground "#B9AC97" :slant italic))))
 '(org-verse ((t (:inherit org-quote))))
 '(org-warning ((t (:foreground "#D8965A" :weight bold))))
 '(org-checkbox ((t (:foreground "#9292E8" :weight bold))))
 '(org-checkbox-statistics-todo ((t (:foreground "#E06B62" :weight bold))))
 '(org-checkbox-statistics-done ((t (:foreground "#7FB58A" :weight bold))))
 '(org-headline-done ((t (:foreground "#6E6051"))))
 '(org-footnote ((t (:foreground "#4FA3B8" :underline t))))
 '(org-ellipsis ((t (:foreground "#6E6051"))))
 '(org-formula ((t (:foreground "#CC8FB6"))))
 '(org-agenda-date ((t (:foreground "#9292E8" :weight bold))))
 '(org-agenda-date-today ((t (:foreground "#9292E8" :background "#1A1612" :weight bold))))
 '(org-agenda-date-weekend ((t (:foreground "#9292E8"))))
 '(org-agenda-structure ((t (:foreground "#9292E8" :weight bold))))
 '(org-agenda-current-time ((t (:foreground "#9292E8"))))
 '(org-scheduled ((t (:foreground "#E8E1D2"))))
 '(org-scheduled-today ((t (:foreground "#9292E8"))))
 '(org-scheduled-previously ((t (:foreground "#D8965A"))))
 '(org-deadline-announce ((t (:foreground "#D8965A"))))
 '(org-upcoming-deadline ((t (:foreground "#C9A14E"))))
 '(markdown-header-face ((t (:foreground "#9292E8" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#9292E8" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#9292E8" :background "#1A1612" :weight bold))))
 '(magit-section-highlight ((t (:background "#1A1612"))))
 '(magit-branch-local ((t (:foreground "#6EA6D8"))))
 '(magit-branch-remote ((t (:foreground "#7FB58A"))))
 '(magit-branch-current ((t (:foreground "#9292E8" :weight bold))))
 '(magit-branch-upstream ((t (:foreground "#7FB58A" :slant italic))))
 '(magit-tag ((t (:foreground "#C9A14E"))))
 '(magit-hash ((t (:foreground "#9292E8"))))
 '(magit-log-author ((t (:foreground "#9292E8"))))
 '(magit-log-date ((t (:foreground "#6E6051"))))
 '(magit-log-graph ((t (:foreground "#6E6051"))))
 '(magit-diff-added ((t (:foreground "#7FB58A"))))
 '(magit-diff-added-highlight ((t (:foreground "#7FB58A" :background "#1A1612"))))
 '(magit-diff-removed ((t (:foreground "#E06B62"))))
 '(magit-diff-removed-highlight ((t (:foreground "#E06B62" :background "#1A1612"))))
 '(magit-diff-context ((t (:foreground "#6E6051"))))
 '(magit-diff-context-highlight ((t (:foreground "#8C7C68" :background "#1A1612"))))
 '(magit-diff-file-heading ((t (:foreground "#E8E1D2" :weight bold))))
 '(magit-diff-file-heading-highlight ((t (:foreground "#E8E1D2" :background "#1A1612" :weight bold))))
 '(magit-diff-hunk-heading ((t (:foreground "#B9AC97" :background "#241E18"))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#E8E1D2" :background "#241E18" :weight bold))))
 '(magit-diff-lines-heading ((t (:foreground "#9292E8" :background "#241E18" :weight bold))))
 '(magit-diffstat-added ((t (:foreground "#7FB58A"))))
 '(magit-diffstat-removed ((t (:foreground "#E06B62"))))
 '(magit-process-ok ((t (:foreground "#7FB58A" :weight bold))))
 '(magit-process-ng ((t (:foreground "#E06B62" :weight bold))))
 '(magit-blame-heading ((t (:foreground "#B9AC97" :background "#1A1612"))))
 '(magit-blame-summary ((t (:foreground "#B9AC97" :slant italic))))
 '(magit-blame-date ((t (:foreground "#6E6051"))))
 '(magit-blame-name ((t (:foreground "#9292E8"))))
 '(magit-blame-hash ((t (:foreground "#9292E8"))))
 '(magit-bisect-good ((t (:foreground "#7FB58A"))))
 '(magit-bisect-bad ((t (:foreground "#E06B62"))))
 '(magit-bisect-skip ((t (:foreground "#C9A14E"))))
 '(magit-cherry-equivalent ((t (:foreground "#CC8FB6"))))
 '(magit-cherry-unmatched ((t (:foreground "#4FA3B8"))))
 '(magit-reflog-amend ((t (:foreground "#CC8FB6"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#7FB58A"))))
 '(magit-reflog-checkout ((t (:foreground "#6EA6D8"))))
 '(magit-reflog-commit ((t (:foreground "#7FB58A"))))
 '(magit-reflog-merge ((t (:foreground "#7FB58A"))))
 '(magit-reflog-other ((t (:foreground "#4FA3B8"))))
 '(magit-reflog-rebase ((t (:foreground "#CC8FB6"))))
 '(magit-reflog-remote ((t (:foreground "#4FA3B8"))))
 '(magit-reflog-reset ((t (:foreground "#E06B62"))))
 '(magit-signature-good ((t (:foreground "#7FB58A"))))
 '(magit-signature-bad ((t (:foreground "#E06B62"))))
 '(magit-signature-untrusted ((t (:foreground "#C9A14E"))))
 '(magit-signature-expired ((t (:foreground "#D8965A"))))
 '(magit-signature-revoked ((t (:foreground "#CC8FB6"))))
 '(magit-signature-error ((t (:foreground "#E06B62"))))
 '(diff-added ((t (:foreground "#7FB58A"))))
 '(diff-removed ((t (:foreground "#E06B62"))))
 '(diff-changed ((t (:foreground "#C9A14E"))))
 '(diff-hunk-header ((t (:foreground "#9292E8"))))
 '(dired-directory ((t (:foreground "#9292E8" :weight bold))))
 '(dired-symlink ((t (:foreground "#4FA3B8" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#E06B62" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#B9AC97" :slant italic))))
 '(dired-mark ((t (:foreground "#D8965A"))))
 '(dired-marked ((t (:foreground "#D8965A" :weight bold))))
 '(dired-flagged ((t (:foreground "#E06B62" :weight bold))))
 '(dired-warning ((t (:foreground "#D8965A"))))
 '(dired-ignored ((t (:foreground "#6E6051"))))
 '(dired-perm-write ((t (:foreground "#C9A14E"))))
 '(dired-set-id ((t (:foreground "#CC8FB6"))))
 '(dired-special ((t (:foreground "#9292E8"))))
 '(diredfl-dir-heading ((t (:foreground "#B9AC97" :background "#1E1813" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#9292E8" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#E8E1D2"))))
 '(diredfl-file-suffix ((t (:foreground "#6E6051"))))
 '(diredfl-symlink ((t (:foreground "#4FA3B8" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#7FB58A"))))
 '(diredfl-date-time ((t (:foreground "#6E6051" :slant italic))))
 '(diredfl-number ((t (:foreground "#D8965A"))))
 '(diredfl-no-priv ((t (:foreground "#6E6051"))))
 '(diredfl-read-priv ((t (:foreground "#7FB58A"))))
 '(diredfl-write-priv ((t (:foreground "#C9A14E"))))
 '(diredfl-exec-priv ((t (:foreground "#E06B62"))))
 '(diredfl-dir-priv ((t (:foreground "#9292E8" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#4FA3B8"))))
 '(diredfl-rare-priv ((t (:foreground "#CC8FB6"))))
 '(diredfl-other-priv ((t (:foreground "#9292E8"))))
 '(diredfl-flag-mark ((t (:foreground "#D8965A" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#1A1612"))))
 '(diredfl-deletion ((t (:foreground "#E06B62" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#E06B62" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#D8965A"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#6E6051"))))
 '(diredfl-ignored-file-name ((t (:foreground "#6E6051"))))
 '(diredfl-autofile-name ((t (:foreground "#4FB0A6"))))
 '(dired-dirname ((t (:foreground "#9292E8" :weight bold))))
 '(dirvish-hl-line ((t (:background "#241E18" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#6E6051"))))
 '(dirvish-yank-overlay ((t (:background "#241E18"))))
 '(dirvish-quick-access-entry ((t (:foreground "#4FA3B8"))))
 '(dirvish-emerge-group-title ((t (:foreground "#9292E8" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(dirvish-header-line-face ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#D8965A"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#9292E8"))))
 '(vertico-current ((t (:background "#241E18" :extend t))))
 '(vertico-group-title ((t (:foreground "#9292E8" :weight bold))))
 '(vertico-group-separator ((t (:foreground "#4A3F30"))))
 '(vertico-multiline ((t (:foreground "#6E6051"))))
 '(vertico-quick1 ((t (:foreground "#9292E8" :weight bold))))
 '(vertico-quick2 ((t (:foreground "#D8965A" :weight bold))))
 '(consult-preview-cursor ((t (:background "#9292E8"))))
 '(consult-preview-line ((t (:background "#1A1612" :extend t))))
 '(consult-preview-error ((t (:foreground "#E06B62" :background "#1A1612"))))
 '(consult-preview-insertion ((t (:background "#241E18"))))
 '(consult-preview-yank ((t (:background "#241E18"))))
 '(consult-async-failed ((t (:foreground "#E06B62"))))
 '(consult-async-running ((t (:foreground "#C9A14E"))))
 '(consult-async-finished ((t (:foreground "#7FB58A"))))
 '(consult-async-split ((t (:foreground "#9292E8" :weight bold))))
 '(consult-narrow-indicator ((t (:foreground "#9292E8" :weight bold))))
 '(consult-bookmark ((t (:foreground "#9292E8"))))
 '(consult-buffer ((t (:foreground "#E8E1D2"))))
 '(consult-file ((t (:foreground "#B9AC97"))))
 '(consult-grep-context ((t (:foreground "#6E6051"))))
 '(consult-line-number-prefix ((t (:foreground "#6E6051"))))
 '(consult-line-number-wrapped ((t (:foreground "#D8965A"))))
 '(consult-key ((t (:foreground "#9292E8" :weight bold))))
 '(consult-imenu-prefix ((t (:foreground "#6E6051"))))
 '(consult-separator ((t (:foreground "#4A3F30"))))
 '(consult-help ((t (:foreground "#8C7C68"))))
 '(marginalia-key ((t (:foreground "#9292E8"))))
 '(marginalia-mode ((t (:foreground "#9292E8"))))
 '(marginalia-modified ((t (:foreground "#D8965A"))))
 '(marginalia-file-name ((t (:foreground "#B9AC97"))))
 '(marginalia-file-priv-no ((t (:foreground "#6E6051"))))
 '(marginalia-file-priv-dir ((t (:foreground "#9292E8"))))
 '(marginalia-file-priv-read ((t (:foreground "#7FB58A"))))
 '(marginalia-file-priv-write ((t (:foreground "#C9A14E"))))
 '(marginalia-file-priv-exec ((t (:foreground "#E06B62"))))
 '(marginalia-date ((t (:foreground "#6E6051" :slant italic))))
 '(marginalia-documentation ((t (:foreground "#8C7E68" :slant italic))))
 '(marginalia-size ((t (:foreground "#D8965A"))))
 '(marginalia-number ((t (:foreground "#D8965A"))))
 '(marginalia-string ((t (:foreground "#B5A488"))))
 '(marginalia-symbol ((t (:foreground "#9292E8"))))
 '(marginalia-list ((t (:foreground "#8C7C68"))))
 '(marginalia-type ((t (:foreground "#7FB58A"))))
 '(marginalia-value ((t (:foreground "#E8E1D2"))))
 '(marginalia-version ((t (:foreground "#4FA3B8"))))
 '(marginalia-true ((t (:foreground "#7FB58A"))))
 '(marginalia-null ((t (:foreground "#6E6051"))))
 '(corfu-current ((t (:foreground "#E8E1D2" :background "#241E18"))))
 '(corfu-default ((t (:foreground "#E8E1D2" :background "#1E1813"))))
 '(corfu-border ((t (:foreground "#322A20"))))
 '(corfu-bar ((t (:background "#9292E8"))))
 '(corfu-popupinfo ((t (:background "#1E1813"))))
 '(corfu-deprecated ((t (:foreground "#6E6051"))))
 '(orderless-match-face-0 ((t (:foreground "#9292E8" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#6EA6D8" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#CC8FB6" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#7FB58A" :weight bold))))
 '(company-tooltip ((t (:foreground "#E8E1D2" :background "#1E1813"))))
 '(company-tooltip-common ((t (:foreground "#9292E8" :weight bold))))
 '(company-tooltip-common-selection ((t (:foreground "#9292E8" :weight bold))))
 '(company-tooltip-selection ((t (:background "#241E18"))))
 '(company-tooltip-annotation ((t (:foreground "#9292E8" :slant italic))))
 '(company-tooltip-annotation-selection ((t (:foreground "#9292E8" :slant italic))))
 '(company-scrollbar-bg ((t (:background "#241E18"))))
 '(company-scrollbar-fg ((t (:background "#9292E8"))))
 '(company-preview ((t (:foreground "#E8E1D2" :background "#1A1612"))))
 '(company-preview-common ((t (:foreground "#9292E8"))))
 '(eldoc-highlight-function-argument ((t (:foreground "#9292E8" :weight bold))))
 '(flycheck-error ((t (:foreground "#E06B62" :underline t))))
 '(flycheck-warning ((t (:foreground "#D8965A" :underline t))))
 '(flycheck-info ((t (:foreground "#6EA6D8" :underline t))))
 '(flycheck-fringe-error ((t (:foreground "#E06B62"))))
 '(flycheck-fringe-warning ((t (:foreground "#D8965A"))))
 '(flycheck-fringe-info ((t (:foreground "#6EA6D8"))))
 '(flycheck-error-list-error ((t (:foreground "#E06B62" :weight bold))))
 '(flycheck-error-list-warning ((t (:foreground "#D8965A"))))
 '(flycheck-error-list-info ((t (:foreground "#6EA6D8"))))
 '(flycheck-error-list-line-number ((t (:foreground "#6E6051"))))
 '(flycheck-error-list-filename ((t (:foreground "#B9AC97"))))
 '(flycheck-error-list-highlight ((t (:background "#1A1612"))))
 '(flymake-error ((t (:foreground "#E06B62" :underline t))))
 '(flymake-warning ((t (:foreground "#D8965A" :underline t))))
 '(flymake-note ((t (:foreground "#6EA6D8" :underline t))))
 '(compilation-mode-line-fail ((t (:foreground "#E06B62" :weight bold))))
 '(compilation-mode-line-exit ((t (:foreground "#7FB58A" :weight bold))))
 '(compilation-mode-line-run ((t (:foreground "#C9A14E" :weight bold))))
 '(compilation-error ((t (:foreground "#E06B62" :weight bold))))
 '(compilation-warning ((t (:foreground "#D8965A" :weight bold))))
 '(compilation-info ((t (:foreground "#6EA6D8"))))
 '(compilation-line-number ((t (:foreground "#6E6051"))))
 '(compilation-column-number ((t (:foreground "#6E6051"))))
 '(eshell-prompt ((t (:foreground "#9292E8" :weight bold))))
 '(eshell-ls-directory ((t (:foreground "#9292E8" :weight bold))))
 '(eshell-ls-executable ((t (:foreground "#7FB58A"))))
 '(eshell-ls-symlink ((t (:foreground "#4FA3B8" :slant italic))))
 '(eshell-ls-special ((t (:foreground "#9292E8"))))
 '(eshell-ls-archive ((t (:foreground "#D8965A"))))
 '(eshell-ls-backup ((t (:foreground "#6E6051"))))
 '(eshell-ls-product ((t (:foreground "#C9A14E"))))
 '(eshell-ls-readonly ((t (:foreground "#E06B62"))))
 '(eshell-ls-missing ((t (:foreground "#E06B62" :slant italic))))
 '(eshell-ls-unreadable ((t (:foreground "#6E6051"))))
 '(eshell-ls-clutter ((t (:foreground "#6E6051"))))
 '(tab-line ((t (:foreground "#B9AC97" :background "#1E1813"))))
 '(tab-line-tab ((t (:foreground "#9292E8" :background "#15120F" :weight bold))))
 '(tab-line-tab-current ((t (:foreground "#9292E8" :background "#15120F" :weight bold))))
 '(tab-line-tab-inactive ((t (:foreground "#6E6051" :background "#1E1813"))))
 '(tab-line-tab-modified ((t (:foreground "#D8965A" :slant italic))))
 '(tab-line-highlight ((t (:foreground "#9292E8" :background "#15120F"))))
 '(tab-line-close-highlight ((t (:foreground "#E06B62"))))
 '(helpful-heading ((t (:foreground "#9292E8" :weight bold :height 1.15))))
 '(which-key-key-face ((t (:foreground "#9292E8" :weight bold))))
 '(which-key-separator-face ((t (:foreground "#6E6051"))))
 '(which-key-note-face ((t (:foreground "#6E6051" :slant italic))))
 '(which-key-command-description-face ((t (:foreground "#E8E1D2"))))
 '(which-key-local-map-description-face ((t (:foreground "#9292E8"))))
 '(which-key-group-description-face ((t (:foreground "#9292E8" :slant italic))))
 '(which-key-special-key-face ((t (:foreground "#D8965A" :weight bold))))
 '(treemacs-root-face ((t (:foreground "#9292E8" :weight bold :height 1.1))))
 '(treemacs-directory-face ((t (:foreground "#9292E8"))))
 '(treemacs-file-face ((t (:foreground "#E8E1D2"))))
 '(treemacs-git-modified-face ((t (:foreground "#D8965A"))))
 '(treemacs-git-added-face ((t (:foreground "#7FB58A"))))
 '(treemacs-git-untracked-face ((t (:foreground "#D8965A" :slant italic))))
 '(treemacs-git-conflict-face ((t (:foreground "#E06B62" :weight bold))))
 '(treemacs-git-renamed-face ((t (:foreground "#9292E8"))))
 '(treemacs-git-ignored-face ((t (:foreground "#6E6051"))))
 '(treemacs-tags-face ((t (:foreground "#C9A14E"))))
 '(treemacs-on-success-pulse-face ((t (:background "#9292E8"))))
 '(imenu-list-entry-face-0 ((t (:foreground "#9292E8" :weight bold))))
 '(imenu-list-entry-face-1 ((t (:foreground "#E8E1D2"))))
 '(imenu-list-entry-face-2 ((t (:foreground "#B9AC97"))))
 '(imenu-list-entry-face-3 ((t (:foreground "#8C7C68"))))
 '(ansi-color-black ((t (:foreground "#100D0A"))))
 '(ansi-color-red ((t (:foreground "#E06B62"))))
 '(ansi-color-green ((t (:foreground "#7FB58A"))))
 '(ansi-color-yellow ((t (:foreground "#C9A14E"))))
 '(ansi-color-blue ((t (:foreground "#6EA6D8"))))
 '(ansi-color-magenta ((t (:foreground "#CC8FB6"))))
 '(ansi-color-cyan ((t (:foreground "#4FA3B8"))))
 '(ansi-color-white ((t (:foreground "#E8E1D2"))))
 '(ansi-color-bright-black ((t (:foreground "#6E6051"))))
 '(ansi-color-bright-red ((t (:foreground "#E06B62"))))
 '(ansi-color-bright-green ((t (:foreground "#7FB58A"))))
 '(ansi-color-bright-yellow ((t (:foreground "#C9A14E"))))
 '(ansi-color-bright-blue ((t (:foreground "#6EA6D8"))))
 '(ansi-color-bright-magenta ((t (:foreground "#CC8FB6"))))
 '(ansi-color-bright-cyan ((t (:foreground "#4FA3B8"))))
 '(ansi-color-bright-white ((t (:foreground "#E8E1D2"))))
 '(doom-modeline-bar ((t (:background "#9292E8"))))
 '(doom-modeline-buffer-path ((t (:foreground "#9292E8" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#D8965A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#7FB58A"))))
 '(doom-modeline-info ((t (:foreground "#7FB58A"))))
 '(doom-modeline-warning ((t (:foreground "#D8965A"))))
 '(doom-modeline-error ((t (:foreground "#E06B62"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#9292E8"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#6EA6D8"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#CC8FB6"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#7FB58A"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#D8965A"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#4FB0A6"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#E06B62" :weight bold))))
 '(font-latex-sectioning-0-face ((t (:foreground "#9292E8" :weight bold :height 1.3))))
 '(font-latex-sectioning-1-face ((t (:foreground "#CC8FB6" :weight bold :height 1.2))))
 '(font-latex-sectioning-2-face ((t (:foreground "#CC8FB6" :weight bold :height 1.15))))
 '(font-latex-sectioning-3-face ((t (:foreground "#6EA6D8" :weight bold))))
 '(font-latex-sectioning-4-face ((t (:foreground "#7FB58A" :weight bold))))
 '(font-latex-sectioning-5-face ((t (:foreground "#6EA6D8"))))
 '(font-latex-bold-face ((t (:inherit bold))))
 '(font-latex-italic-face ((t (:inherit italic))))
 '(font-latex-string-face ((t (:foreground "#B5A488"))))
 '(font-latex-warning-face ((t (:foreground "#E06B62" :weight bold))))
 '(font-latex-verbatim-face ((t (:foreground "#D8965A"))))
 '(font-latex-math-face ((t (:foreground "#9292E8"))))
 '(font-latex-sedate-face ((t (:foreground "#B9AC97"))))
 '(font-latex-script-char-face ((t (:foreground "#CC8FB6"))))
 '(font-latex-doctex-preprocessor-face ((t (:foreground "#9292E8"))))
 '(font-latex-doctex-documentation-face ((t (:foreground "#8C7E68"))))
 '(TeX-error-description-error ((t (:foreground "#E06B62" :weight bold))))
 '(TeX-error-description-warning ((t (:foreground "#D8965A" :weight bold))))
 '(TeX-error-description-tip ((t (:foreground "#6EA6D8")))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-dawn-dark)

;;; lumina-dawn-dark-theme.el ends here
