;;; lumina-slate-light-theme.el --- Lumina Slate, light -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Slate, light variant.
;; Cool pale grey paper with deep restrained inks.
;;
;;; Code:

(deftheme lumina-slate-light
  "Lumina Slate, light variant.")

(custom-theme-set-faces
 'lumina-slate-light
 '(default ((t (:foreground "#1F242B" :background "#EDEFF2"))))
 '(fringe ((t (:foreground "#7E8590" :background "#EDEFF2"))))
 '(mode-line ((t (:foreground "#545A64" :background "#E2E5EA"))))
 '(mode-line-inactive ((t (:foreground "#7E8590" :background "#E2E5EA"))))
 '(mode-line-buffer-id ((t (:foreground "#1F5FA8" :weight bold))))
 '(header-line ((t (:foreground "#5A606A" :background "#E2E5EA"))))
 '(header-line-inactive ((t (:foreground "#7E8590" :background "#E2E5EA"))))
 '(header-line-highlight ((t (:foreground "#1F5FA8"))))
 '(cursor ((t (:background "#1F5FA8"))))
 '(region ((t (:background "#DDE2EC" :extend t))))
 '(secondary-selection ((t (:background "#D5D9E0"))))
 '(hl-line ((t (:background "#E2E5EA" :extend t))))
 '(highlight ((t (:background "#D5D9E0"))))
 '(vertical-border ((t (:foreground "#C3C8D2"))))
 '(window-divider ((t (:foreground "#C3C8D2"))))
 '(window-divider-first-pixel ((t (:foreground "#C3C8D2"))))
 '(window-divider-last-pixel ((t (:foreground "#C3C8D2"))))
 '(internal-border ((t (:background "#EDEFF2"))))
 '(line-number ((t (:foreground "#A6ACB8" :background "#EDEFF2"))))
 '(line-number-current-line ((t (:foreground "#1F5FA8" :background "#E2E5EA" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#1F5FA8" :weight bold))))
 '(isearch ((t (:foreground "#EDEFF2" :background "#1F5FA8" :weight bold))))
 '(isearch-fail ((t (:foreground "#B23A40" :background "#EDEFF2"))))
 '(lazy-highlight ((t (:foreground "#EDEFF2" :background "#806510"))))
 '(match ((t (:foreground "#EDEFF2" :background "#2E7250"))))
 '(show-paren-match ((t (:foreground "#2E7250" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#B23A40" :weight bold))))
 '(link ((t (:foreground "#1F5FA8" :underline t))))
 '(link-visited ((t (:foreground "#4A4694" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#B23A40" :weight bold))))
 '(warning ((t (:foreground "#9E5A28" :weight bold))))
 '(success ((t (:foreground "#2E7250" :weight bold))))
 '(escape-glyph ((t (:foreground "#9E5A28"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#7E8590"))))
 '(trailing-whitespace ((t (:background "#B23A40"))))
 '(font-lock-keyword-face ((t (:foreground "#1F5FA8" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#6A707A" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#545A64" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#2E7250"))))
 '(font-lock-function-name-face ((t (:foreground "#1C6E6C"))))
 '(font-lock-variable-name-face ((t (:foreground "#353A42"))))
 '(font-lock-type-face ((t (:foreground "#1A6276" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#4A4694" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#1A6276"))))
 '(font-lock-preprocessor-face ((t (:foreground "#1F5FA8"))))
 '(font-lock-negation-char-face ((t (:foreground "#B23A40"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#1C6E6C"))))
 '(font-lock-property-name-face ((t (:foreground "#1A6276"))))
 '(font-lock-property-use-face ((t (:foreground "#1A6276"))))
 '(font-lock-number-face ((t (:foreground "#9E5A28"))))
 '(font-lock-operator-face ((t (:foreground "#5A606A"))))
 '(font-lock-escape-face ((t (:foreground "#9E5A28"))))
 '(tab-bar ((t (:foreground "#545A64" :background "#E2E5EA"))))
 '(tab-bar-tab ((t (:foreground "#1F5FA8" :background "#EDEFF2" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#7E8590" :background "#E2E5EA"))))
 '(outline-1 ((t (:foreground "#1F5FA8" :weight bold))))
 '(outline-2 ((t (:foreground "#1C6E6C"))))
 '(outline-3 ((t (:foreground "#1A6276"))))
 '(outline-4 ((t (:foreground "#4A4694"))))
 '(outline-5 ((t (:foreground "#1F5FA8"))))
 '(outline-6 ((t (:foreground "#1C6E6C"))))
 '(outline-7 ((t (:foreground "#1A6276"))))
 '(outline-8 ((t (:foreground "#4A4694"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#1F5FA8" :weight bold :height 1.3))))
 '(org-block ((t (:background "#E2E5EA" :extend t))))
 '(org-block-begin-line ((t (:foreground "#6A707A" :background "#E2E5EA" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#9E5A28" :weight bold))))
 '(org-done ((t (:foreground "#2E7250" :weight bold))))
 '(org-table ((t (:foreground "#1F242B"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#4A4694" :underline t))))
 '(org-code ((t (:foreground "#9E5A28"))))
 '(org-verbatim ((t (:foreground "#2E7250"))))
 '(org-special-keyword ((t (:foreground "#4A4694"))))
 '(org-drawer ((t (:foreground "#7E8590"))))
 '(org-meta-line ((t (:foreground "#7E8590"))))
 '(markdown-header-face ((t (:foreground "#1F5FA8" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#1F5FA8" :weight bold))))
 '(magit-section-highlight ((t (:background "#E2E5EA"))))
 '(magit-branch-local ((t (:foreground "#1C6E6C"))))
 '(magit-branch-remote ((t (:foreground "#1A6276"))))
 '(magit-diff-added ((t (:foreground "#2E7250"))))
 '(magit-diff-removed ((t (:foreground "#B23A40"))))
 '(magit-diff-context ((t (:foreground "#7E8590"))))
 '(magit-hash ((t (:foreground "#4A4694"))))
 '(diff-added ((t (:foreground "#2E7250"))))
 '(diff-removed ((t (:foreground "#B23A40"))))
 '(diff-changed ((t (:foreground "#806510"))))
 '(diff-hunk-header ((t (:foreground "#1F5FA8"))))
 '(dired-directory ((t (:foreground "#1F5FA8" :weight bold))))
 '(dired-symlink ((t (:foreground "#1A6276" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#B23A40" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#545A64" :slant italic))))
 '(dired-mark ((t (:foreground "#9E5A28"))))
 '(dired-marked ((t (:foreground "#9E5A28" :weight bold))))
 '(dired-flagged ((t (:foreground "#B23A40" :weight bold))))
 '(dired-warning ((t (:foreground "#9E5A28"))))
 '(dired-ignored ((t (:foreground "#7E8590"))))
 '(dired-perm-write ((t (:foreground "#806510"))))
 '(dired-set-id ((t (:foreground "#8E3C6E"))))
 '(dired-special ((t (:foreground "#4A4694"))))
 '(diredfl-dir-heading ((t (:foreground "#545A64" :background "#E2E5EA" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#1F5FA8" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#1F242B"))))
 '(diredfl-file-suffix ((t (:foreground "#7E8590"))))
 '(diredfl-symlink ((t (:foreground "#1A6276" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#2E7250"))))
 '(diredfl-date-time ((t (:foreground "#7E8590" :slant italic))))
 '(diredfl-number ((t (:foreground "#9E5A28"))))
 '(diredfl-no-priv ((t (:foreground "#7E8590"))))
 '(diredfl-read-priv ((t (:foreground "#2E7250"))))
 '(diredfl-write-priv ((t (:foreground "#806510"))))
 '(diredfl-exec-priv ((t (:foreground "#B23A40"))))
 '(diredfl-dir-priv ((t (:foreground "#1F5FA8" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#1A6276"))))
 '(diredfl-rare-priv ((t (:foreground "#8E3C6E"))))
 '(diredfl-other-priv ((t (:foreground "#4A4694"))))
 '(diredfl-flag-mark ((t (:foreground "#9E5A28" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#E2E5EA"))))
 '(diredfl-deletion ((t (:foreground "#B23A40" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#B23A40" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#9E5A28"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#7E8590"))))
 '(diredfl-ignored-file-name ((t (:foreground "#7E8590"))))
 '(diredfl-autofile-name ((t (:foreground "#1C6E6C"))))
 '(dired-dirname ((t (:foreground "#1F5FA8" :weight bold))))
 '(dirvish-hl-line ((t (:background "#D5D9E0" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#7E8590"))))
 '(dirvish-yank-overlay ((t (:background "#D5D9E0"))))
 '(dirvish-quick-access-entry ((t (:foreground "#1A6276"))))
 '(dirvish-emerge-group-title ((t (:foreground "#1F5FA8" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#5A606A" :background "#E2E5EA"))))
 '(dirvish-header-line-face ((t (:foreground "#5A606A" :background "#E2E5EA"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#9E5A28"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#1F5FA8"))))
 '(vertico-current ((t (:background "#C3C8D2" :extend t))))
 '(corfu-current ((t (:foreground "#1F242B" :background "#C3C8D2"))))
 '(corfu-default ((t (:foreground "#1F242B" :background "#E2E5EA"))))
 '(corfu-border ((t (:foreground "#C3C8D2"))))
 '(corfu-bar ((t (:background "#1F5FA8"))))
 '(orderless-match-face-0 ((t (:foreground "#1F5FA8" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#1C6E6C" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#1A6276" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#2E7250" :weight bold))))
 '(doom-modeline-bar ((t (:background "#1F5FA8"))))
 '(doom-modeline-buffer-path ((t (:foreground "#1F5FA8" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#9E5A28" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#2E7250"))))
 '(doom-modeline-info ((t (:foreground "#2E7250"))))
 '(doom-modeline-warning ((t (:foreground "#9E5A28"))))
 '(doom-modeline-error ((t (:foreground "#B23A40"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#1F5FA8"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#1C6E6C"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#1A6276"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#4A4694"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#2E7250"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#9E5A28"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#B23A40" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-slate-light)

;;; lumina-slate-light-theme.el ends here
