;;; lumina-dawn-dark-theme.el --- Lumina Dawn, dark -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Dawn, dark variant.
;; Warm sepia-neutral ground with hand-mixed deep inks; the reference flavor of the family.
;;
;;; Code:

(deftheme lumina-dawn-dark
  "Lumina Dawn, dark variant.")

(custom-theme-set-faces
 'lumina-dawn-dark
 '(default ((t (:foreground "#E8E1D2" :background "#15120F"))))
 '(fringe ((t (:foreground "#6E6051" :background "#15120F"))))
 '(mode-line ((t (:foreground "#B9AC97" :background "#1A1612"))))
 '(mode-line-inactive ((t (:foreground "#6E6051" :background "#1A1612"))))
 '(mode-line-buffer-id ((t (:foreground "#8A8EE0" :weight bold))))
 '(header-line ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(header-line-inactive ((t (:foreground "#6E6051" :background "#1E1813"))))
 '(header-line-highlight ((t (:foreground "#8A8EE0"))))
 '(cursor ((t (:background "#8A8EE0"))))
 '(region ((t (:background "#2D2A42" :extend t))))
 '(secondary-selection ((t (:background "#241E18"))))
 '(hl-line ((t (:background "#1A1612" :extend t))))
 '(highlight ((t (:background "#241E18"))))
 '(vertical-border ((t (:foreground "#322A20"))))
 '(window-divider ((t (:foreground "#322A20"))))
 '(window-divider-first-pixel ((t (:foreground "#322A20"))))
 '(window-divider-last-pixel ((t (:foreground "#322A20"))))
 '(internal-border ((t (:background "#15120F"))))
 '(line-number ((t (:foreground "#4A3F30" :background "#15120F"))))
 '(line-number-current-line ((t (:foreground "#8A8EE0" :background "#1A1612" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#8A8EE0" :weight bold))))
 '(isearch ((t (:foreground "#15120F" :background "#8A8EE0" :weight bold))))
 '(isearch-fail ((t (:foreground "#E06B62" :background "#15120F"))))
 '(lazy-highlight ((t (:foreground "#15120F" :background "#C9A14E"))))
 '(match ((t (:foreground "#15120F" :background "#6FB585"))))
 '(show-paren-match ((t (:foreground "#6FB585" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#E06B62" :weight bold))))
 '(link ((t (:foreground "#6EA6D8" :underline t))))
 '(link-visited ((t (:foreground "#8A8EE0" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#E06B62" :weight bold))))
 '(warning ((t (:foreground "#D9925A" :weight bold))))
 '(success ((t (:foreground "#6FB585" :weight bold))))
 '(escape-glyph ((t (:foreground "#D9925A"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#6E6051"))))
 '(trailing-whitespace ((t (:background "#E06B62"))))
 '(font-lock-keyword-face ((t (:foreground "#8A8EE0" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7A6E5C" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#8C7E68" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#6FB585"))))
 '(font-lock-function-name-face ((t (:foreground "#6EA6D8"))))
 '(font-lock-variable-name-face ((t (:foreground "#CFC3AD"))))
 '(font-lock-type-face ((t (:foreground "#C9A14E" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#C079A6" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#C079A6"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8A8EE0"))))
 '(font-lock-negation-char-face ((t (:foreground "#E06B62"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#6EA6D8"))))
 '(font-lock-property-name-face ((t (:foreground "#4FA3B8"))))
 '(font-lock-property-use-face ((t (:foreground "#4FA3B8"))))
 '(font-lock-number-face ((t (:foreground "#D9925A"))))
 '(font-lock-operator-face ((t (:foreground "#8C7C68"))))
 '(font-lock-escape-face ((t (:foreground "#C079A6"))))
 '(tab-bar ((t (:foreground "#B9AC97" :background "#1E1813"))))
 '(tab-bar-tab ((t (:foreground "#8A8EE0" :background "#15120F" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#6E6051" :background "#1E1813"))))
 '(outline-1 ((t (:foreground "#8A8EE0" :weight bold))))
 '(outline-2 ((t (:foreground "#6EA6D8"))))
 '(outline-3 ((t (:foreground "#6FB585"))))
 '(outline-4 ((t (:foreground "#C079A6"))))
 '(outline-5 ((t (:foreground "#8A8EE0"))))
 '(outline-6 ((t (:foreground "#6EA6D8"))))
 '(outline-7 ((t (:foreground "#6FB585"))))
 '(outline-8 ((t (:foreground "#C079A6"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#8A8EE0" :weight bold :height 1.3))))
 '(org-block ((t (:background "#1E1813" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7A6E5C" :background "#1E1813" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#D9925A" :weight bold))))
 '(org-done ((t (:foreground "#6FB585" :weight bold))))
 '(org-table ((t (:foreground "#E8E1D2"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#8A8EE0" :underline t))))
 '(org-code ((t (:foreground "#D9925A"))))
 '(org-verbatim ((t (:foreground "#6FB585"))))
 '(org-special-keyword ((t (:foreground "#8A8EE0"))))
 '(org-drawer ((t (:foreground "#6E6051"))))
 '(org-meta-line ((t (:foreground "#6E6051"))))
 '(markdown-header-face ((t (:foreground "#8A8EE0" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#8A8EE0" :weight bold))))
 '(magit-section-highlight ((t (:background "#1A1612"))))
 '(magit-branch-local ((t (:foreground "#6EA6D8"))))
 '(magit-branch-remote ((t (:foreground "#6FB585"))))
 '(magit-diff-added ((t (:foreground "#6FB585"))))
 '(magit-diff-removed ((t (:foreground "#E06B62"))))
 '(magit-diff-context ((t (:foreground "#6E6051"))))
 '(magit-hash ((t (:foreground "#8A8EE0"))))
 '(diff-added ((t (:foreground "#6FB585"))))
 '(diff-removed ((t (:foreground "#E06B62"))))
 '(diff-changed ((t (:foreground "#C9A14E"))))
 '(diff-hunk-header ((t (:foreground "#8A8EE0"))))
 '(dired-directory ((t (:foreground "#8A8EE0" :weight bold))))
 '(dired-symlink ((t (:foreground "#4FA3B8" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#E06B62" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#B9AC97" :slant italic))))
 '(dired-mark ((t (:foreground "#D9925A"))))
 '(dired-marked ((t (:foreground "#D9925A" :weight bold))))
 '(dired-flagged ((t (:foreground "#E06B62" :weight bold))))
 '(dired-warning ((t (:foreground "#D9925A"))))
 '(dired-ignored ((t (:foreground "#6E6051"))))
 '(dired-perm-write ((t (:foreground "#C9A14E"))))
 '(dired-set-id ((t (:foreground "#C079A6"))))
 '(dired-special ((t (:foreground "#8A8EE0"))))
 '(diredfl-dir-heading ((t (:foreground "#B9AC97" :background "#1E1813" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#8A8EE0" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#E8E1D2"))))
 '(diredfl-file-suffix ((t (:foreground "#6E6051"))))
 '(diredfl-symlink ((t (:foreground "#4FA3B8" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#6FB585"))))
 '(diredfl-date-time ((t (:foreground "#6E6051" :slant italic))))
 '(diredfl-number ((t (:foreground "#D9925A"))))
 '(diredfl-no-priv ((t (:foreground "#6E6051"))))
 '(diredfl-read-priv ((t (:foreground "#6FB585"))))
 '(diredfl-write-priv ((t (:foreground "#C9A14E"))))
 '(diredfl-exec-priv ((t (:foreground "#E06B62"))))
 '(diredfl-dir-priv ((t (:foreground "#8A8EE0" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#4FA3B8"))))
 '(diredfl-rare-priv ((t (:foreground "#C079A6"))))
 '(diredfl-other-priv ((t (:foreground "#8A8EE0"))))
 '(diredfl-flag-mark ((t (:foreground "#D9925A" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#1A1612"))))
 '(diredfl-deletion ((t (:foreground "#E06B62" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#E06B62" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#D9925A"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#6E6051"))))
 '(diredfl-ignored-file-name ((t (:foreground "#6E6051"))))
 '(diredfl-autofile-name ((t (:foreground "#4FB0A6"))))
 '(dired-dirname ((t (:foreground "#8A8EE0" :weight bold))))
 '(dirvish-hl-line ((t (:background "#241E18" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#6E6051"))))
 '(dirvish-yank-overlay ((t (:background "#241E18"))))
 '(dirvish-quick-access-entry ((t (:foreground "#4FA3B8"))))
 '(dirvish-emerge-group-title ((t (:foreground "#8A8EE0" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(dirvish-header-line-face ((t (:foreground "#8C7C68" :background "#1E1813"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#D9925A"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#8A8EE0"))))
 '(vertico-current ((t (:background "#241E18" :extend t))))
 '(corfu-current ((t (:foreground "#E8E1D2" :background "#241E18"))))
 '(corfu-default ((t (:foreground "#E8E1D2" :background "#1E1813"))))
 '(corfu-border ((t (:foreground "#322A20"))))
 '(corfu-bar ((t (:background "#8A8EE0"))))
 '(orderless-match-face-0 ((t (:foreground "#8A8EE0" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#6EA6D8" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#6FB585" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#6FB585" :weight bold))))
 '(doom-modeline-bar ((t (:background "#8A8EE0"))))
 '(doom-modeline-buffer-path ((t (:foreground "#8A8EE0" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#D9925A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#6FB585"))))
 '(doom-modeline-info ((t (:foreground "#6FB585"))))
 '(doom-modeline-warning ((t (:foreground "#D9925A"))))
 '(doom-modeline-error ((t (:foreground "#E06B62"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#8A8EE0"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#6EA6D8"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#6FB585"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#C079A6"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#4FB0A6"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#D9925A"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#E06B62" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-dawn-dark)

;;; lumina-dawn-dark-theme.el ends here
