;;; lumina-indigo-dark-theme.el --- Lumina Indigo, dark -*- lexical-binding: t; -*-
;;
;; Author: razik <https://github.com/RazikSF>
;; Maintainer: razik <https://github.com/RazikSF>
;; URL: https://github.com/RazikSF/lumina-themes
;; Version: 1.0.0
;; Package-Requires: ((emacs "26.1"))
;; Keywords: faces, themes
;;
;;; Commentary:
;;
;; Lumina Indigo, dark variant.
;; Deep indigo ground with copper and verdigris accents.
;;
;;; Code:

(deftheme lumina-indigo-dark
  "Lumina Indigo, dark variant.")

(custom-theme-set-faces
 'lumina-indigo-dark
 '(default ((t (:foreground "#DEE0EC" :background "#141625"))))
 '(fringe ((t (:foreground "#5B6184" :background "#141625"))))
 '(mode-line ((t (:foreground "#8E93AE" :background "#0F1019"))))
 '(mode-line-inactive ((t (:foreground "#5B6184" :background "#0F1019"))))
 '(mode-line-buffer-id ((t (:foreground "#6E88E4" :weight bold))))
 '(header-line ((t (:foreground "#7C82A4" :background "#0F1019"))))
 '(header-line-inactive ((t (:foreground "#5B6184" :background "#0F1019"))))
 '(header-line-highlight ((t (:foreground "#6E88E4"))))
 '(cursor ((t (:background "#6E88E4"))))
 '(region ((t (:background "#31354F" :extend t))))
 '(secondary-selection ((t (:background "#262A40"))))
 '(hl-line ((t (:background "#1E2133" :extend t))))
 '(highlight ((t (:background "#262A40"))))
 '(vertical-border ((t (:foreground "#31354F"))))
 '(window-divider ((t (:foreground "#31354F"))))
 '(window-divider-first-pixel ((t (:foreground "#31354F"))))
 '(window-divider-last-pixel ((t (:foreground "#31354F"))))
 '(internal-border ((t (:background "#141625"))))
 '(line-number ((t (:foreground "#414763" :background "#141625"))))
 '(line-number-current-line ((t (:foreground "#6E88E4" :background "#1E2133" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "#6E88E4" :weight bold))))
 '(isearch ((t (:foreground "#141625" :background "#6E88E4" :weight bold))))
 '(isearch-fail ((t (:foreground "#E0707C" :background "#141625"))))
 '(lazy-highlight ((t (:foreground "#141625" :background "#DCC36E"))))
 '(match ((t (:foreground "#141625" :background "#54C194"))))
 '(show-paren-match ((t (:foreground "#54C194" :weight bold))))
 '(show-paren-mismatch ((t (:foreground "#E0707C" :weight bold))))
 '(link ((t (:foreground "#6E88E4" :underline t))))
 '(link-visited ((t (:foreground "#9286E4" :underline t))))
 '(button ((t (:inherit link))))
 '(error ((t (:foreground "#E0707C" :weight bold))))
 '(warning ((t (:foreground "#E0935A" :weight bold))))
 '(success ((t (:foreground "#54C194" :weight bold))))
 '(escape-glyph ((t (:foreground "#E0935A"))))
 '(nobreak-space ((t (:inherit escape-glyph))))
 '(shadow ((t (:foreground "#5B6184"))))
 '(trailing-whitespace ((t (:background "#E0707C"))))
 '(font-lock-keyword-face ((t (:foreground "#6E88E4" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7A80A0" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:foreground "#888EAA" :slant italic))))
 '(font-lock-string-face ((t (:foreground "#E0935A"))))
 '(font-lock-function-name-face ((t (:foreground "#46BAB4"))))
 '(font-lock-variable-name-face ((t (:foreground "#C8CBDC"))))
 '(font-lock-type-face ((t (:foreground "#54C194" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#9286E4" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#58B6DE"))))
 '(font-lock-preprocessor-face ((t (:foreground "#6E88E4"))))
 '(font-lock-negation-char-face ((t (:foreground "#E0707C"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-function-call-face ((t (:foreground "#46BAB4"))))
 '(font-lock-property-name-face ((t (:foreground "#54C194"))))
 '(font-lock-property-use-face ((t (:foreground "#54C194"))))
 '(font-lock-number-face ((t (:foreground "#DC7CBA"))))
 '(font-lock-operator-face ((t (:foreground "#7C82A4"))))
 '(font-lock-escape-face ((t (:foreground "#E0935A"))))
 '(tab-bar ((t (:foreground "#8E93AE" :background "#0F1019"))))
 '(tab-bar-tab ((t (:foreground "#6E88E4" :background "#141625" :weight bold))))
 '(tab-bar-tab-inactive ((t (:foreground "#5B6184" :background "#0F1019"))))
 '(outline-1 ((t (:foreground "#6E88E4" :weight bold))))
 '(outline-2 ((t (:foreground "#46BAB4"))))
 '(outline-3 ((t (:foreground "#E0935A"))))
 '(outline-4 ((t (:foreground "#54C194"))))
 '(outline-5 ((t (:foreground "#6E88E4"))))
 '(outline-6 ((t (:foreground "#46BAB4"))))
 '(outline-7 ((t (:foreground "#E0935A"))))
 '(outline-8 ((t (:foreground "#54C194"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-level-6 ((t (:inherit outline-6))))
 '(org-level-7 ((t (:inherit outline-7))))
 '(org-level-8 ((t (:inherit outline-8))))
 '(org-document-title ((t (:foreground "#6E88E4" :weight bold :height 1.3))))
 '(org-block ((t (:background "#0F1019" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7A80A0" :background "#0F1019" :slant italic :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-todo ((t (:foreground "#E0935A" :weight bold))))
 '(org-done ((t (:foreground "#54C194" :weight bold))))
 '(org-table ((t (:foreground "#DEE0EC"))))
 '(org-link ((t (:inherit link))))
 '(org-date ((t (:foreground "#9286E4" :underline t))))
 '(org-code ((t (:foreground "#E0935A"))))
 '(org-verbatim ((t (:foreground "#54C194"))))
 '(org-special-keyword ((t (:foreground "#9286E4"))))
 '(org-drawer ((t (:foreground "#5B6184"))))
 '(org-meta-line ((t (:foreground "#5B6184"))))
 '(markdown-header-face ((t (:foreground "#6E88E4" :inherit bold))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face))))
 '(markdown-code-face ((t (:inherit org-block))))
 '(markdown-link-face ((t (:inherit link))))
 '(magit-section-heading ((t (:foreground "#6E88E4" :weight bold))))
 '(magit-section-highlight ((t (:background "#1E2133"))))
 '(magit-branch-local ((t (:foreground "#46BAB4"))))
 '(magit-branch-remote ((t (:foreground "#54C194"))))
 '(magit-diff-added ((t (:foreground "#54C194"))))
 '(magit-diff-removed ((t (:foreground "#E0707C"))))
 '(magit-diff-context ((t (:foreground "#5B6184"))))
 '(magit-hash ((t (:foreground "#9286E4"))))
 '(diff-added ((t (:foreground "#54C194"))))
 '(diff-removed ((t (:foreground "#E0707C"))))
 '(diff-changed ((t (:foreground "#DCC36E"))))
 '(diff-hunk-header ((t (:foreground "#6E88E4"))))
 '(dired-directory ((t (:foreground "#6E88E4" :weight bold))))
 '(dired-symlink ((t (:foreground "#58B6DE" :slant italic))))
 '(dired-broken-symlink ((t (:foreground "#E0707C" :slant italic :underline t))))
 '(dired-header ((t (:foreground "#8E93AE" :slant italic))))
 '(dired-mark ((t (:foreground "#E0935A"))))
 '(dired-marked ((t (:foreground "#E0935A" :weight bold))))
 '(dired-flagged ((t (:foreground "#E0707C" :weight bold))))
 '(dired-warning ((t (:foreground "#E0935A"))))
 '(dired-ignored ((t (:foreground "#5B6184"))))
 '(dired-perm-write ((t (:foreground "#DCC36E"))))
 '(dired-set-id ((t (:foreground "#DC7CBA"))))
 '(dired-special ((t (:foreground "#9286E4"))))
 '(diredfl-dir-heading ((t (:foreground "#8E93AE" :background "#0F1019" :slant italic))))
 '(diredfl-dir-name ((t (:foreground "#6E88E4" :weight bold))))
 '(diredfl-file-name ((t (:foreground "#DEE0EC"))))
 '(diredfl-file-suffix ((t (:foreground "#5B6184"))))
 '(diredfl-symlink ((t (:foreground "#58B6DE" :slant italic))))
 '(diredfl-executable-tag ((t (:foreground "#54C194"))))
 '(diredfl-date-time ((t (:foreground "#5B6184" :slant italic))))
 '(diredfl-number ((t (:foreground "#E0935A"))))
 '(diredfl-no-priv ((t (:foreground "#5B6184"))))
 '(diredfl-read-priv ((t (:foreground "#54C194"))))
 '(diredfl-write-priv ((t (:foreground "#DCC36E"))))
 '(diredfl-exec-priv ((t (:foreground "#E0707C"))))
 '(diredfl-dir-priv ((t (:foreground "#6E88E4" :weight bold))))
 '(diredfl-link-priv ((t (:foreground "#58B6DE"))))
 '(diredfl-rare-priv ((t (:foreground "#DC7CBA"))))
 '(diredfl-other-priv ((t (:foreground "#9286E4"))))
 '(diredfl-flag-mark ((t (:foreground "#E0935A" :weight bold))))
 '(diredfl-flag-mark-line ((t (:background "#1E2133"))))
 '(diredfl-deletion ((t (:foreground "#E0707C" :weight bold))))
 '(diredfl-deletion-file-name ((t (:foreground "#E0707C" :slant italic))))
 '(diredfl-compressed-file-name ((t (:foreground "#E0935A"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#5B6184"))))
 '(diredfl-ignored-file-name ((t (:foreground "#5B6184"))))
 '(diredfl-autofile-name ((t (:foreground "#46BAB4"))))
 '(dired-dirname ((t (:foreground "#6E88E4" :weight bold))))
 '(dirvish-hl-line ((t (:background "#262A40" :extend t))))
 '(dirvish-subtree-state ((t (:foreground "#5B6184"))))
 '(dirvish-yank-overlay ((t (:background "#262A40"))))
 '(dirvish-quick-access-entry ((t (:foreground "#58B6DE"))))
 '(dirvish-emerge-group-title ((t (:foreground "#6E88E4" :weight bold))))
 '(dirvish-header-line ((t (:foreground "#7C82A4" :background "#0F1019"))))
 '(dirvish-header-line-face ((t (:foreground "#7C82A4" :background "#0F1019"))))
 '(dirvish-vc-needs-merge-face ((t (:foreground "#E0935A"))))
 '(all-the-icons-dired-dir-face ((t (:foreground "#6E88E4"))))
 '(vertico-current ((t (:background "#31354F" :extend t))))
 '(corfu-current ((t (:foreground "#DEE0EC" :background "#31354F"))))
 '(corfu-default ((t (:foreground "#DEE0EC" :background "#0F1019"))))
 '(corfu-border ((t (:foreground "#31354F"))))
 '(corfu-bar ((t (:background "#6E88E4"))))
 '(orderless-match-face-0 ((t (:foreground "#6E88E4" :weight bold))))
 '(orderless-match-face-1 ((t (:foreground "#46BAB4" :weight bold))))
 '(orderless-match-face-2 ((t (:foreground "#E0935A" :weight bold))))
 '(orderless-match-face-3 ((t (:foreground "#54C194" :weight bold))))
 '(doom-modeline-bar ((t (:background "#6E88E4"))))
 '(doom-modeline-buffer-path ((t (:foreground "#6E88E4" :weight bold))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E0935A" :weight bold))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#54C194"))))
 '(doom-modeline-info ((t (:foreground "#54C194"))))
 '(doom-modeline-warning ((t (:foreground "#E0935A"))))
 '(doom-modeline-error ((t (:foreground "#E0707C"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#6E88E4"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#46BAB4"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#E0935A"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#54C194"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#9286E4"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#DC7CBA"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#E0707C" :weight bold)))) )

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'lumina-indigo-dark)

;;; lumina-indigo-dark-theme.el ends here
